### ISSUE TITLE
get_stream_url: youtube vs googleusercontent links?

### ISSUE THREAD

**Issue by fcaza** [simon-weber/gmusicapi#105]
Hi,
Sometimes, when i use get_stream_url(song_id), it returns a videoplayback instead of a stream..
I get           http://r4---sn-apn7en7r.c.youtube.com/videoplayback?id=.... like URL
instead of   http://t.doc-0-0-sj.sj.googleusercontent.com/stream?id=..... 

Is it something that i need to deal with in my library? 
Do you know if there is a policy to get a stream instead of videoplayback?

Thanks in advance,
Franck

**Comment by shinevalve** [comment]
hi can you send me please to crghadiya@gmail.com
