### ISSUE TITLE
Support sorting with loadalltracks call

### ISSUE THREAD

**Issue by simon-weber** [simon-weber/gmusicapi#16]
Google will sort the returned songs with, for example, `ascendingSort=true` and `sort="album"`. This should be an option in `get_all_songs`.

**Comment by thebigmunch** [comment]
So, this was for ``Webclient.get_all_songs``, which has not existed for some time now : P

I'm not sure if the other client interfaces have the same kind of sorting baked in. Should this be closed or turned into a desired feature for the ``get_*_songs`` methods for ``Mobileclient`` and ``Musicmanager``. Even if it's not directly supported in the calls, we could do it on the client-side. I already do this for output in my scripts for predictable output and processing order, but I'm not sure it's something that needs to be included in gmusicapi if it's not already in the calls.

**Comment by simon-weber** [comment]
I'm down to just close it.
