### ISSUE TITLE
2-step verification (OAuth) not supported in mobileclient or webclient

### ISSUE THREAD

**Issue by jakealstad** [simon-weber/gmusicapi#168]
https://support.google.com/accounts/answer/180744?hl=en

I plan to investigate what it will take to implement this.

**Comment by sciencepro** [comment]
Will ClientLogin's upcoming deprecation be a problem?  This is the scheme that's being used with normal username/password login, correct?

http://googledevelopers.blogspot.com/2015/02/reminder-clientlogin-shutdown-scheduled.html

**Comment by simon-weber** [comment]
Right, plaintext auth for both the webclient and mobileclient uses clientlogin.

Here's the current state of things (as compared to https://github.com/simon-weber/Unofficial-Google-Music-API/issues/168#issuecomment-36445395):
* web: we use clientlogin. unknown what google uses.
* android: we use clientlogin. google [uses oauth](https://github.com/simon-weber/Unofficial-Google-Music-API/issues/168#issuecomment-68190964), though it's unclear whether we can also use it.
* music manager: we and google both use oauth.
* iOS: we don't use this api. google uses oauth in a way that [I think would work for us](https://github.com/simon-weber/Unofficial-Google-Music-API/issues/290).

**Comment by sciencepro** [comment]
Thanks for the clarification.  What I'm not clear is if the method I'm using of getting an auth token from AccountManager on Android falls under ClientLogin or if it's something else.  

Hopefully by April another one of these methods will show some promise.  I'll see what I can start exploring when I get a chance.

**Comment by simon-weber** [comment]
AccountManager for google music is definitely capable of using oauth - that's what I referred to in https://github.com/simon-weber/Unofficial-Google-Music-API/issues/168#issuecomment-68190964 - but I'm not sure if there's a specific way you have to interact with it on android to do that.

**Comment by simon-weber** [comment]
It looks like [other code](http://codingteam.net/project/googleplaydownloader/browse/src/ext_libs/android-checkin/src/main/java/com/android/checkin/Checkin.java/?rev=35#line-63) has the [master token flow](http://sbktech.blogspot.com/2014/01/inside-android-play-services-magic.html) working outside of android. Some notes:
* I think they took the client_sig from the gsf app and are posing as it. Like the linked article describes, this is used in place of a client id.
* I'm not sure why they don't need to provide an androidId. They link to [a library that can create a fake android id](https://github.com/nviennot/android-checkin), so maybe they need one later on.

**Comment by simon-weber** [comment]
I've got the master token flow working!

I should have a working mobileclient in a few days.

**Comment by simon-weber** [comment]
https://github.com/simon-weber/Unofficial-Google-Music-API/commit/b0e05e671c347681e145df15305dd076ff065753 gets things working again (and doesn't give the insecure apps warning). I've yet to try 2fa, but it should be possible to support it now, too.

**Comment by simon-weber** [comment]
2fa support will be a bit weird. Here's what the 2fa flow looks like:
* master token request results in an error that returns a url for the user to visit
* the url has the 2fa form
* on success, the client is redirected to a page that sets the master token as a cookie

Notice that the last step doesn't actually show the value in a user-readable format (unlike, say, the Music Manager's oauth flow that has the "copy and paste this value" copy). I see two options to support this:
* make login optionally accept a master token. when gmusicapi sees the 2fa error, give the url to client code. client code tells users to visit url, enter code, then copy out the cookie value (which could be made easier with a bookmarklet) and provide it in a login call.
* make login optionally accept a 2fa code. when gmusicapi sees the 2fa error, it posts the code to the url itself, then retrieves the cookie.

The first option is what the music manager does, but having users deal with cookies is super weird. The second option seems easier for everyone, but could be flaky if the login form changes often.

**Comment by sciencepro** [comment]
This is really awesome, thanks for the update.
Regarding 2FA, depending on the scenario, copying out the cookie might not be so bad, but will this still work if the cookie is domain restricted?

**Comment by mgillespie** [comment]
I would hope whatever system is in use, it works on systems that don't have
a web browser or desktop installed. My setup is a headless raspberrypi, I
suspect there are a lot of headless systems these days running this.

With regards to 2FA does application specific passwords not mitigate this?
On 15 May 2015 01:42, "Simon Weber" <notifications@github.com> wrote:
>
> 2fa support will be a bit weird. Here's what the 2fa flow looks like:
>
> master token request results in an error that returns a url for the user
to visit
> the url has the 2fa form
> on success, the client is redirected to a page that sets the master token
as a cookie
>
> Notice that the last step doesn't actually show the value in a
user-readable format (unlike, say, the Music Manager's oauth flow that has
the "copy and paste this value" copy). I see two options to support this:
>
> make login optionally accept a master token. when gmusicapi sees the 2fa
error, give the url to client code. client code tells users to visit url,
enter code, then copy out the cookie value (which could be made easier with
a bookmarklet) and provide it in a login call.
> make login optionally accept a 2fa code. when gmusicapi sees the 2fa
error, it posts the code to the url itself, then retrieves the cookie.
>
> The first option is what the music manager does, but having users deal
with cookies is super weird. The second option seems easier for everyone,
but could be flaky if the login form changes often.

**Comment by sciencepro** [comment]
Is there any reason why a similar approach wouldn't work for Webclient?  I'm going to give it a try.  I still need to use Webclient to obtain a deviceId.

**Comment by sciencepro** [comment]
Actually, I realize the androidId is required to do the login, so it's sort of a chicken and egg problem.

**Comment by diraimondo** [comment]
Given the knowledge of device_id, I can confirm that mc.login on develop branch works. On gmusicproxy I use function get_registered_devices() to get the device ids list. Now, it is broken and there is no way to discover such keys on a fresh installation.

**Comment by thebigmunch** [comment]
@diraimondo: Technically, you can login with a bogus device ID, but, of course, that's not really a great idea.

And while I am an Android user, many people are not. So having it take an Android ID only (or naming it that way if it takes others) is also a bit of a usability issue. I've had to put some things on hold for a bit due to this as well : (

**Comment by diraimondo** [comment]
The requirement for a valid Android device id was already there on the mobileclient api before.

**Comment by thebigmunch** [comment]
> The requirement for a valid Android device id was already there on the mobileclient api before.

No. The requirement of a valid mobile device id (Android, iOS or even Chrome app) was already there for streaming, not specifically Android.

**Comment by siebert** [comment]
I'm wondering if gmusicapi already works using an application-specific password on accounts with 2-step verification enabled. If so, why bother at all implementing a proper 2-step verification workflow?

**Comment by simon-weber** [comment]
My understanding is that app-specific passwords were a hack because clientlogin didn't support 2fa, and that they won't work now. I think they're not needed when everything uses oauth in the right way (mobileclient doesn't).

**Comment by diraimondo** [comment]
I would like to use a proper 2fa authentication with gmusicapi without application-specific passwords. Is it already working?

**Comment by siebert** [comment]
App-specific passwords are a kind of hack to enable access to 2fa protected google accounts for applications which don't support 2fa. It still works for me and is necessary to use a gmail account in Thunderbird among others.

**Comment by simon-weber** [comment]
The current mobileclient interface seems to support the formerly ios-specific skyjam scope now, so we can merge this into https://github.com/simon-weber/gmusicapi/issues/426#issuecomment-250996392.
