### ISSUE TITLE
Fix webclient.change_song_metadata

### ISSUE THREAD

**Issue by simon-weber** [simon-weber/gmusicapi#224]
webclient.change_song_metadata been broken, and needs to be updated to use jsarray. [I had removed it](https://github.com/simon-weber/Unofficial-Google-Music-API/commit/8af538d7b1db3edbff6ce3bc133de6e810e9d751) with the expectation that mobileclient.change_song_metadata duplicated it, but as of #209 that isn't true.

**Comment by simon-weber** [comment]
format=json appears to work now, and might make this significantly easier.

**Comment by thebigmunch** [comment]
Can this be closed now as of #490? And I think #229 could be closed as well with the status given to the Webclient and the fact that it's been dead for over 2 years.

**Comment by simon-weber** [comment]
Fine by me.
