### ISSUE TITLE
Add new Songza styles playlists

### ISSUE THREAD

**Issue by jwdempsey** [simon-weber/gmusicapi#295]
Is it possible to get this data in the Mobile client?

**Comment by rolandrohde** [comment]
Hi,

is there any progress on supporting Playlists?

**Comment by simon-weber** [comment]
Sorry, I haven't done any work on it.

**Comment by thebigmunch** [comment]
These are the Listen Now Situations I implemented in #460 for another issue. Didn't make the connection with this until looking back at old issues and reading through this one. Should be able to close this.

**Comment by simon-weber** [comment]
Sweet; thanks.
