### ISSUE TITLE
Support for managing your own library and uploaded music?

### ISSUE THREAD

**Issue by mikespub** [simon-weber/gmusicapi#301]
It seems the support for "all access" songs, playlists etc. is coming along nicely, but support for managing your own library and songs is lacking.

For instance, there doesn't seem to be an easy way to browse your own library for all artists, albums or genres as shown in the web interface, or to request your own uploaded songs per artist, album or genre. Those API functions only seem to work with "official" artists, albums and songs anymore - even if Google auto-matched many of your own songs in your library.

Also, it should be possible to update the metadata of albums and songs in your own library. This feature seems to have totally disappeared after moving the APIs from Webclient to Mobileclient.

Thanks & keep up the good work,

Mike.

**Comment by mikespub** [comment]
BTW, adding the fixes from #229 with some field mapping to convert song metadata from wc to mc format still seems to work.

**Comment by DanNixon** [comment]
There is ```Mobileclient.change_song_metadata()``` for editing track information.

Other than that I just load the full library and build whatever structure suites the application.

**Comment by simon-weber** [comment]
> there doesn't seem to be an easy way to browse your own library for all artists, albums or genres as shown in the web interface

Pretty much all filtering/sorting is done clientside, so I don't have any plans of implementing it.

> Those API functions only seem to work with "official" artists, albums and songs

Which calls are you referring to?

**Comment by mikespub** [comment]
mc.get_all_songs() works to retrieve your own songs, but mc.get_track_info(), mc.get_artist_info() and mc.get_album_info() don't work to retrieve information about particular tracks, artists and/or albums unless they're All Access ones.

**Comment by mikespub** [comment]
Note: this is probably a commercial decision of Google, but it means that the feature-set available via mobileclient isn't the same as that via webclient anymore. So you might consider keeping a few API functions in webclient instead of moving everything to mobileclient in the long run :-)

**Comment by simon-weber** [comment]
> don't work to retrieve information about particular tracks, artists and/or albums unless they're All Access ones

Ah, I see what you're saying. This limitation is a bummer, but it's not that unreasonable from the point of view of their backend: the api assumes there's a heavy stateful client on the other end. The client pretty much just calls get_all_songs once, then receives push updates from the server and updates the local state.

It's not reasonable for the client to maintain the state of the entire All Access database, though, so that data is exposed piecemeal through the calls you're referring to.

> it means that the feature-set available via mobileclient isn't the same as that via webclient anymore. So you might consider keeping a few API functions in webclient instead of moving everything to mobileclient in the long run :-)

Generally I try to do this :grin:. Anything that's entirely duplicated gets removed because the webclient is such a pain, but things like webclient streaming have tradeoffs compared to the mobileclient. Things I'm planning to support indefinitely are listed [here](http://unofficial-google-music-api.readthedocs.org/en/develop/reference/webclient.html#gmusicapi.clients.Webclient).

**Comment by mikespub** [comment]
That's clear, thanks. Problem is that some things that were moved from webclient don't work as expected in mobileclient (for non-all access songs).

So if we want to update songs, albums, artists or genres in the library, the current API won't let us do it even if the actual web interface does...

But I guess that's my own itch to scratch :-)

**Comment by simon-weber** [comment]
I don't think there's an action item here, so I'm going to close this. Feel free to reopen if I missed something.

**Comment by ZachSaucier** [comment]
So to be clear, I can't use this API to edit the metadata of tracks that I upload? I'm trying to remove ".mp3" from the track name of all songs that I've uploaded that have it.

I've found all the track's metadata in the IndexDB of the Application section of devtools and can download it if need be.

**Comment by simon-weber** [comment]
Right, unfortunately: Google only allowed that through the webclient, which was painful to maintain and eventually removed (in https://github.com/simon-weber/gmusicapi/commit/8af538d7b1db3edbff6ce3bc133de6e810e9d751).

You could try to hack something together with that code (though I probably wouldn't take a PR for it), though it may be easier to just do it with javascript.
