### ISSUE TITLE
Add get_registered_devices method and a deauthorize method to Mobileclient

### ISSUE THREAD

**Issue by thebigmunch** [simon-weber/gmusicapi#315]
The Google Music Android app supports viewing and deauthorizing devices using the ``devicemanagementinfo`` mclients endpoint.

``GET https://mclients.googleapis.com/sj/v1.10/devicemanagementinfo?alt=json&hl=en_US``
``DELETE https://mclients.googleapis.com/sj/v1.10/devicemanagementinfo?delete-id=0x<deviceid>``

**Comment by simon-weber** [comment]
:+1: nice find

**Comment by foreverguest** [comment]
Just submitted PR #316 based on this call, it's working good for me, hope it is right.

**Comment by thebigmunch** [comment]
@foreverguest You missed some stuff that needs to be in the protocol for schema validation, some stuff in the docstring, there needs to be a test added, and it needs to be added to the docs index.

I have a working version I made last night with all the docs, tests, etc that I will submit later today. I also added a deauthorize_device method that I just need to test out and add the docs before submitting.

**Comment by thebigmunch** [comment]
Also, you didn't account for someone calling get_registered_devices on an account with no registered devices. When this happens, it should return an empty list, but, as it is, it would throw an error instead.

**Comment by foreverguest** [comment]
OK, I'm not used to this procedures. I'll wait for your implementation, thanks.

**Comment by simon-weber** [comment]
@foreverguest no worries; the effort is appreciated regardless =) Normally I'd work with you to get it merged, but it look's like thebigmunch beat you to it.

**Comment by thebigmunch** [comment]
Yeah, just got too busy yesterday to submit. Let's see how this goes.

**Comment by thebigmunch** [comment]
Hopefully that covers it, but I'd leave this open until I submit the deauthorize_device method : P Just need to get some time to finish testing.

**Comment by simon-weber** [comment]
Whoops, missed that part of it; sounds good.

**Comment by thebigmunch** [comment]
Just trawling through old issues to look for stuff to do and found #76 : P

Two issues with one stone : )

**Comment by thebigmunch** [comment]
Additionally, I (or someone) should look into an endpoint for registering a device.

**Comment by simon-weber** [comment]
> I (or someone) should look into an endpoint for registering a device.

The last time I looked at this it happened implicitly when you logged in from a new device.
