### ISSUE TITLE
Idea: Rename repository to gmusicapi

### ISSUE THREAD

**Issue by thebigmunch** [simon-weber/gmusicapi#320]
The fact that the repository wasn't named gmusicapi has always bugged me. There are some tangible benefits that come with it being named that way (like showing in repository search results for gmusicapi on GitHub) and some, perhaps, less tangible benefits like gmusicapi is the actual name of the project so it'd just make more sense.

Back then, it wasn't really an option. But almost two years ago now, GitHub implemented [automatic redirection](https://github.com/blog/1508-repository-redirects-are-here) for repo renames and transfers. As far as I'm aware, the only issue to renaming would be if there were GitHub Pages involved, which is not the case here.

**Comment by simon-weber** [comment]
Yeah, this is something I've thought about. The only real positive I can think of for the current name is the link juice, haha.

**Comment by thebigmunch** [comment]
I'm not even sure how much link juice you get from it now, tbh. The GitHub repo doesn't show in the first 3 pages (all I checked) of a Google search for ``Google Music``, for example. The ReadTheDocs page was on the second page, but don't think that'd be affected since the title of that page wouldn't change. On the flip side, the GitHub repo was the 2nd result after the PyPi page for ``gmusicapi`` (my script repo is 3rd, lulz). Of course, a search for ``Google Music python`` or ``Google Music api`` puts the GitHub repo as the first result followed by ReadTheDocs and PyPi, but I'm not really sure that'd be affected much since Google Music will still be included in the repo description and README.

**Comment by simon-weber** [comment]
https://github.com/simon-weber/gmusicapi!
