### ISSUE TITLE
mobileclient.change_song_metadata only supports rating

### ISSUE THREAD

**Issue by ecoskian** [simon-weber/gmusicapi#322]
I have tried something along the lines of

```
api = Mobileclient()
api.login(...) # this returns True
songs = api.get_all_songs()
songs[0]['title'] = 'new title'
songs[0]['artist'] = 'new artist'
api.change_song_metadata(songs[0])
```
This results in no visible change when I look at songs from any of my devices, and if I call `get_all_songs` again it returns the original information for `songs[0]`

**Comment by thebigmunch** [comment]
There are a few issues and a pull request for this already; they're pretty easy to find. The mobile endpoint only supports changing play count. The Webclient.change_song_metadata method needed some changes to work. A user opened a pull request for this, but the work was never finished.

**Comment by siebert** [comment]
Well, had I know this I wouldn't have to implement it myself. On the other hand I now know that I don't need to waste more time on creating a pull request for my change.

The usage of 3 different APIs is also quite frustrating. As the Google webclient API seems to be feature complete, I would love to see a major rewrite of gmusicapi which only uses the webclient API.

**Comment by thebigmunch** [comment]
There is also an issue for a unified client. However, the Google webclient api, nor any other client API is anywhere near feature complete. Many of the things that you might think that would come from a different API actually do. E.g. the webclient and Chrome app use the music manager api to upload songs.

In fact, as the mobile api has added more endpoints, the gmusicapi Webclient calls that do the same thing have been deprecated and eventually removed. Dealing with the Google webclient API is more difficult and it's more apt to change and break things (as found during gmusicapi's history).

**Comment by siebert** [comment]
I didn't know that the webclient uses that music manager api, too. But it should be possible to eliminate the mobile client api. I understand that the webclient api is more volatile, but the mobile client has it downsides, too. With the webclient we don't have to register and manage fake android devices and using Fiddler etc. to snoop traffic is way more easy on the webclient than on an android device.

And the mobile client apis are often more limited, for example I can't any longer distinguish matched and uploaded songs as the mobile client api doesn't include the song type.

**Comment by simon-weber** [comment]
> but the mobile client has it downsides, too

so does the webclient =) The most important one is that I'm not confident in our ability to keep it working, since unlike the installed clients Google doesn't have to provide backwards compatibility. This causes problems with no warning (most recently, breaking all streaming in https://github.com/simon-weber/Unofficial-Google-Music-API/issues/318).

**Comment by thebigmunch** [comment]
The mobile client api contains quite a bit that the webclient api doesn't. The Webclient api contains only a few things that the mobile client api doesn't.

**Comment by thebigmunch** [comment]
It sucks, but we, as developers and users, are stuck with what Google gives us. And none of these are official, public APIs to begin with, so it's not like we can really petition Google to make it easier for us to use either.

**Comment by thebigmunch** [comment]
> With the webclient we don't have to register and manage fake android devices and using Fiddler etc. to snoop traffic is way more easy on the webclient than on an android device.
The only thing you would need a mobile device for is streaming. I don't know if this is still true, but back when the Chrome app first came out, you could use its id for streaming as well. Also, it's rather trivial to set up Fiddler with a mobile device; the Fiddler documentation contains the handful of easy steps to do this.

**Comment by siebert** [comment]
> The mobile client api contains quite a bit that the webclient api doesn't.

Really? What would that be?

> Also, it's rather trivial to set up Fiddler with a mobile device

That's true for iOS, but not for Android in my experience.

**Comment by thebigmunch** [comment]
[This](http://docs.telerik.com/fiddler/configure-fiddler/tasks/ConfigureForAndroid) doesn't cover it? Much of the page is pictures which may get in the way if you're experienced, but it's useful to help even novices set it up.

**Comment by siebert** [comment]
No, that's only for Apps/Browsers which uses the webproxy. Most apps don't do that and I'm pretty sure that includes the Google Play Music app.

Still wondering which functions of the mobile client api are missing in the webclient api...

**Comment by thebigmunch** [comment]
Um, that's the exact method I use to proxy Google Play Music and most apps on my Android phones, so...

**Comment by simon-weber** [comment]
> Most apps don't do that and I'm pretty sure that includes the Google Play Music app.

That's worked fine for me in the past on both physical and virtual devices, but the last time I tried it was a few months ago. Maybe Google started cert pinning in the meantime?

> Still wondering which functions of the mobile client api are missing in the webclient api...

I think @thebigmunch was referring to the current state of things in gmusicapi, not the actual capabilities of Google's apis.

> I would love to see a major rewrite of gmusicapi which only uses the webclient API.

I'd definitely love help fleshing out the webclient! I'm just not likely to recommend it as the primary interface because it's a hassle to maintain (and I don't get paid for working on this! :grin:).

**Comment by siebert** [comment]
See http://stackoverflow.com/questions/24417242/do-android-proxy-settings-apply-to-all-apps-on-the-device

I don't recall whether I ever tried to snoop the Google Play Music app, but serveral other apps I've tried didn't use the proxy setting. So for traffic snooping iOS is best as all apps use the proxy setting and for reverse engineering the source code Android is best as the apk can be decompiled into smali/java :)

There seems to be some workaround against certificate pinning, but I didn't test it:
https://github.com/iSECPartners/Android-SSL-TrustKiller

**Comment by thebigmunch** [comment]
I believe this can be closed as this is a limitation of Google Music, not gmusicapi. The method is documented as only supporting rating. I'll be doing something about the potential confusion surrounding this method soon (see #480). And there's already a test to check for any change in ``change_song_metadata`` functionality in the future.

**Comment by simon-weber** [comment]
Sounds good to me.
