### ISSUE TITLE
artist/album station creation broken

### ISSUE THREAD

**Issue by chrisnorman7** [simon-weber/gmusicapi#335]
I know you closed the one about genre stations, but it seems that artist and album stations don't work either... Not sure if they did before.

There's no error that I can see, just nothing.

Cheers.

**Comment by simon-weber** [comment]
Huh, ok. I think I only test creation of a genre station, haha.

**Comment by thebigmunch** [comment]
Just perusing issues to fix. Happened to be testing station creation earlier, and artist/album station creation seems to work fine for me now. And it looks like all the options are in the tests. Can this be closed?

**Comment by simon-weber** [comment]
Whoops, yup. Not sure how I missed the tests before.
