### ISSUE TITLE
Report played tracks/albums/radios back to server? 

### ISSUE THREAD

**Issue by rolandrohde** [simon-weber/gmusicapi#339]
Hi, 

Would it be possible to report played tracks, Albums and radio stations back to the server? 
Currently, whatever I play/create in the Android app immediately shows up in the Squeezebox Plugin, but whatever I do on the SB stays there which means radio stations, likes and dislikes etc. don't get updater properly for me since I use Google Music All Access almost exclusively  on the Squeezebox, never on mobile devices or browser. 
It would be great if this could be implemented! Currently the genre radio stations and "I'm feeling lucky" tend to repeat tracks a lot... 
The Play Music Plugin already keeps a list of recently played albums, but that must be a local affair because those albums never show up anywhere in the GPM Webinterface or app. 

Thanks!

**Comment by simon-weber** [comment]
Woah, sorry I never responded to this :sweat: 

I think gmusicapi supports this, so maybe it's not implemented in the plugin you're using (presumably https://github.com/hechtus/squeezebox-googlemusic?). If that's the case, you'll want to raise it with them instead.
