### ISSUE TITLE
Mobileclient.login fails with requests SSLError

### ISSUE THREAD

**Issue by chrisnorman7** [simon-weber/gmusicapi#350]
Hi, when using Mobileclient.login I get the following error:
 Traceback (most recent call last):
  File "test.py", line 5, in <module>
    m.login(argv[1], argv[2], m.FROM_MAC_ADDRESS)
  File "c:\python27\lib\site-packages\gmusicapi-7.0.0.dev0-py2.7.egg\gmusicapi\clients\mobileclient.py", line 63, in login
    if not self.session.login(email, password, android_id):
  File "c:\python27\lib\site-packages\gmusicapi-7.0.0.dev0-py2.7.egg\gmusicapi\session.py", line 170, in login
    res = gpsoauth.perform_master_login(email, password, android_id)
  File "c:\python27\lib\site-packages\gpsoauth-0.0.4-py2.7.egg\gpsoauth\__init__.py", line 66, in perform_master_login
    return _perform_auth_request(data)
  File "c:\python27\lib\site-packages\gpsoauth-0.0.4-py2.7.egg\gpsoauth\__init__.py", line 22, in _perform_auth_request
    headers={'User-Agent': useragent})
  File "c:\python27\lib\site-packages\requests\api.py", line 99, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "c:\python27\lib\site-packages\requests\api.py", line 49, in request
    response = session.request(method=method, url=url, **kwargs)
  File "c:\python27\lib\site-packages\requests\sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\python27\lib\site-packages\requests\sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "c:\python27\lib\site-packages\requests\adapters.py", line 431, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: hostname 'android.clients.google.com' doesn't match either of '*.google.com', '*.android.com', '*.appengine.google.com', '*.cloud.google.com', '*.google-analytics.com', '*.google.ca', '*.google.cl', '*.google.co.in', '*.google.co.jp', '*.google.co.uk', '*.google.com.ar', '*.google.com.au', '*.google.com.br', '*.google.com.co', '*.google.com.mx', '*.google.com.tr', '*.google.com.vn', '*.google.de', '*.google.es', '*.google.fr', '*.google.hu', '*.google.it', '*.google.nl', '*.google.pl', '*.google.pt', '*.googleadapis.com', '*.googleapis.cn', '*.googlecommerce.com', '*.googlevideo.com', '*.gstatic.cn', '*.gstatic.com', '*.gvt1.com', '*.gvt2.com', '*.metric.gstatic.com', '*.urchin.com', '*.url.google.com', '*.youtube-nocookie.com', '*.youtube.com', '*.youtubeeducation.com', '*.ytimg.com', 'android.com', 'g.co', 'goo.gl', 'google-analytics.com', 'google.com', 'googlecommerce.com', 'urchin.com', 'youtu.be', 'youtube.com', 'youtubeeducation.com'

I got that by supplying my username and password to the following code:
 from sys import argv

from gmusicapi import Mobileclient as m
m = m()
m.login(argv[1], argv[2], m.FROM_MAC_ADDRESS)

I have yet to try it on another PC (running Windows 7 here), not sure if it fails on Macintosh.
HTH.

**Comment by simon-weber** [comment]
This is also described at https://github.com/simon-weber/gmusicapi/issues/345#issuecomment-113922570.

Can you give me your python version and the output of `pip freeze`? I think you may be missing the extra dependencies you need to verify the certs.

**Comment by chrisnorman7** [comment]
Hi mate,
Here's the readout from the computer where the crashes occur.

Interestingly, my others don't crash. I'll include them too:

python --version
Python 2.7.8 (default, Jun 30 2014, 16:03:49) [MSC v.1500 32 bit 
(Intel)] on win32

pip freeze
accessible-output2==0.12.dev0
appdirs==1.4.0
autoupdate==0.24
beautifulsoup4==4.3.2
certifi==2015.4.28
configobj==5.0.6
confmanager==2.0
decorator==3.4.2
docutils==0.12
facebook-sdk==0.4.0
future==0.14.3
gmusicapi==7.0.0.dev0
gpsoauth==0.0.4
httplib2==0.9.1
Jinja2==2.7.3
libloader==0.1
MarkupSafe==0.23
mechanicalsoup==0.3.1
mock==1.0.1
mutagen==1.29
ndg-httpsclient==0.4.0
oauth2client==1.4.9
platform-utils==0.33
proboscis==1.2.6.0
protobuf==3.0.0a2
py2exe2msi==0.0.2
pyasn1==0.1.7
pyasn1-modules==0.0.5
pycrypto==2.6.1
PyExecJS==1.0.4
pygame==1.9.1
Pygments==2.0.1
PyInstaller==2.1
pyopenssl==0.15.1
pyperclip==1.5.7
python-dateutil==2.4.2
pywin32==219
requests==2.5.0
rsa==3.1.4
six==1.9.0
sound-lib==0.73
Sphinx==1.2.3
Twisted==14.0.2
Unidecode==0.4.18
updatecheck==0.6
validictory==1.0.0
winpaths==0.2
zope.interface==4.1.2

Here's the result of pip freeze (same Python version, possibly 2.7.9) 
from the computer where crashes don't occur. Both are running windows. 
Both Macintosh computers work fine:

amqp==1.4.6
anyjson==0.3.3
app-reloader==0.12
appdirs==1.4.0
argh==0.25.0
beautifulsoup4==4.3.2
billiard==3.3.0.19
byteplay==0.2
celery==3.1.17
certifi==2015.4.28
cffi==0.9.2
configobj==5.0.6
confmanager==2.2
console==0.1.1
CorePost==0.0.16
crypto==1.3.4
cryptography==0.8.1
decorator==3.4.2
Django==1.7.4
docutils==0.12
dropbox==2.2.0
enum34==1.0.4
flufl.enum==4.0.1
FormEncode==1.3.0
future==0.14.3
fuzzywuzzy==0.4.0
game-utils==0.11
gmusicapi==7.0.0.dev0
google==1.5
gpsoauth==0.0.4
html==1.16
httplib2==0.9.1
inflect==0.2.5
Jinja2==2.7.3
keyboard-handler==0.52
keyring==4.0
kombu==3.0.24
libloader==0.1
lupa==1.0b1
mailer==0.7
Markdown==2.5.2
MarkupSafe==0.23
mechanicalsoup==0.3.1
midi==0.2.3
mock==1.0.1
mutagen==1.29
mygui==1.0
Naked==0.1.31
ndg-httpsclient==0.4.0
netifaces==0.10.4
oauth2==1.5.211
oauth2client==1.4.11
parsedatetime==1.4
pathtools==0.1.2
Pint==0.5.2
pkginfo==1.2.1
platform-utils==0.33
proboscis==1.2.6.0
protobuf==2.6.1
psutil==2.2.0
py2exe==0.6.9
pyasn1==0.1.7
pyasn1-modules==0.0.5
PyAudio==0.2.8
pybass==0.55.0
pycparser==2.10
pycrypto==2.6.1
PyExecJS==1.0.4
pygame==1.9.2a0
Pygments==2.0.2
pygoogle==0.6
-e 
git://github.com/pyinstaller/pyinstaller.git@6f84a5ac1a511c192379197aab7dc8756c05caec#egg=PyInstaller-develop
pyopenssl==0.15.1
pyparsing==2.0.3
pyperclip==1.5.7
python-dateutil==2.4.2
python-magic==0.4.6
python-sql==0.4
pytz==2014.10
pywin32==219
pyyaml==3.11
requests==2.7.0
rsa==3.1.4
simple-pbkdf2==1.0
six==1.9.0
sound-lib==0.73
Sphinx==1.2.3
spotipy==2.3.6
SQLAlchemy==0.9.9
telnetsrv==0.4
tweepy==2.3.0
twine==1.4.0
Twisted==15.0.0
Unidecode==0.4.18
updatecheck==0.6
urllib3==1.10
validictory==1.0.0
watchdog==0.8.1
wheel==0.24.0
winpaths==0.2
yoyo-migrations==4.2.4
zope.interface==4.1.2

**Comment by ratherDashing** [comment]
Same error here:

/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Traceback (most recent call last):
  File "/opt/gmusicapi-scripts/gmupload.py", line 94, in <module>
    main()
  File "/opt/gmusicapi-scripts/gmupload.py", line 53, in main
    mmw.login(oauth_file=cli['cred'], uploader_id=cli['uploader-id'])
  File "/opt/gmusicapi-scripts/gmwrapper.py", line 366, in login
    if not self.api.login(oauth_credentials=oauth_cred, uploader_id=uploader_id):
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/clients/musicmanager.py", line 160, in login
    self._perform_upauth(uploader_id, uploader_name))
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/clients/musicmanager.py", line 219, in _perform_upauth
    uploader_name)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/clients/shared.py", line 80, in _make_call
    return protocol.perform(self.session, self.validate, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/protocol/shared.py", line 208, in perform
    response = session.send(req_kwargs, cls.required_auth)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/session.py", line 86, in send
    res = self._send_with_auth(req_kwargs, desired_auth, rsession)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/session.py", line 231, in _send_with_auth
    return rsession.request(**req_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: hostname 'android.clients.google.com' doesn't match either of '*.google.com', '*.android.com', '*.appengine.google.com', '*.cloud.google.com', '*.google-analytics.com', '*.google.ca', '*.google.cl', '*.google.co.in', '*.google.co.jp', '*.google.co.uk', '*.google.com.ar', '*.google.com.au', '*.google.com.br', '*.google.com.co', '*.google.com.mx', '*.google.com.tr', '*.google.com.vn', '*.google.de', '*.google.es', '*.google.fr', '*.google.hu', '*.google.it', '*.google.nl', '*.google.pl', '*.google.pt', '*.googleadapis.com', '*.googleapis.cn', '*.googlecommerce.com', '*.googlevideo.com', '*.gstatic.cn', '*.gstatic.com', '*.gvt1.com', '*.gvt2.com', '*.metric.gstatic.com', '*.urchin.com', '*.url.google.com', '*.youtube-nocookie.com', '*.youtube.com', '*.youtubeeducation.com', '*.ytimg.com', 'android.com', 'g.co', 'goo.gl', 'google-analytics.com', 'google.com', 'googlecommerce.com', 'urchin.com', 'youtu.be', 'youtube.com', 'youtubeeducation.com'

Ubuntu 14.04, all packages up to date on Ubuntu and all packages up to date on pip.

I would run pip freeze but I get this:


Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/freeze.py", line 74, in run
    req = pip.FrozenRequirement.from_dist(dist, dependency_links, find_tags=find_tags)
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 286, in from_dist
    assert len(specs) == 1 and specs[0][0] == '=='
AssertionError

so who knows.

**Comment by simon-weber** [comment]
Hm. @ratherDashing, maybe try creating a new virtual environment and installing there instead?

**Comment by ratherDashing** [comment]
I fixed this on Ubuntu 14.04 with the following:

    remove ubuntu package: sudo apt-get remove --auto-remove python-pip

    download official pip installer: wget https://bootstrap.pypa.io/get-pip.py

    install pip by running downloaded installer: sudo python get-pip.py

    add sym-link to make it run without full path: sudo ln -s /usr/local/bin/pip /usr/bin/pip

**Comment by simon-weber** [comment]
It looks like this was an environment problem? Feel free to reopen if not.
