### ISSUE TITLE
the response format for Search was not recognized

### ISSUE THREAD

**Issue by maemigh** [simon-weber/gmusicapi#351]
pip search gmusicapi
gmusicapi                 - An unofficial api for Google Play Music.
  INSTALLED: 7.0.0.dev0

Value {u'station': {u'kind': u'sj#radioStation', u'seed': {u'trackId': u'Tmw7toyudf7wogw4ydzrilbghhu', u'kind': u'sj#radioSeed', u'seedType': u'2'}, u'imageUrls': [{u'url': u'http://lh6.ggpht.com/VQz_rC34E5mG6IuqubufVocSyAbG6nX4zcoEBysnJYnE6U6qIlKWxcFdo2gNlAdJqZIlW1vf'}], u'name': u'Symphony No. 41 in C Major, K. 551, "Jupiter": II. Andante cantabile'}, u'type': u'6'} for field '<obj>.entries[54]' contains additional property 'station' not defined by 'properties' or 'patternProperties' and additionalProperties  is False

First, try the develop branch. If you can recreate this error with the most recent code please [create an issue](http://goo.gl/qbAW8) that includes the above ValidationException and the following request/response:
{'url': 'https://mclients.googleapis.com/sj/v1.11/query', 'headers': {'Authorization': '<omitted>'}, 'params': {'q': u'ambient sleep classics', 'max-results': 50}, 'method': 'GET'}

'{\n "kind": "sj#searchresponse",\n "entries": [\n  {\n   "type": "3",\n   "album": {\n    "kind": "sj#album",\n    "name": "Ambient Sleep Classics",\n    "albumArtist": "Various Artists",\n    "albumArtRef": "http://lh6.ggpht.com/VQz_rC34E5mG6IuqubufVocSyAbG6nX4zcoEBysnJYnE6U6qIlKWxcFdo2gNlAdJqZIlW1vf",\n    "albumId": "Bjardktjh62inpx4agbn7iaqeoi",\n    "artist": "Various Artists",\n    "artistId": [\n     ""\n    ],\n    "year": 2014\n   },\n   "score": 123.99147033691406\n  },\n  {\n   "type": "3",\n   "album": {\n    "kind": "sj#album",\n    "name": "Land of Sweet Dreams \xe2\x80\x93 Relaxing Mind Music for Good Night, Classical Music for Healing Sleeping, Sweet Dreams with Classics, Deep Sleep Music, Time for Bed",\n    "albumArtist": "Sweet Dreams Music Ambient",\n    "albumArtRef": "http://lh6.ggpht.com/q6jilN3V6Sx4YNT1slgQrQrm1fcEnmvh_nxMjc0AXKcJyjORGjR_MvInW2LoWioqW-yIcXa0Fg",\n    "albumId": "Bbdvxoyohk4gvufxisftpqapdfy",\n    "artist": "Sweet Dreams Music Ambient",\n    "artistId": [\n     "A5wohjiitzfqphhe4f6lu...'

A traceback follows:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/protocol/shared.py", line 248, in perform
    cls.validate(response, parsed_response)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/protocol/mobileclient.py", line 263, in validate
    return validictory.validate(msg, cls._res_schema)
  File "/usr/local/lib/python2.7/dist-packages/validictory/__init__.py", line 36, in validate
    return v.validate(data, schema)
  File "/usr/local/lib/python2.7/dist-packages/validictory/validator.py", line 543, in validate
    self.__validate("data", {"data": data}, schema, '<obj>')
  File "/usr/local/lib/python2.7/dist-packages/validictory/validator.py", line 566, in __validate
    validator(data, fieldname, schema, path, newschema.get(schemaprop))
  File "/usr/local/lib/python2.7/dist-packages/validictory/validator.py", line 244, in validate_properties
    path + '.' + eachProp)
  File "/usr/local/lib/python2.7/dist-packages/validictory/validator.py", line 566, in __validate
    validator(data, fieldname, schema, path, newschema.get(schemaprop))
  File "/usr/local/lib/python2.7/dist-packages/validictory/validator.py", line 275, in validate_items
    '{}[{}]'.format(path, index))
  File "/usr/local/lib/python2.7/dist-packages/validictory/validator.py", line 566, in __validate
    validator(data, fieldname, schema, path, newschema.get(schemaprop))
  File "/usr/local/lib/python2.7/dist-packages/validictory/validator.py", line 353, in validate_additionalProperties
    " is False", value, fieldname, prop=eachProperty, path=path)
  File "/usr/local/lib/python2.7/dist-packages/validictory/validator.py", line 176, in _error
    raise err
ValidationException: Value {u'station': {u'kind': u'sj#radioStation', u'seed': {u'trackId': u'Tmw7toyudf7wogw4ydzrilbghhu', u'kind': u'sj#radioSeed', u'seedType': u'2'}, u'imageUrls': [{u'url': u'http://lh6.ggpht.com/VQz_rC34E5mG6IuqubufVocSyAbG6nX4zcoEBysnJYnE6U6qIlKWxcFdo2gNlAdJqZIlW1vf'}], u'name': u'Symphony No. 41 in C Major, K. 551, "Jupiter": II. Andante cantabile'}, u'type': u'6'} for field '<obj>.entries[54]' contains additional property 'station' not defined by 'properties' or 'patternProperties' and additionalProperties  is False

**Comment by simon-weber** [comment]
Thanks for reporting! It's neat that searches can return stations now.
