### ISSUE TITLE
Webclient.login failure on 7.0.0

### ISSUE THREAD

**Issue by porkhelmet** [simon-weber/gmusicapi#352]
First a quick "thank you" to all the work on gmusicapi!  I've been using the Webclient to upload album art in a nightly Cron for about a week on version 5.0.0 with success.  Nice!  Unfortunately, Webclient logins mysteriously started failing last night, I didn't change the scripts.  I upgraded gmusicapi to version 7.0.0 but still cannot authenticate with an app password and Webclient.  I tried using just a password and received a 2-factor text from Google so it looks like at least an attempt was made to login.  Also, Mobileclient logins work just fine.  I've read through the open issues but it doesn't seem like anyone else has reported this.  Any thoughts?  Output from my attempts:

python
Python 2.7.9 (default, Apr 22 2015, 03:25:20)
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
from gmusicapi import Webclient
webclient = Webclient(True,True,True)
webclient.login('EMAIL','APP_PASSWORD')
False

from gmusicapi import Mobileclient
mobileclient = Mobileclient()
mobileclient.login('EMAIL','APP_PASSWORD',Mobileclient.FROM_MAC_ADDRESS )
True

**Comment by simon-weber** [comment]
> Webclient logins mysteriously started failing last night

Ah, sounds like the clientlogin shutdown reached your account.

> I upgraded gmusicapi to version 7.0.0 but still cannot authenticate with an app password and Webclient

This is expected - app passwords were a stopgap because clientlogin didn't support 2fa - though I didn't consider unattended use cases like yours on the webclient.

> Mobileclient logins work just fine

That surprises me: I would have expected you to run into 2fa there as well. Support for that is finally possible, but the client code isn't written yet (see https://github.com/simon-weber/gmusicapi/issues/168#issuecomment-102210526 for details).

Unfortunately, I don't think there's a way around disabling 2fa if you need this script to keep running; sorry :disappointed:

**Comment by porkhelmet** [comment]
Oh no!  That is unfortunate news.  Is there any hope of a fix in the future?  In my use case I am syncing local music automatically with Google Music as new songs are added.  Since cross platform support from Google is lacking, gmusicapi is the only option for small devices such as home NAS.

**Comment by simon-weber** [comment]
Here's the lay of the land wrt unattended use cases when 2fa is enabled:
* webclient: won't work (unless you set up a TOTP provider on the machine).
* mobileclient: could work, but would require changes.
* iosclient: would work, but it's not written yet.
* musicmanager: works currently.

**Comment by porkhelmet** [comment]
Thanks again Simon!  Thinking big pitcure, musicmanager does everything I need *except* for uploading album art, which is why I'm using Webclient in the first place.  I'm too much of a novice to add much in the effort to provide unattended 2fa logins, but here is some code I wrote to find both embedded and external album art.  Maybe this will prove valuable in a future gmusicapi release?  I hate to ask for things without giving something first :)

Note, based on #242 =s130-c-e100 needs to be stripped from the end of the URL before uploading, otherwise the Google Mobile client will not display images.

Example of code to find and save the location of external album art:

import os

folder_images = {}

if os.path.isdir(path):
	for dirpath, dirnames, filenames in os.walk(path):
		for filename in filenames:

			# if the file is a folder image remember the location
			if filename.lower() == folder.jpg:
				folder_images[os.path.join(dirpath, '')] = filename

Example of code to extract embedded jpeg art from mp3

import os
import logging
import mutagen

def save_embedded_art(filepath):
        try:
                # Scan the file for all metadata
                audio = mutagen.File(filepath)
        except:
                logger.warning("ERROR scanning for embedded art -- {}".format(filepath))
                return False
        else:
                # Check metadata for cover art
                for k in audio.keys():
                        if u'covr' in k:
                                return _extract_embedded_art(audio,filepath,k)
                        if u'APIC' in k:
                                return _extract_embedded_art(audio,filepath,k)
        # Return false if something goes awry
        return False

def _extract_embedded_art(audio,filepath,tag):
        # Get the mime type for the album art
        mime_type = audio.tags[tag].mime

        # Make the mime type lowercase and check for jpeg image
        if mime_type.lower() == "image/jpeg" or "image/jpg":

                # If jpeg found get the image data and write to disk
                artwork = audio.tags[tag].data
                try:
                        with open('/tmp/cover/image.jpg', 'wb') as img:
                                img.write(artwork)
                except IOError:
                        logger.warning("ERROR writing embedded art to disk -- {}".format(filepath))
                        return False
                else:
                        return True
        else:
                logger.warning("ERROR embedded art not jpeg format -- {}".format(filepath))
                return False
        # Return false if something goes awry
        return False

**Comment by simon-weber** [comment]
> here is some code I wrote to find both embedded and external album art

Great, thanks! :+1: 

> musicmanager does everything I need except for uploading album art

The music manager api is capable of this; it's just not implemented (https://github.com/simon-weber/gmusicapi/issues/242#issuecomment-41757580). Hopefully it's not too hard to implement now that you've written part of it =)

**Comment by simon-weber** [comment]
Let's track the art uploading in https://github.com/simon-weber/gmusicapi/issues/242.
