### ISSUE TITLE
Don't install tests / Split test dependencies

### ISSUE THREAD

**Issue by mrueg** [simon-weber/gmusicapi#354]
Hi,

I'm trying to use gmusicapi with mopidy-gmusic (a plugin for mopidy). 
Mopidy checks the plugins' transitive dependencies during start up, otherwise stops loading the plugin.
As gmusicapi currently seems to install the test directory, it checks for the test dependencies, too. 
Usually one would not require them to be installed. 
Could you exclude the test directory in setup.py and split the dependencies into install_requires and tests_require?

**Comment by simon-weber** [comment]
Yeah, I'd like to do this. This was intentional - when gmusicapi was young, I often needed users to run the test suite to help with debugging - but isn't needed anymore.
