### ISSUE TITLE
webclient login fails with "need to enable less secure logins"

### ISSUE THREAD

**Issue by Frisch12** [simon-weber/gmusicapi#356]
Login failed with "strange login response" error.

```
2015-07-17 15:19:01,299 - gmusicapi.Webclient1 (shared:405) [WARNING]: Received strange login response: {}

You may need to enable less secure logins:
  https://www.google.com/settings/security/lesssecureapps
```

I've already tried to deactivate second factor authentication and enable less secure apps support.

**Comment by caymard** [comment]
Same here. I tried an application-specific password but no changes.

**Comment by Frisch12** [comment]
Ah i've found the issue. 
Check the API-Documentation. The Mobileclient login method needs an additional parameter. Pass Mobileclient.FROM_MAC_ADDRESS into the method as third parameter. 
The get_registered_devices method does not work anymore

**Comment by caymard** [comment]
Ah nice thanks ! So working with `Mobileclient` is an obligation ? `Webclient` is unable with the application-specific password ?

**Comment by Frisch12** [comment]
I use Mobileclient because it can access the "all access" library and songs. 
I've written a simple script wich maybe shows you how it works: https://gist.github.com/Frisch12/55e80fa7423f762fb06c

**Comment by simon-weber** [comment]
@Frisch12 @caymard were you both using the webclient on the most recent version of gmusicapi? I had expected that switching away from clientlogin would prevent the message you were seeing.

**Comment by caymard** [comment]
@simon-weber I had the most recent version yep

**Comment by FischerLouis** [comment]
Hey guys,

Any update on that issue?
I am also unable to use Webclient.login(email, password).
I got the same error as @Frisch12.

This is what I tried so far for login:
 - Regular authentication,
 - Regular authentication with "less secure apps" feature activated,
 - 2 factor authentication activated with a specific app password.

I would like to use Webclient.upload_album_art.
Any ideas?

Thanks for your awesome work on gmusicapi.

**Comment by simon-weber** [comment]
Are you sure you're using the most recent unreleased code (from the `develop` branch)? I think this is the "fix webclient authentication" I mentioned in https://github.com/simon-weber/gmusicapi/blob/develop/HISTORY.rst.

**Comment by Frisch12** [comment]
Currents it works for me well with this gist: https://gist.github.com/Frisch12/55e80fa7423f762fb06c

**Comment by FischerLouis** [comment]
Thank you for your quick feedbacks.

I was quite sure I updated my packages but after double checking it, I realized I was indeed still in version 6.0.0.
The login through the Webclient is now successful.

Thanks again for your help!

**Comment by simon-weber** [comment]
Ah, good to hear!
