### ISSUE TITLE
using add_songs_to_playlist with nid from list get_promoted_songs fails

### ISSUE THREAD

**Issue by bsdz** [simon-weber/gmusicapi#358]
When trying to add songs returned from get_promoted_songs to another playlist using add_songs_to_playlist, a playlist entry_id is returned but the song does not appear on the playlist.

One can reproduce the issue by editing the example.py in the following way.

```
library = api.get_promoted_songs()
```

and

```
song_id = first_song['nid']
```

When one then runs the example and inspects the playlist online, it will be empty.

**Comment by simon-weber** [comment]
Huh. Off the top of my head I've got not idea what could be causing that. Thanks for reporting it!

**Comment by nocola** [comment]
Hi all. I just add "T" to head of nid (if !(startWith("T"))), and stream was successfully  got ))

**Comment by bsdz** [comment]
Actually, it seems latest master resolves this issue. Thanks.
