### ISSUE TITLE
WebClient.GetSettings() gives http error 404

### ISSUE THREAD

**Issue by bubbleguuum** [simon-weber/gmusicapi#361]
As the title says. It seems to be new and since a day or two.

**Comment by theli-ua** [comment]
yeah url now is different  its fetchsettings instead of loadsettings , and the return format is a bit different as well

**Comment by theli-ua** [comment]
Also, for anyone who wants to fix this. deviceType now is 2 for android, 3 for ios

**Comment by mrmaffen** [comment]
You may want to take a look at this commit by theli-ua https://github.com/tomahawk-player/tomahawk-resolvers/commit/4cd61449b2941df06116428bf4b5bb3347a1197d (ignore the "_token" changes)

**Comment by simon-weber** [comment]
Thanks for the heads up; I'll take a look this weekend.
