### ISSUE TITLE
Issue in Podcast lecture

### ISSUE THREAD

**Issue by vmurillo** [simon-weber/gmusicapi#362]
This issue seems very alike to this:

https://github.com/simon-weber/gmusicapi/issues/286

Whenever I trye to play a podcast, after a small period of time I got this console error:

[00007f3940c09938] core access error: read error: Connection reset by peer

I am using VLC 2.2.1buildd@lgw01-37.buildd Jul 20 2015 23:42:41 under Ubuntu 14.04

Regards.

**Comment by simon-weber** [comment]
Yeah, that does sound like the same issue. Since there's more context in #286, let's move the discussion over there and reopen it.
