### ISSUE TITLE
Getting tracks for unknown stations raises KeyError

### ISSUE THREAD

**Issue by jodal** [simon-weber/gmusicapi#365]
The docs for `Mobileclient.get_station_tracks()` indicates that there's a "I'm Feeling Lucky" station with the special ID "IFL". This doesn't work for me, and should maybe be removed from the docstring.

It might be it's because my GPM account is a day old and don't have much data about what I like to listen too? If so, this still needs better error handling in the case the station doesn't exist for the current user. Would be nice if someone could try to reproduce this with an older GPM account.

``` python
>>> import gmusicapi
>>> api = gmusicapi.Mobileclient(validate=False)
>>> api.login('alice@example.com', 'secret', gmusicapi.Mobileclient.FROM_MAC_ADDRESS)
True
>>> api.get_station_tracks('IFL')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jodal/dev/virtualenvs/mopidy/local/lib/python2.7/site-packages/gmusicapi/clients/mobileclient.py", line 787, in get_station_tracks
    station_id, num_tracks, recently_played=recently_played)
  File "/home/jodal/dev/virtualenvs/mopidy/local/lib/python2.7/site-packages/gmusicapi/clients/shared.py", line 80, in _make_call
    return protocol.perform(self.session, self.validate, *args, **kwargs)
  File "/home/jodal/dev/virtualenvs/mopidy/local/lib/python2.7/site-packages/gmusicapi/protocol/shared.py", line 242, in perform
    log.debug(cls.filter_response(parsed_response))
  File "/home/jodal/dev/virtualenvs/mopidy/local/lib/python2.7/site-packages/gmusicapi/protocol/mobileclient.py", line 815, in filter_response
    if 'stations' in filtered['data']:
KeyError: 'data'
>>> 
```

**Comment by thebigmunch** [comment]
It works for me, as in it doesn't give an error, though the case of it not existing should be handled. However, it doesn't seem to work as on the WebUI or Mobile app. It simply seems to return a song in my library instead.

**Comment by simon-weber** [comment]
Maybe they changed the response from the station tracks to a station seed track?

**Comment by thebigmunch** [comment]
The response looks like it contains the station tracks from my testing with the Android app and Fiddler.

**Comment by jodal** [comment]
After having used Google Play Music a bit more, the IFL station now works for me too. Thus I think the issue here is simply to handle non-existent stations a bit nicer.

To reproduce the error, just use any random station ID, like `foo`.

**Comment by simon-weber** [comment]
Overloading the return value of `[]` isn't ideal but was an easy fix.
