### ISSUE TITLE
Unable to log in

### ISSUE THREAD

**Issue by marcuspen** [simon-weber/gmusicapi#373]
The gmusicapi has been working for me fine up until today. Based on my debugging, it seems Google may have restricted how we can log in. 

So I've been using the Mobileclient to login with simply:
```
from gmusicapi import Mobileclient
api = Mobileclient()
api.login(email, password, Mobileclient.FROM_MAC_ADDRESS)
```

That now returns `False`.
After some debugging, it seems that when I get to line 170 in session.py:
```
res = gpsoauth.perform_master_login(email, password, android_id)
```
It now returns the following error in the dict:
```
u'ErrorDetail': u'To access your account, you must sign in on the web. Touch Next to start browser sign-in.', u'Error': u'NeedsBrowser'
```

Anyone else had this? Or maybe I've just forgotten to do something...

**Comment by simon-weber** [comment]
I've never seen this before. Auth seems ok for me right now.

Maybe they're doing some kind of step-up for suspicious logins? Or they're rolling out an auth change that my accounts haven't received yet?

**Comment by marcuspen** [comment]
I hope not!

**Comment by timgws** [comment]
@marcuspen I just experienced this myself. Turning on 2 Step Authentication and creating an Application Specific Password solved this for me.

**Comment by marcuspen** [comment]
Cheers @timgws . That seemed to work. We should probably add this to the readme / documentation. I don't mind adding this and making a PR?

**Comment by simon-weber** [comment]
@marcuspen that'd be great. https://github.com/simon-weber/gmusicapi/blob/971f948bdc8f8f8e943933357815b90a303bdff1/gmusicapi/clients/mobileclient.py#L30 would be a good spot for it.

**Comment by pejobo** [comment]
@timgws I've got 2 step auth enabled but cannot login with an application specific password, google shows a dash on https://security.google.com/settings/security/apppasswords  in the column "last usage".
My test code:
````
     >>> from gmusicapi import Mobileclient
     >>> api = Mobileclient()
     >>> print api.login(u, p)
     False
````

debug log:
````
version: 4.0.0
logging to: /home/xxx/.cache/gmusicapi/log/gmusicapi.log
2015-10-31 15:17:19,590 - gmusicapi.Mobileclient1 (shared:70) [INFO]: initialized
2015-10-31 15:17:19,596 - gmusicapi.Mobileclient1 (shared:93) [INFO]: logged out
2015-10-31 15:19:27,971 - gmusicapi.Mobileclient1 (shared:204) [DEBUG]: ClientLogin(<omitted>)
````

**Comment by simon-weber** [comment]
@pejobo it looks like you're on an old version. Upgrading to 7.0.0 should it :+1:

**Comment by pejobo** [comment]
Hmm, my package manager says I'm on 7.0.0:
````
$ yaourt -Ss python2-gmusicapi
aur/python2-gmusicapi 7.0.0-1 [installed] (2)
    Allows control of Google Music with Python
````
Are there better means to see the version number?

**Comment by simon-weber** [comment]
Hm, the log is definitely from 4.0.0. Maybe you're referencing an old system-wide install when running the script?

You can try printing `gmusicapi.__file__` or `gmusicapi.__version__` in your script to narrow down which version you're running from.

**Comment by pejobo** [comment]
Thanks for the hint, didn't pay attention to the log. Found the old version is in .local/lib. Thanks for your help, shame on me.

**Comment by simon-weber** [comment]
No worries! The only reason I know to look is because I've made the same mistake a million times :grin:

**Comment by timgws** [comment]
@pejobo I assume you were able to log in using the Application Specific Password after removing the older installed version of gmusicapi?

**Comment by pejobo** [comment]
@timgws yes the login was successful (returned "True") and the google page showed me that the given app password has been used.

**Comment by simon-weber** [comment]
Whoops, forgot to close this one.

**Comment by Jhilam2014** [comment]
from gmusicapi import Mobileclient
>>> api = Mobileclient()
>>> api.login("<emailid>", "<Password>",Mobileclient.FROM_MAC_ADDRESS)
False
>>>
