### ISSUE TITLE
adding tracks to library

### ISSUE THREAD

**Issue by dcalacci** [simon-weber/gmusicapi#376]
This is a feature request to be able to add a list of track IDs to a users' library, rather than a just a playlist.

I'm new to this project but may try to work on this if I can muster the time. 

The current post endpoint is at: `/addsongstolocker`.

Examining the post request when a user adds a track to the library, this is what I can determine about the data being sent:

```
[[0, 2, 0] <--- I don't know what this means, I assume it's a code of some sort for the client status?
[null, 
 [[<uuid1>, <track ID>], ...]
]
```

I don't know what uuid1 is, though. After some testing, it seems to be a track identifier that resets between sessions. Not sure if this is seen in other bits of the API. 

Looks pretty easy to implement if the other bits of data are deciphered, which you guys might have a better idea about. Any tips?

**Comment by simon-weber** [comment]
It looks like you're referring to the webclient endpoint. Would it be ok to use the [mobileclient endpoint](https://unofficial-google-music-api.readthedocs.org/en/develop/reference/mobileclient.html#gmusicapi.clients.Mobileclient.add_aa_track) instead?

We generally don't do any more development on the webclient because of the nasty data format you mentioned :grin:

**Comment by dcalacci** [comment]
ah, yeah, totally. I'll do some sniffing when I get home and see if I can decipher the data format, unless you have tips for spoofing mobile to look at the data format?

**Comment by simon-weber** [comment]
Oh, I meant that I thought this was already supported, but through the mobileclient (not the webclient).

**Comment by dcalacci** [comment]
oh, man, totally missed that method. sick! will make importing my rdio library much easier. this should be closed.

**Comment by simon-weber** [comment]
Haha, no problem, just wanted to make sure I understood (technically, it doesn't support a _list_ of songs). Chalk it up to poorly-organized docs.

**Comment by dcalacci** [comment]
just a little tip -- I think one of the reasons why I missed it at first glance is because it references "all access", which afaik is no longer part of google music, so I may have passed it off as deprecated even though it is not

**Comment by simon-weber** [comment]
Wow, I didn't know they got rid of that branding, haha. I'll have to look into this at some point.

**Comment by madx** [comment]
Just found that issue, will help to import my rdio collection as well!

@dcalacci did you come up with some script to do it?

**Comment by madx** [comment]
Nevermind, I wrote one :)

https://gist.github.com/madx/b0a09ae013c628fe22b8f255f6b66fb4
