### ISSUE TITLE
remove_entries_from_playlist doesn't work

### ISSUE THREAD

**Issue by chrisnorman7** [simon-weber/gmusicapi#378]
Hi,
I'm trying to use remove_entries_from_playlist with the Mobileclient with no success. I've tried passing the function every ID field I can find, and no show.

Cheers.

**Comment by thebigmunch** [comment]
You didn't specify which ID fields you tried, which is usually a better idea than saying everyone you could find.

Mobileclient.get_all_user_playlist_contents() returns all your playlists. In each playlist is a tracks key. Each entry in there has an id key. That's the entry_id you need.

**Comment by chrisnorman7** [comment]
OK,
Guess I deserved the jibe... I was using get_shared_playlist_contents or 
whatever it's called. Your method worked.

Thanks,

**Comment by simon-weber** [comment]
Haha, no worries. Just means the docs should be improved.
