### ISSUE TITLE
[feature request] add track lastPlayed timestamp

### ISSUE THREAD

**Issue by xlorepdarkhelm** [simon-weber/gmusicapi#379]
Is it possible to make the track data from get_all_songs include the lastPlayed timestamp? I am currently building an automatic playlist manager for my google play songs, and I tend to rely on that field when building my playlists. Thanks.

Not 100% certain the field actually exists. Yes, I do see the lastModifiedTimestamp field you already expose, and if necessary, I can potentially use that one.

**Comment by simon-weber** [comment]
Sorry, we already provide everything we're given from Google. The lastModifiedTimestamp might be what you want; I'm not sure. They do probably track timestamps somewhere since the client provides it [here](https://github.com/simon-weber/gmusicapi/blob/b35dd3ad4414b2950996cc2ca4016bd6d7e5fcfd/gmusicapi/protocol/mobileclient.py#L1057).

**Comment by xlorepdarkhelm** [comment]
Ok, no problem. I can work with lastModifiedTimestamp, it isn't 100% what I am looking for, but it can serve my purposes. Curious, do you know what the recentTimestamp is? Is there anywhere that explains what the various fields mean? I figured out that the timestamps must be [converted to a number and] divided by 1,000,000 in order to use with datetime.datetime.fromtimestamp().

**Comment by simon-weber** [comment]
> Is there anywhere that explains what the various fields mean?

Not really =( There are a few comments in the docstrings alongside the examples, but nothing more structured that that.

**Comment by MrGreenTea** [comment]
@simon-weber Is this stillt not possible? I saw that in your chrome extension you have these now:


https://github.com/simon-weber/Autoplaylists-for-Google-Music/commit/687cb26185bc7e5167d840a181d7b6d516249ec0
https://github.com/simon-weber/Autoplaylists-for-Google-Music/commit/5e1b9808c14c85106e985949a3830b658f78ad2f

Would it be possible to include them here too?

**Comment by simon-weber** [comment]
Yeah, Google still doesn't provide it to the mobile apis. The chrome extension is using a much wonkier set of web apis (since it doesn't need to worry about auth in the same way).
