### ISSUE TITLE
CentOS support

### ISSUE THREAD

**Issue by cecaceres** [simon-weber/gmusicapi#387]
Hi,
I'm really interested in this project, but it doesn't work on CentOS.
Everything is installed but when I'm trying to execute I got some errors.

[claudio@~]$ sudo pip install https://github.com/simon-weber/Unofficial-Google-Music-API/tarball/develop
Collecting https://github.com/simon-weber/Unofficial-Google-Music-API/tarball/develop
  Downloading https://github.com/simon-weber/Unofficial-Google-Music-API/tarball/develop
     - 151kB 1.6MB/s
Requirement already satisfied (use --upgrade to upgrade): validictory!=0.9.2,>=0.8.0 in /usr/lib/python2.6/site-packages (from gmusicapi==7.0.1.dev0)
Requirement already satisfied (use --upgrade to upgrade): decorator>=3.3.1 in /usr/lib/python2.6/site-packages (from gmusicapi==7.0.1.dev0)
Requirement already satisfied (use --upgrade to upgrade): mutagen>=1.18 in /usr/lib/python2.6/site-packages (from gmusicapi==7.0.1.dev0)
Requirement already satisfied (use --upgrade to upgrade): protobuf>=2.4.1 in /usr/lib/python2.6/site-packages (from gmusicapi==7.0.1.dev0)
Requirement already satisfied (use --upgrade to upgrade): requests!=1.2.0,!=2.2.1,<2.8.0,>=1.1.0 in /usr/lib/python2.6/site-packages (from gmusicapi==7.0.1.dev0)
Requirement already satisfied (use --upgrade to upgrade): python-dateutil!=2.0,>=1.3 in /usr/lib/python2.6/site-packages (from gmusicapi==7.0.1.dev0)
Requirement already satisfied (use --upgrade to upgrade): proboscis>=1.2.5.1 in /usr/lib/python2.6/site-packages (from gmusicapi==7.0.1.dev0)
Requirement already satisfied (use --upgrade to upgrade): oauth2client>=1.1 in /usr/lib/python2.6/site-packages (from gmusicapi==7.0.1.dev0)
Requirement already satisfied (use --upgrade to upgrade): mock>=0.7.0 in /usr/lib/python2.6/site-packages (from gmusicapi==7.0.1.dev0)
Requirement already satisfied (use --upgrade to upgrade): appdirs>=1.1.0 in /usr/lib/python2.6/site-packages (from gmusicapi==7.0.1.dev0)
Requirement already satisfied (use --upgrade to upgrade): gpsoauth==0.0.5 in /usr/lib/python2.6/site-packages (from gmusicapi==7.0.1.dev0)
Requirement already satisfied (use --upgrade to upgrade): MechanicalSoup in /usr/lib/python2.6/site-packages (from gmusicapi==7.0.1.dev0)
Requirement already satisfied (use --upgrade to upgrade): pyopenssl in /usr/lib64/python2.6/site-packages (from gmusicapi==7.0.1.dev0)
Requirement already satisfied (use --upgrade to upgrade): ndg-httpsclient in /usr/lib/python2.6/site-packages (from gmusicapi==7.0.1.dev0)
Requirement already satisfied (use --upgrade to upgrade): pyasn1 in /usr/lib/python2.6/site-packages (from gmusicapi==7.0.1.dev0)
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/lib/python2.6/site-packages (from protobuf>=2.4.1->gmusicapi==7.0.1.dev0)
Requirement already satisfied (use --upgrade to upgrade): six>=1.5 in /usr/lib/python2.6/site-packages (from python-dateutil!=2.0,>=1.3->gmusicapi==7.0.1.dev0)
Requirement already satisfied (use --upgrade to upgrade): httplib2>=0.9.1 in /usr/lib/python2.6/site-packages (from oauth2client>=1.1->gmusicapi==7.0.1.dev0)
Requirement already satisfied (use --upgrade to upgrade): pyasn1-modules>=0.0.5 in /usr/lib/python2.6/site-packages (from oauth2client>=1.1->gmusicapi==7.0.1.dev0)
Requirement already satisfied (use --upgrade to upgrade): rsa>=3.1.4 in /usr/lib/python2.6/site-packages (from oauth2client>=1.1->gmusicapi==7.0.1.dev0)
Requirement already satisfied (use --upgrade to upgrade): funcsigs in /usr/lib/python2.6/site-packages (from mock>=0.7.0->gmusicapi==7.0.1.dev0)
Requirement already satisfied (use --upgrade to upgrade): pbr>=0.11 in /usr/lib/python2.6/site-packages (from mock>=0.7.0->gmusicapi==7.0.1.dev0)
Requirement already satisfied (use --upgrade to upgrade): pycrypto>=2.5 in /usr/lib64/python2.6/site-packages (from gpsoauth==0.0.5->gmusicapi==7.0.1.dev0)
Requirement already satisfied (use --upgrade to upgrade): beautifulsoup4 in /usr/lib/python2.6/site-packages (from MechanicalSoup->gmusicapi==7.0.1.dev0)
Installing collected packages: gmusicapi
  Running setup.py install for gmusicapi
Successfully installed gmusicapi-7.0.1.dev0

[claudio@~]$ sudo pip install https://github.com/terencehonles/fusepy/tarball/master
Collecting https://github.com/terencehonles/fusepy/tarball/master
  Downloading https://github.com/terencehonles/fusepy/tarball/master
     / 16kB 6.6MB/s
Installing collected packages: fusepy
  Running setup.py install for fusepy
Successfully installed fusepy-2.0.2

[claudio@~]$ sudo pip install https://github.com/EnigmaCurry/GMusicFS/tarball/master
Collecting https://github.com/EnigmaCurry/GMusicFS/tarball/master
  Downloading https://github.com/EnigmaCurry/GMusicFS/tarball/master
     \ 8.2kB 3.1MB/s
Requirement already satisfied (use --upgrade to upgrade): fusepy in /usr/lib/python2.6/site-packages (from GMusicFS==0.1)
Requirement already satisfied (use --upgrade to upgrade): gmusicapi in /usr/lib/python2.6/site-packages (from GMusicFS==0.1)
Requirement already satisfied (use --upgrade to upgrade): validictory!=0.9.2,>=0.8.0 in /usr/lib/python2.6/site-packages (from gmusicapi->GMusicFS==0.1)
Requirement already satisfied (use --upgrade to upgrade): decorator>=3.3.1 in /usr/lib/python2.6/site-packages (from gmusicapi->GMusicFS==0.1)
Requirement already satisfied (use --upgrade to upgrade): mutagen>=1.18 in /usr/lib/python2.6/site-packages (from gmusicapi->GMusicFS==0.1)
Requirement already satisfied (use --upgrade to upgrade): protobuf>=2.4.1 in /usr/lib/python2.6/site-packages (from gmusicapi->GMusicFS==0.1)
Requirement already satisfied (use --upgrade to upgrade): requests!=1.2.0,!=2.2.1,<2.8.0,>=1.1.0 in /usr/lib/python2.6/site-packages (from gmusicapi->GMusicFS==0.1)
Requirement already satisfied (use --upgrade to upgrade): python-dateutil!=2.0,>=1.3 in /usr/lib/python2.6/site-packages (from gmusicapi->GMusicFS==0.1)
Requirement already satisfied (use --upgrade to upgrade): proboscis>=1.2.5.1 in /usr/lib/python2.6/site-packages (from gmusicapi->GMusicFS==0.1)
Requirement already satisfied (use --upgrade to upgrade): oauth2client>=1.1 in /usr/lib/python2.6/site-packages (from gmusicapi->GMusicFS==0.1)
Requirement already satisfied (use --upgrade to upgrade): mock>=0.7.0 in /usr/lib/python2.6/site-packages (from gmusicapi->GMusicFS==0.1)
Requirement already satisfied (use --upgrade to upgrade): appdirs>=1.1.0 in /usr/lib/python2.6/site-packages (from gmusicapi->GMusicFS==0.1)
Requirement already satisfied (use --upgrade to upgrade): gpsoauth==0.0.5 in /usr/lib/python2.6/site-packages (from gmusicapi->GMusicFS==0.1)
Requirement already satisfied (use --upgrade to upgrade): MechanicalSoup in /usr/lib/python2.6/site-packages (from gmusicapi->GMusicFS==0.1)
Requirement already satisfied (use --upgrade to upgrade): pyopenssl in /usr/lib64/python2.6/site-packages (from gmusicapi->GMusicFS==0.1)
Requirement already satisfied (use --upgrade to upgrade): ndg-httpsclient in /usr/lib/python2.6/site-packages (from gmusicapi->GMusicFS==0.1)
Requirement already satisfied (use --upgrade to upgrade): pyasn1 in /usr/lib/python2.6/site-packages (from gmusicapi->GMusicFS==0.1)
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/lib/python2.6/site-packages (from protobuf>=2.4.1->gmusicapi->GMusicFS==0.1)
Requirement already satisfied (use --upgrade to upgrade): six>=1.5 in /usr/lib/python2.6/site-packages (from python-dateutil!=2.0,>=1.3->gmusicapi->GMusicFS==0.1)
Requirement already satisfied (use --upgrade to upgrade): httplib2>=0.9.1 in /usr/lib/python2.6/site-packages (from oauth2client>=1.1->gmusicapi->GMusicFS==0.1)
Requirement already satisfied (use --upgrade to upgrade): pyasn1-modules>=0.0.5 in /usr/lib/python2.6/site-packages (from oauth2client>=1.1->gmusicapi->GMusicFS==0.1)
Requirement already satisfied (use --upgrade to upgrade): rsa>=3.1.4 in /usr/lib/python2.6/site-packages (from oauth2client>=1.1->gmusicapi->GMusicFS==0.1)
Requirement already satisfied (use --upgrade to upgrade): funcsigs in /usr/lib/python2.6/site-packages (from mock>=0.7.0->gmusicapi->GMusicFS==0.1)
Requirement already satisfied (use --upgrade to upgrade): pbr>=0.11 in /usr/lib/python2.6/site-packages (from mock>=0.7.0->gmusicapi->GMusicFS==0.1)
Requirement already satisfied (use --upgrade to upgrade): pycrypto>=2.5 in /usr/lib64/python2.6/site-packages (from gpsoauth==0.0.5->gmusicapi->GMusicFS==0.1)
Requirement already satisfied (use --upgrade to upgrade): beautifulsoup4 in /usr/lib/python2.6/site-packages (from MechanicalSoup->gmusicapi->GMusicFS==0.1)
Installing collected packages: GMusicFS
  Running setup.py install for GMusicFS
Successfully installed GMusicFS-0.1

[claudio@~]$ gmusicfs
Traceback (most recent call last):
  File "/usr/bin/gmusicfs", line 9, in <module>
    load_entry_point('GMusicFS==0.1', 'console_scripts', 'gmusicfs')()
  File "/usr/lib/python2.6/site-packages/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.6/site-packages/pkg_resources/__init__.py", line 2721, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.6/site-packages/pkg_resources/__init__.py", line 2377, in load
    return self.resolve()
  File "/usr/lib/python2.6/site-packages/pkg_resources/__init__.py", line 2383, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.6/site-packages/gmusicfs/gmusicfs.py", line 20, in <module>
    from gmusicapi import Mobileclient as GoogleMusicAPI
  File "/usr/lib/python2.6/site-packages/gmusicapi/__init__.py", line 4, in <module>
    from gmusicapi.clients import Webclient, Musicmanager, Mobileclient
  File "/usr/lib/python2.6/site-packages/gmusicapi/clients/__init__.py", line 2, in <module>
    from gmusicapi.clients.webclient import Webclient
  File "/usr/lib/python2.6/site-packages/gmusicapi/clients/webclient.py", line 7, in <module>
    from gmusicapi.clients.shared import _Base
  File "/usr/lib/python2.6/site-packages/gmusicapi/clients/shared.py", line 4, in <module>
    from gmusicapi.utils import utils
  File "/usr/lib/python2.6/site-packages/gmusicapi/utils/utils.py", line 24, in <module>
    from gmusicapi.compat import my_appdirs
  File "/usr/lib/python2.6/site-packages/gmusicapi/compat.py", line 15, in <module>
    import unittest2 as unittest
ImportError: No module named unittest2

[claudio@~]$ sudo gmusicfs
Traceback (most recent call last):
  File "/usr/bin/gmusicfs", line 9, in <module>
    load_entry_point('GMusicFS==0.1', 'console_scripts', 'gmusicfs')()
  File "/usr/lib/python2.6/site-packages/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.6/site-packages/pkg_resources/__init__.py", line 2721, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.6/site-packages/pkg_resources/__init__.py", line 2377, in load
    return self.resolve()
  File "/usr/lib/python2.6/site-packages/pkg_resources/__init__.py", line 2383, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.6/site-packages/gmusicfs/gmusicfs.py", line 20, in <module>
    from gmusicapi import Mobileclient as GoogleMusicAPI
  File "/usr/lib/python2.6/site-packages/gmusicapi/__init__.py", line 4, in <module>
    from gmusicapi.clients import Webclient, Musicmanager, Mobileclient
  File "/usr/lib/python2.6/site-packages/gmusicapi/clients/__init__.py", line 2, in <module>
    from gmusicapi.clients.webclient import Webclient
  File "/usr/lib/python2.6/site-packages/gmusicapi/clients/webclient.py", line 7, in <module>
    from gmusicapi.clients.shared import _Base
  File "/usr/lib/python2.6/site-packages/gmusicapi/clients/shared.py", line 4, in <module>
    from gmusicapi.utils import utils
  File "/usr/lib/python2.6/site-packages/gmusicapi/utils/utils.py", line 24, in <module>
    from gmusicapi.compat import my_appdirs
  File "/usr/lib/python2.6/site-packages/gmusicapi/compat.py", line 15, in <module>
    import unittest2 as unittest
ImportError: No module named unittest2

[claudio@~]$

Is it plattform issue or something else?

**Comment by simon-weber** [comment]
Sorry, python 2.6 isn't supported anymore. It ought to work with 2.7.

**Comment by cecaceres** [comment]
Thanks!
I upgraded to 2.7, but I broked yum, I'm checking options to have both versions at same time

**Comment by simon-weber** [comment]
I've used https://github.com/yyuu/pyenv to some success, though I think virtualenv alone might fix your case if you create the env with the python2.7 binary.

**Comment by cecaceres** [comment]
Installed pyenv and then python 2.7.10
It worked!
but...

I guess my environment is fine:
`[claudio@gmusic]$ pwd`
`/usr/local/gmusic`
`[claudio@gmusic]$ ls -la .python-version`
`-rw-rw-r--.  1 claudio claudio    7 dic 10 16:48 .python-version`
`[claudio@gmusic]$ cat .python-version`
`2.7.10`
`[claudio@gmusic]$ python -V`
`Python 2.7.10`

Now, what I'm doing:
`[claudio@gmusic]$ gmusicfs --deviceid`
`/usr/local/pyenv/versions/2.7.10/lib/python2.7/site-packages/bs4/__init__.py:166: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html.parser"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.`

`To get rid of this warning, change this:`

`BeautifulSoup([your markup])`

`to this:`

`BeautifulSoup([your markup], "html.parser")`

`  markup_type=markup_type))`
`AndroidS : 0x3650031938xxxxxx`
`Android4 : 0x3a54851358xxxxxx`
`Android2x : 0x3fe29a9ee6xxxxxx`

It doesn't create new device id, so, I put in ~/gmusicfs one of existing:
`[claudio@gmusic]$ cat ~/.gmusicfs`
`[credentials]`
`username=cxxxx@gmail.com`
`password=xxxxx`
`deviceId=0x3fe29a9ee6xxxxxx`

then, I try to mount...
`[claudio@gmusic]$ gmusicfs -vv ~/gmusic`
`INFO:gmusicapi.Mobileclient1:!-- begin debug log --!`
`INFO:gmusicapi.Mobileclient1:version: 7.0.1-dev`
`INFO:gmusicapi.Mobileclient1:logging to: /home/claudio/.cache/gmusicapi/log/gmusicapi.log`
`INFO:gmusicapi.Mobileclient1:initialized`
`INFO:gmusicapi.Mobileclient1:logged out`
`INFO:gmusicfs:Logging in...`
`Traceback (most recent call last):`
`  File "/usr/local/pyenv/versions/2.7.10/bin/gmusicfs", line 9, in <module>`
`    load_entry_point('GMusicFS==0.1', 'console_scripts', 'gmusicfs')()`
`  File "/usr/local/pyenv/versions/2.7.10/lib/python2.7/site-packages/gmusicfs/gmusicfs.py", line 476, in main`
`    fs = GMusicFS(mountpoint, true_file_size=args.true_file_size, verbose=verbosity, scan_library= not args.nolibrary)`
`  File "/usr/local/pyenv/versions/2.7.10/lib/python2.7/site-packages/gmusicfs/gmusicfs.py", line 240, in __init__`
`    true_file_size=true_file_size, verbose=verbose, scan=scan_library)`
`  File "/usr/local/pyenv/versions/2.7.10/lib/python2.7/site-packages/gmusicfs/gmusicfs.py", line 132, in __init__`
`    self.__login_and_setup(username, password)`
`  File "/usr/local/pyenv/versions/2.7.10/lib/python2.7/site-packages/gmusicfs/gmusicfs.py", line 176, in __login_and_setup`
`    self.api.login(username, password)`
`TypeError: login() takes exactly 4 arguments (3 given)`

Error says *4 arguments (3 given)* -> What am I missing?

**Comment by simon-weber** [comment]
Oh, I missed that you were working with gmusicfs; sorry. The error you're seeing now is on gmusicfs's end: it's built for an outdated version of gmusicapi and there have been [multiple breaking changes](https://github.com/simon-weber/gmusicapi/blob/develop/HISTORY.rst) since then. In particular, it looks like https://github.com/EnigmaCurry/GMusicFS/pull/38 fixes the problem you're seeing.

**Comment by cecaceres** [comment]
Perfect!
It worked

Thanks

**Comment by simon-weber** [comment]
Happy to help!
