### ISSUE TITLE
ValidationException: Required field 'artistId' is missing

### ISSUE THREAD

**Issue by gandalf14** [simon-weber/gmusicapi#391]
2016-01-01 18:36:01,151 - gmusicapi.Mobileclient1 (shared:281) [ERROR]: the response format for Search was not recognized.

Required field 'artistId' is missing

First, try the develop branch. If you can recreate this error with the most recent code please [create an issue](http://goo.gl/qbAW8) that includes the above ValidationException and the following request/response:
{'url': 'https://mclients.googleapis.com/sj/v1.11/query', 'headers': {'Authorization': '<omitted>'}, 'params': {'q': u'Green Day Working Class Hero', 'max-results': 5}, 'method': 'GET'}

'{\n "kind": "sj#searchresponse",\n "entries": [\n  {\n   "type": "2",\n   "artist": {\n    "kind": "sj#artist",\n    "name": "Green Day",\n    "artistArtRef": "http://lh3.googleusercontent.com/Taog3UD1LR6QFlN6XQ6aSREwi5WuTa87uPCIhNB-LV0Pj8xk9tx9UWn02v5mRUqgEGmJ5usY",\n    "artistId": "Aobnbagaujlk2pbajnfhenlwvl4",\n    "artist_bio_attribution": {\n     "kind": "sj#attribution",\n     "source_title": "Wikipedia",\n     "source_url": "http://en.wikipedia.org/wiki/Green_Day",\n     "license_title": "Creative Commons Attribution CC-BY-SA 4.0",\n     "license_url": "http://creativecommons.org/licenses/by-sa/4.0/legalcode"\n    }\n   },\n   "best_result": false,\n   "navigational_result": false\n  },\n  {\n   "type": "2",\n   "artist": {\n    "kind": "sj#artist",\n    "name": "John Lennon",\n    "artistArtRef": "http://lh3.googleusercontent.com/4fL5gDEH95B34OuskOHmSa5UhBkSQpOW1nYGMBnkw0sGZr367GwR_aEV6jeaZiKA2W5rbnY0OQ",\n    "artistId": "Ad7ak2jizbqd4ftjeb4ni24755e",\n    "artist_bio_attribution": {\n     "kind": "sj#attribution",\n     "source_title": "Wikipedia",\n     "source_url": "http://en.wikipedia.org/wiki/John_Lennon",\n     "license_title": "Creative Commons Attribution CC-BY-SA 4.0",\n     "license_url": "http://creativecommons.org/licenses/by-sa/4.0/legalcode"\n    }\n   },\n   "best_result": false,\n   "navigational_result": false\n  },\n  {\n   "type": "3",\n   "album": {\n    "kind": "sj#album",\n    "name": "Plastic Ono Band",\n    "albumArtist": "John Lennon",\n    "albumArtRef": "http://lh4.ggpht.com/Sa4RllXGchJMjzqQU0N29ywU20r_bf0df71uv3eocmLTlCMEwsMA5vqAOK9yVNrqTuQoDM2sew",\n    "albumId": "B23fvx6okvoszpj7b4eesj6dnly",\n    "artist": "John Lennon",\n    "artistId": [\n     "Ad7ak2jizbqd4ftjeb4ni24755e"\n    ],\n    "description_attribution": {\n     "kind": "sj#attribution",\n     "source_title": "Wikipedia",\n     "source_url": "http://en.wikipedia.org/wiki/John_Lennon/Plastic_Ono_Band",\n     "license_title": "Creative Commons Attribution CC-BY-SA 4.0",\n     "license_url": "http://creativecommons.org/licenses/by-sa/4.0/legalcode"\n    },\n    "year": 1970\n   },\n   "best_result": false,\n   "navigational_result": false\n  },\n  {\n   "type": "3",\n   "album": {\n    "kind": "sj#album",\n    "name": "Working Class Hero - A Tribute to Green Day",\n    "albumArtist": "Ameritz Tribute Club",\n    "albumArtRef": "http://lh4.ggpht.com/OI2ISXtdTmbgR28TYz3yjnUcej0rT_ZWq0vIT77NMOoEyjIbRaz3ixKE6yljFUJbRf4ENCZumNM",\n    "albumId": "Be6j6yy4wz5aox3gcreltiin6ea",\n    "artist": "Ameritz Tribute Club",\n    "artistId": [\n     "Abfss4t2qygg4y2rh5kaynvxr7y"\n    ],\n    "year": 2012\n   },\n   "best_result": false,\n   "navigational_result": false\n  },\n  {\n   "type": "3",\n   "album": {\n    "kind": "sj#album",\n    "name": "Instant Karma: The Amnesty International Campaign to Save Darfur",\n    "albumArtist": "",\n    "albumId": "Bqk2lmd6kfg4nwbkaa35zoopoaa",\n    "artist": "",\n    "description_attribution": {\n     "kind": "sj#attribution",\n     "source_title": "Wikipedia",\n     "source_url": "http://en.wikipedia.org/wiki/Instant_Karma:_The_Amnesty_International_Campaign_to_Save_Darfur",\n     "license_title": "Creative Commons Attribution CC-BY-SA 4.0",\n     "license_url": "http://creativecommons.org/licenses/by-sa/4.0/legalcode"\n    },\n    "year": 2007\n   },\n   "best_result": false,\n   "navigational_result": false\n  },\n  {\n   "type": "3",\n   "album": {\n    "kind": "sj#album",\n    "name": "Working Class Hero (In the Style of Green Day) [Performance Track with Demonstration Vocals]",\n    "albumArtist": "Done Again",\n    "albumArtRef": "http://lh6.ggpht.com/jRv8T2RGhJSEU5l-NQ4FpTP3c3CtSOrh_2WrQbkuXvRVbiEYRBVsy_X55RxfCK_ZsbP5EtErDYw",\n    "albumId": "Bhwlphi2sre67i62huw4dqzmnbu",\n    "artist": "Done Again",\n    "artistId": [\n     "Afqaclvfhwyd5aryvwt6qz4axg4"\n    ],\n    "year": 2011\n   },\n   "best_result": false,\n   "navigational_result": false\n  },\n  {\n   "type": "1",\n   "track": {\n    "kind": "sj#track",\n    "title": "Working Class Hero",\n    "artist": "Green Day",\n    "composer": "",\n    "album": "Instant Karma: The Amnesty International Campaign To Save Darfur",\n    "albumArtist": "Various Artists",\n    "year": 2007,\n    "trackNumber": 13,\n    "genre": "Pop",\n    "durationMillis": "263000",\n    "albumArtRef": [\n     {\n      "url": "http://lh3.ggpht.com/jC94qAaRDa3eF0FK3UMUJ7VLm4Jth6KVyeMRW1zhnIKJmdwb3VxQczLpvf3eYXF1eK4S8oVf"\n     }\n    ],\n    "discNumber": 1,\n    "estimatedSize": "10552451",\n    "trackType": "7",\n    "storeId": "Tarakvjh7vkcmsfwzct52si4jxu",\n    "albumId": "Bxs6dyco3ef5qqh4xge6cxelmda",\n    "artistId": [\n     "Aobnbagaujlk2pbajnfhenlwvl4"\n    ],\n    "nid": "Tarakvjh7vkcmsfwzct52si4jxu",\n    "trackAvailableForSubscription": true,\n    "trackAvailableForPurchase": true,\n    "albumAvailableForPurchase": true,\n    "contentType": "2",\n    "primaryVideo": {\n     "kind": "sj#video",\n     "id": "UPPgeDhGzKY",\n     "thumbnails": [\n      {\n       "url": "https://i.ytimg.com/vi/UPPgeDhGzKY/mqdefault.jpg",\n       "width": 320,\n       "height": 180\n      }\n     ]\n    }\n   },\n   "best_result": false,\n   "navigational_result": false\n  },\n  {\n   "type": "1",\n   "track": {\n    "kind": "sj#track",\n    "title": "Working Class Hero (2010 - Remaster)",\n    "artist": "John Lennon",\n    "composer": "",\n    "album": "Plastic Ono Band",\n    "albumArtist": "John Lennon",\n    "year": 1970,\n    "trackNumber": 4,\n    "genre": "\'70s Rock",\n    "durationMillis": "227000",\n    "albumArtRef": [\n     {\n      "url": "http://lh4.ggpht.com/Sa4RllXGchJMjzqQU0N29ywU20r_bf0df71uv3eocmLTlCMEwsMA5vqAOK9yVNrqTuQoDM2sew"\n     }\n    ],\n    "discNumber": 1,\n    "estimatedSize": "9120014",\n    "trackType": "7",\n    "storeId": "Tdbezspyhoctu3k23wkgcmt3m6q",\n    "albumId": "B23fvx6okvoszpj7b4eesj6dnly",\n    "artistId": [\n     "Ad7ak2jizbqd4ftjeb4ni24755e"\n    ],\n    "nid": "Tdbezspyhoctu3k23wkgcmt3m6q",\n    "trackAvailableForSubscription": true,\n    "trackAvailableForPurchase": true,\n    "albumAvailableForPurchase": true,\n    "contentType": "2",\n    "primaryVideo": {\n     "kind": "sj#video",\n     "id": "ziwsjE1O4Ow",\n     "thumbnails": [\n      {\n       "url": "https://i.ytimg.com/vi/ziwsjE1O4Ow/mqdefault.jpg",\n       "width": 320,\n       "height": 180\n      }\n     ]\n    }\n   },\n   "best_result": false,\n   "navigational_result": false\n  },\n  {\n   "type": "1",\n   "track": {\n    "kind": "sj#track",\n    "title": "Working Class Hero (Singalong Version)",\n    "artist": "The Punk Heroes",\n    "composer": "",\n    "album": "A Salute To Green Day",\n    "albumArtist": "Various Artists",\n    "trackNumber": 35,\n    "genre": "Alternative/Indie",\n    "durationMillis": "287000",\n    "albumArtRef": [\n     {\n      "url": "http://lh5.ggpht.com/EwvHlxhUCwht8bSq_omIvG8ZoXlzzw_KsrxnnOQZCRvqB_jULGsoXsGYifqfESSfL19fbeEh_jM"\n     }\n    ],\n    "discNumber": 1,\n    "estimatedSize": "11494955",\n    "trackType": "7",\n    "storeId": "Tcv5i5p6s3mxrl34df6ytlr55zi",\n    "albumId": "Bovean3437hp4qb6aa4aakaekpe",\n    "artistId": [\n     "Ac2naxf45qiovyjib3w22ckbde4"\n    ],\n    "nid": "Tcv5i5p6s3mxrl34df6ytlr55zi",\n    "trackAvailableForSubscription": true,\n    "trackAvailableForPurchase": true,\n    "albumAvailableForPurchase": true,\n    "contentType": "2"\n   },\n   "best_result": false,\n   "navigational_result": false\n  },\n  {\n   "type": "1",\n   "track": {\n    "kind": "sj#track",\n    "title": "Working Class Hero",\n    "artist": "Flies on the Square Egg",\n    "composer": "",\n    "album": "A Tribute to Green Day",\n    "albumArtist": "Flies on the Square Egg",\n    "year": 2014,\n    "trackNumber": 9,\n    "genre": "Rock",\n    "durationMillis": "241000",\n    "albumArtRef": [\n     {\n      "url": "http://lh3.ggpht.com/GoNHOZmnNXGGlEVgYX3bCZhwB_63kyUJwznhJ6QZSMcdqVGJ7KY57kZx5rpRyurEParKaszzhQ"\n     }\n    ],\n    "discNumber": 1,\n    "estimatedSize": "9668468",\n    "trackType": "7",\n    "storeId": "Tnhi7nraxo7i7coqtbx5bmbvwvy",\n    "albumId": "Brbv3btcm5o74pvhlyhfgw3x3gu",\n    "artistId": [\n     "Aog4nlabf2lrzcmispyzgt7erdq"\n    ],\n    "nid": "Tnhi7nraxo7i7coqtbx5bmbvwvy",\n    "trackAvailableForSubscription": true,\n    "trackAvailableForPurchase": true,\n    "albumAvailableForPurchase": true,\n    "contentType": "2"\n   },\n   "best_result": false,\n   "navigational_result": false\n  },\n  {\n   "type": "1",\n   "track": {\n    "kind": "sj#track",\n    "title": "Working Class Hero",\n    "artist": "Ameritz Tribute Club",\n    "composer": "",\n    "album": "Working Class Hero - A Tribute to Green Day",\n    "albumArtist": "Ameritz Tribute Club",\n    "trackNumber": 12,\n    "genre": "Alternative/Indie",\n    "durationMillis": "248000",\n    "albumArtRef": [\n     {\n      "url": "http://lh4.ggpht.com/OI2ISXtdTmbgR28TYz3yjnUcej0rT_ZWq0vIT77NMOoEyjIbRaz3ixKE6yljFUJbRf4ENCZumNM"\n     }\n    ],\n    "discNumber": 1,\n    "estimatedSize": "9952686",\n    "trackType": "7",\n    "storeId": "Tdgvoivepciibwkrk7r4vf4qhvu",\n    "albumId": "Be6j6yy4wz5aox3gcreltiin6ea",\n    "artistId": [\n     "Abfss4t2qygg4y2rh5kaynvxr7y"\n    ],\n    "nid": "Tdgvoivepciibwkrk7r4vf4qhvu",\n    "trackAvailableForSubscription": true,\n    "trackAvailableForPurchase": true,\n    "albumAvailableForPurchase": true,\n    "contentType": "2"\n   },\n   "best_result": false,\n   "navigational_result": false\n  },\n  {\n   "type": "6",\n   "station": {\n    "kind": "sj#radioStation",\n    "name": "Green Day",\n    "seed": {\n     "kind": "sj#radioSeed",\n     "artistId": "Aobnbagaujlk2pbajnfhenlwvl4",\n     "seedType": "3"\n    },\n    "imageUrls": [\n     {\n      "url": "http://lh3.googleusercontent.com/Taog3UD1LR6QFlN6XQ6aSREwi5WuTa87uPCIhNB-LV0Pj8xk9tx9UWn02v5mRUqgEGmJ5usY"\n     }\n    ]\n   },\n   "best_result": false,\n   "navigational_result": false\n  },\n  {\n   "type": "6",\n   "station": {\n    "kind": "sj#radioStation",\n    "name": "John Lennon",\n    "seed": {\n     "kind": "sj#radioSeed",\n     "artistId": "Ad7ak2jizbqd4ftjeb4ni24755e",\n     "seedType": "3"\n    },\n    "imageUrls": [\n     {\n      "url": "http://lh3.googleusercontent.com/4fL5gDEH95B34OuskOHmSa5UhBkSQpOW1nYGMBnkw0sGZr367GwR_aEV6jeaZiKA2W5rbnY0OQ"\n     }\n    ]\n   },\n   "best_result": fa...'

A traceback follows:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/gmusicapi/protocol/shared.py", line 248, in perform
    cls.validate(response, parsed_response)
  File "/usr/local/lib/python2.7/site-packages/gmusicapi/protocol/mobileclient.py", line 279, in validate
    return validictory.validate(msg, cls._res_schema)
  File "/usr/local/lib/python2.7/site-packages/validictory/__init__.py", line 43, in validate
    return v.validate(data, schema)
  File "/usr/local/lib/python2.7/site-packages/validictory/validator.py", line 578, in validate
    self.__validate("data", {"data": data}, schema, '<obj>')
  File "/usr/local/lib/python2.7/site-packages/validictory/validator.py", line 614, in __validate
    validator(data, fieldname, schema, path, newschema.get(schemaprop))
  File "/usr/local/lib/python2.7/site-packages/validictory/validator.py", line 273, in validate_properties
    path + '.' + property)
  File "/usr/local/lib/python2.7/site-packages/validictory/validator.py", line 614, in __validate
    validator(data, fieldname, schema, path, newschema.get(schemaprop))
  File "/usr/local/lib/python2.7/site-packages/validictory/validator.py", line 307, in validate_items
    '{}[{}]'.format(path, index))
  File "/usr/local/lib/python2.7/site-packages/validictory/validator.py", line 614, in __validate
    validator(data, fieldname, schema, path, newschema.get(schemaprop))
  File "/usr/local/lib/python2.7/site-packages/validictory/validator.py", line 273, in validate_properties
    path + '.' + property)
  File "/usr/local/lib/python2.7/site-packages/validictory/validator.py", line 614, in __validate
    validator(data, fieldname, schema, path, newschema.get(schemaprop))
  File "/usr/local/lib/python2.7/site-packages/validictory/validator.py", line 273, in validate_properties
    path + '.' + property)
  File "/usr/local/lib/python2.7/site-packages/validictory/validator.py", line 614, in __validate
    validator(data, fieldname, schema, path, newschema.get(schemaprop))
  File "/usr/local/lib/python2.7/site-packages/validictory/validator.py", line 317, in validate_required
    exctype=RequiredFieldValidationError)
  File "/usr/local/lib/python2.7/site-packages/validictory/validator.py", line 185, in _error
    raise err
ValidationException: Required field 'artistId' is missing

**Comment by simon-weber** [comment]
Thanks!
