### ISSUE TITLE
IFL keeps starting with same Artist

### ISSUE THREAD

**Issue by Tadly** [simon-weber/gmusicapi#393]
Whenever I (and other users) start a new IFL radio, the radio always starts with the same artist for as long as there are tracks you haven't listend to.
Including a list of recently_played_ids or not doesn't change anything.

Using newer API versions didn't work either (tested 2.1, 2.2, 2.3, 2.4)

On official clients it "works" as expected.
So I'm guessing google might have some client logic behind IFL radios (which would suck) but I'm not sure on that.

**Comment by Tadly** [comment]
Quickly logged a IFL radio request from my phone just in case it might help :)

POST /sj/v2.3/radio/stationfeed?alt=json&hl=en_GB&tier=aa&rz=start

```json
{
   "contentFilter":1,
   "stations":[
      {
         "libraryContentOnly":false,
         "numEntries":25,
         "recentlyPlayed":[

         ],
         "seed":{
            "seedType":6
         }
      }
   ]
}
```

**Comment by rrader** [comment]
still reproduces
installed on ArchLinux from AUR (gmusicproxy-stable) v. 1.0.5

**Comment by Tadly** [comment]
Just bumped gmusicapi to 10.1.0 in my kodi add-on and I think this issue might actually be resolved.
I'll do some more testing.

@rrader gmusicproxy-stable has [python2-gmusicapi](https://aur.archlinux.org/packages/python2-gmusicapi/) as an dependency which is still based on version 9.0.0 (as of the time writing this) and has already been flagged out-of-date.
gmusicproxy-stable seems to allow [python2-gmusicapi-git](https://aur.archlinux.org/packages/python2-gmusicapi-git/) as alternative though so you might give that a try...

**Comment by rrader** [comment]
@Tadly with git version i'm getting

```
Nov 09 18:14:46 antigluk-desktop systemd[1]: Started Let's stream Google Play Music using any media-player.
Nov 09 18:14:46 antigluk-desktop GMusicProxy[5445]: Traceback (most recent call last):
Nov 09 18:14:46 antigluk-desktop GMusicProxy[5445]:   File "/usr/bin/GMusicProxy", line 30, in <module>
Nov 09 18:14:46 antigluk-desktop GMusicProxy[5445]:     import gmusicapi, gmusicapi.utils, eyed3.id3
Nov 09 18:14:46 antigluk-desktop GMusicProxy[5445]:   File "/usr/lib/python2.7/site-packages/gmusicapi/__init__.py", line 4, in <module>
Nov 09 18:14:46 antigluk-desktop GMusicProxy[5445]:     from gmusicapi.clients import Webclient, Musicmanager, Mobileclient
Nov 09 18:14:46 antigluk-desktop GMusicProxy[5445]:   File "/usr/lib/python2.7/site-packages/gmusicapi/clients/__init__.py", line 5, in <modu
Nov 09 18:14:46 antigluk-desktop GMusicProxy[5445]:     from gmusicapi.clients.musicmanager import Musicmanager, OAUTH_FILEPATH
Nov 09 18:14:46 antigluk-desktop GMusicProxy[5445]:   File "/usr/lib/python2.7/site-packages/gmusicapi/clients/musicmanager.py", line 27, in 
Nov 09 18:14:46 antigluk-desktop GMusicProxy[5445]:     from gmusicapi.protocol import musicmanager, upload_pb2, locker_pb2
Nov 09 18:14:46 antigluk-desktop GMusicProxy[5445]:   File "/usr/lib/python2.7/site-packages/gmusicapi/protocol/musicmanager.py", line 24, in
Nov 09 18:14:46 antigluk-desktop GMusicProxy[5445]:     from gmusicapi.protocol import upload_pb2, locker_pb2, download_pb2
Nov 09 18:14:46 antigluk-desktop GMusicProxy[5445]:   File "/usr/lib/python2.7/site-packages/gmusicapi/protocol/upload_pb2.py", line 16, in <
Nov 09 18:14:46 antigluk-desktop GMusicProxy[5445]:     from . import locker_pb2 as locker__pb2
Nov 09 18:14:46 antigluk-desktop GMusicProxy[5445]:   File "/usr/lib/python2.7/site-packages/gmusicapi/protocol/locker_pb2.py", line 16, in <
Nov 09 18:14:46 antigluk-desktop GMusicProxy[5445]:     from . import uits_pb2 as uits__pb2
Nov 09 18:14:46 antigluk-desktop GMusicProxy[5445]:   File "/usr/lib/python2.7/site-packages/gmusicapi/protocol/uits_pb2.py", line 22, in <mo
Nov 09 18:14:46 antigluk-desktop GMusicProxy[5445]:     \x12\x32\n\x08url_info\x18\x08 \x01(\x0b\x32 .wireless_android_skyjam.UrlInfo\x12Z\n\
Nov 09 18:14:46 antigluk-desktop GMusicProxy[5445]: TypeError: __init__() got an unexpected keyword argument 'syntax'
Nov 09 18:14:46 antigluk-desktop systemd[1]: gmusicproxy.service: Main process exited, code=exited, status=1/FAILURE

```

**Comment by Tadly** [comment]
@rrader I think that's a problem with out-to-date dependencies of gmusicapi.

You probably should downgrade again as there has been some breakage between v9 and v10 of gmusicapi and gmusicproxy requires V9 which you can see [here](https://github.com/diraimondo/gmusicproxy/blob/master/setup.py#L27)

You could ask them to support V10 :)

**Comment by Tadly** [comment]
Tested again on multiple setups and worked.
I'll close the issue

**Comment by simon-weber** [comment]
Weird! I don't know what would have changed to fix it on our end, so maybe Google fixed this.

**Comment by Tadly** [comment]
@simon-weber sadly no. When using v9 the bug persists :)
How you guys fixed it, I don't know but I really don't mind. Let's just keep it :)

**Comment by rrader** [comment]
ok guys, looks like it's easier to make own music library :trollface: 

OR write a tool on Selenium that would click on IFL on google music site

**Comment by rektide** [comment]
I still have this problem! I'm stuck eternally in college rock and lou reed. Please help!

I kind of want both- more random songs for the current station, and a way to get a new station.

**Comment by rektide** [comment]
Hey sorry this is perhaps a false alarm. I'm a perpetual newbie when it comes to Python and still trying to make heads or tales of this, but I think it might be gmusicproxy using a really old version.

I'm following up with upstream at https://github.com/diraimondo/gmusicproxy/issues/46

**Comment by simon-weber** [comment]
No worries. Let us know if you manage to escape!

**Comment by rektide** [comment]
I thought I might try better to see what the API's behavior was, so I hacked the standard example into what I thought would be a thing that would give me a random playlist each time. I'm getting music from the same seed each time this runs. Is that expected? Is there a way to get a new seed?
https://gist.github.com/rektide/98e894c86bb1eeb5f3b40405e16d718e

**Comment by diraimondo** [comment]
On my gmusicproxy, using gmusicapi 10.1.0, I'm still facing this problem.

**Comment by Tadly** [comment]
@rektide @diraimondo are you using the master branch version of gmusicproxy or the latest release (v1.0.6 as of this point)?
v1.0.6 still uses gmusicapi 9.0.0.
I've also had a quick look at the master branch source of gmusicproxy which looks ok to me.
That's all I can add to this :)

**Comment by diraimondo** [comment]
@Tadly gmusicproxy v.1.0.6 already use gmusicapi 10.1.0 and yes, I'm using the master branch version.

I looked at the code of the kodi plugin; I've not seen anything special: a query using `IFL` as special id of the station.

**Comment by Tadly** [comment]
>gmusicproxy v.1.0.6 already use gmusicapi 10.1.0

You sure? I had a look at the tag and the commit you tagged as v1.0.6 has v9.0.0 in the setup.py

>I looked at the code of the kodi plugin; I've not seen anything special: a query using IFL as special id of the station.

Yap, as I said, your source looks fine to me.

**Comment by diraimondo** [comment]
@Tadly Ok, you are right. I probably pushed the 'release' button too early in GitHub. Anyway, I'm used the latest code in my tests.

**Comment by mgillespie** [comment]
Some feedback here, seeing the exact same problem as described.  All my IFS playlists in gmusic proxy come back almost identical each time, with the same old songs (but in a different order).

Using gmusicproxy 1.0.7 and gmusicapi 10.1.0

It's really easy to test, just request a IFS playlist a few times and look at how similar they are.

**Comment by dhoare12** [comment]
I'm seeing similar behaviour - the request format for IFL radio seems to have changed (as in Tadly's [comment](#issuecomment-169774542))
Amending [dynamic_data for ListStationTracks](https://github.com/simon-weber/gmusicapi/blob/develop/gmusicapi/protocol/mobileclient.py#L1411) to include a `seed` property instead of `radioId` when IFL is requested seems to fix the issue.
