### ISSUE TITLE
Musicmanager client id does not match Google's

### ISSUE THREAD

**Issue by simon-weber** [simon-weber/gmusicapi#397]
[This has been the case forever](https://github.com/simon-weber/gmusicapi/blob/a5c15886dde6b93708f47e0ef7e70644a405df3c/gmusicapi/protocol/musicmanager.py#L146), and seemingly didn't cause any trouble until https://github.com/simon-weber/gmusicapi/issues/380#issuecomment-156738383.

https://github.com/simon-weber/gmusicapi/issues/380#issuecomment-156743098 shows that eyed3 will usually strip the right tags to cause a match.

**Comment by thebigmunch** [comment]
Note that this change will cause the upload of duplicates of songs uploaded with previous versions of gmusicapi due to generating a different client id. However, it removes the previous behavior of uploading a duplicate song if the metadata is changed in the future.
