### ISSUE TITLE
get_stream_url with all access track ids.

### ISSUE THREAD

**Issue by CinemarDave** [simon-weber/gmusicapi#404]
Can anyone provide an example of get_stream_url that uses an all access track id that works and does not return a 404 error?

**Comment by simon-weber** [comment]
Try `'Tqqufr34tuqojlvkolsrwdwx7pe'` -- the test suite just successfully retrieved a url for that id.

**Comment by mrdavidli** [comment]
Thanks, and should have said I have tried that one and many others. All I get is the following

I've added two lines to the example.py file

foo = api.get_stream_url("Tqqufr34tuqojlvkolsrwdwx7pe", "000000000429B3C8", "hi")
print(foo)

and this is what I get. Can you see my error? Thanks.

C:\Python\gmusic>python example.py
Successfully logged in.

Traceback (most recent call last):
  File "example.py", line 97, in <module>
    demonstrate()
  File "example.py", line 46, in demonstrate
    foo = api.get_stream_url("Tqqufr34tuqojlvkolsrwdwx7pe", "000000000429B3C8", "hi")
  File "<decorator-gen-78>", line 2, in get_stream_url
  File "C:\Python\gmusic\gmusicapi\utils\utils.py", line 296, in wrapper
    return function(*args, **kw)
  File "C:\Python\gmusic\gmusicapi\clients\mobileclient.py", line 275, in get_stream_url
    return self._make_call(mobileclient.GetStreamUrl, song_id, device_id, quality)
  File "C:\Python\gmusic\gmusicapi\clients\shared.py", line 83, in _make_call
    return protocol.perform(self.session, self.validate, *args, **kwargs)
  File "C:\Python\gmusic\gmusicapi\protocol\shared.py", line 227, in perform
    raise CallFailure(err_msg, call_name)
gmusicapi.exceptions.CallFailure: GetStreamUrl: 404 Client Error: Not Found for url: https://android.clients.google.com/music/mplay?opt=hi&mjck=Tqqufr34tuqojlvkolsrwdwx7pe&pt=e&slt=1454255454231&sig=KUo-tAzCl1PPqv4x6gwTgHPiSbc&net=mob
(requests kwargs: {u'url': u'https://android.clients.google.com/music/mplay', u'headers': {u'X-Device-ID': u'000000000429B3C8', u'Authorization': u'<omitted>'}, u'allow_redirects': False, u'params': {u'opt': u'hi', u'mjck': u'Tqqufr34tuqojlvkolsrwdwx7pe', u'pt': u'e', u'slt': '1454255454231', u'sig': 'KUo-tAzCl1PPqv4x6gwTgHPiSbc', u'net': u'mob'}, u'method': u'GET'})
(response was: '<HTML>\n<HEAD>\n<TITLE>Not Found</TITLE>\n</HEAD>\n<BODY BGCOLOR="#FFFFFF" TEXT="#000000">\n<H1>Not Found</H1>\n<H2>Error 404</H2>\n</BODY>\n</HTML>\n')

C:\Python\gmusic>

**Comment by simon-weber** [comment]
Hm. I think it's got to involve your device id. Does it show up when you call http://unofficial-google-music-api.readthedocs.org/en/latest/reference/mobileclient.html#gmusicapi.clients.Mobileclient.get_registered_devices?

**Comment by mrdavidli** [comment]
Yes, thank you. I did not catch the fact that one must use a registered device id and not the fake one using the local mac address. Everything is working now.

**Comment by simon-weber** [comment]
Gotcha -- glad we got it figured out!
