### ISSUE TITLE
Missing module urlparse when using python 3

### ISSUE THREAD

**Issue by Lindenk** [simon-weber/gmusicapi#410]
It looks like gmusicapi has experimental python 3 support, although it doesn't look like I can import it yet because python 3 does not have `urlparse` as a module.

**Comment by thebigmunch** [comment]
What do you mean by "doesn't look like I can import it yet"? Have you actually tried and failed or are you just assuming?

This should just work due to using the python-future library for Python 2/3 compatibility. I don't use the Webclient, but I have no problem importing it.

**Comment by Lindenk** [comment]
Sorry, I should have been more specific. I was implying that I might have missed something when trying to use it.

On my system (Arch linux x64), if I take a fresh python install, install gmusicapi with pip, and attempt to import gmusicapi in a python 3 script, it throws a module not found exception for `urlparse`.

**Comment by thebigmunch** [comment]
No version of gmusicapi has been released yet since Python 3 support was added. You'd have to install from git develop branch (``pip install git+https://github.com/simon-weber/gmusicapi@develop``) for that. Simon hopes to get a new release out soon™.

**Comment by simon-weber** [comment]
> Simon hopes to get a new release out soon™.

:+1: hopefully tonight!

**Comment by simon-weber** [comment]
8.0.0 is out! Give this another shot, and feel free to reopen if it remains a problem.

**Comment by jodal** [comment]
Great news! :-)

Can the `py3k` branch be pruned from the repo now? Maybe some other branches too? Seems to be a lot of old cruft there.

**Comment by simon-weber** [comment]
Thanks for the reminder! I just cleared out a bunch of old stuff.
