### ISSUE TITLE
How to retrieve Favorite and Last Added playlists with songs?

### ISSUE THREAD

**Issue by sirkonst** [simon-weber/gmusicapi#411]
subj

**Comment by simon-weber** [comment]
This used to be part of the docs, but it looks like I removed it along with the webclient method. I'll add it back.

These playlists are calculated clientside, so gmusicapi can't retrieve them for you. See https://github.com/simon-weber/gmusicapi/issues/346#issuecomment-111154306 for more details.

**Comment by sirkonst** [comment]
As I see there is no way way to get all AA songs with thumb up which not added to library, right?

**Comment by simon-weber** [comment]
Right. https://github.com/simon-weber/gmusicapi/issues/182 tracks that issue.
