### ISSUE TITLE
Songs matching with matching disabled

### ISSUE THREAD

**Issue by thebigmunch** [simon-weber/gmusicapi#412]
I've seen a rash of this happening recently after never having seen it in years of use. I've had at least one song out of at least half a dozen randomly chosen albums testing my scripts/wrapper. It causes issues because the song is actually put in the library, but gmusicapi returns a tuple of empty dicts for the result.

This has been on Python 3 after the port. I haven't gotten to really test it well yet. Definitely needs testing to see if it happens on Python 2 with current version and Python 2 on prior version before porting. With luck, it's something that can be solved on gmusicapi's side and not another server oddity.

Edit: Probably best either way to set the matched result to the server_track_id since the song was actually matched.

**Comment by simon-weber** [comment]
Hm, I also noticed this during that weird uploading bug a few months back: https://github.com/simon-weber/gmusicapi/issues/380#issuecomment-156738383. I had assumed it got fixed along with it.

**Comment by thebigmunch** [comment]
Yeah, I had #397 in my head for this. And, after a quick test this morning, stripping the tag from the file resulted in a successful upload.
