### ISSUE TITLE
Webclient login fails

### ISSUE THREAD

**Issue by willemli** [simon-weber/gmusicapi#420]
When calling Webclient.login(email, password) it gives this error:

```
Traceback (most recent call last):
  File "Main.py", line 25, in <module>
    if g.login("email", "password"):
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/clients/webclient.py", line 60, in login
    if not self.session.login(email, password):
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/session.py", line 119, in login
    form.select("#Passwd")[0]['value'] = password
IndexError: list index out of range
```

I think it has to do with the fact that Google now asks for your email first, and the password field isn't added until you click "next" on the login screen.

**Comment by siebert** [comment]
Changing the line
`form.select("#Passwd")[0]['value'] = password`
to
`form.select("#Passwd-hidden")[0]['value'] = password`
worked for me.

**Comment by siebert** [comment]
Spoke too soon, the IndexError is fixed by my change, but it seems that the login isn't successfull:

```
  File "gmusicapi\session.py", line 81, in send
    raise NotLoggedIn
```

**Comment by willemli** [comment]
Changing it to 
`form.select("#Passwd-hidden")[0]['value'] = password`
won't work because the actual password field you need to submit is `Passwd`, but that field won't show up after you click the next button.

**Comment by siebert** [comment]
Ok, this change really works for me :)

```
        form = form_candidates[0]
        form.select("#Email")[0]['value'] = email
+
+        response = browser.submit(form, 'https://accounts.google.com/AccountLoginInfo')
+        
+        try:
+            response.raise_for_status()
+        except requests.HTTPError:
+            log.exception("submitting login form failed")
+            return False
+
+        form_candidates = response.soup.select("form")
+        if len(form_candidates) > 1:
+            log.error("Google login form dom has changed; there are %s candidate forms:\n%s",
+                      len(form_candidates), form_candidates)
+            return False
+
+        form = form_candidates[0]
        form.select("#Passwd")[0]['value'] = password

        response = browser.submit(form, 'https://accounts.google.com/ServiceLoginAuth')

```

**Comment by willemli** [comment]
Works for me as well, awesome! Thanks :+1:

**Comment by siebert** [comment]
I think we should keep this issue open until someone commits my (or a different) change to the git repository.

**Comment by willemli** [comment]
Oops, reopened the issue. How do I use your code instead of the original code? I'm kinda new to Python

**Comment by simon-weber** [comment]
@siebert looks reasonable to me. Can you open a pr? This ought to be simple enough to do it entirely through the web interface: try clicking the edit button on https://github.com/simon-weber/gmusicapi/blob/develop/gmusicapi/session.py.

**Comment by siebert** [comment]
Did as requested. The question is, did google roll out this change for everyone at once or do we have to support both the old and the new login forms?

**Comment by simon-weber** [comment]
Yeah, good question. I suppose we'll find it when/if it breaks for other folks, haha.

**Comment by simon-weber** [comment]
Fixed by #421.

**Comment by jaymoulin** [comment]
This seems to be happening again. Will this be fixed even if doc state this as **not well suported**?

**Comment by simon-weber** [comment]
I'm not personally going to work on it, but if someone makes a fix I'll consider merging it.
