### ISSUE TITLE
Docs/code style pass

### ISSUE THREAD

**Issue by thebigmunch** [simon-weber/gmusicapi#439]
While working on some big Mobileclient changes from another issue recently, I was struck by some of the things I found in docstrings. Mainly, punctuation, capitalization, and the lack of consistency. I'd like to make an editing pass on the docs for these things. Along with that, I could make the Google Music -> Google Play Music transition we spoke about regarding SEO.

As for code style, I'd like to propose some modifications based on some things, it turns out, I have in common with [Kenneth Reitz](https://requests.readthedocs.org/en/master/dev/contributing/#kenneth-reitz-s-code-style). Also the organization of class methods isn't  ideal. So, I'd like to propose:
- Line length. I have always felt having a strict, arbitrary line length limit to be quite strange. In Kenneth's words, exceeding the set limit is fine `when doing otherwise would be terribly inconvenient`. I find this a bit vague and not so correct. I prefer `when doing otherwise would hurt readability/understandabillity of the code`. For a simple example, take the recent update of the requests versions in setup.py: the original PR had it on a single line (clearly more readable than line continuation with parentheses) that couldn't be merged because it was slightly over the line length limit. There are situations in actual code where breaking a line hurts readability/understandabillity often magnified when dealing with multiple indentation levels. It should be easy to look at code and make a subjective judgement on its readability/understandabillity. I propose allowing for encouraging 100 character line length limit while adding the possibility of longer lines in the same way as in requests.
- Continuation style. I wholeheartedly agree with Kenneth's statement about that specific form of line continuation. Adding to that, I believe it hurts both the writing and reading of continuations. I was reminded of this when dealing a lot with the schemas which are written in this form. However, the example responses in the docstrings are written in a much better form that is easier to read and write. I propose to disallow that form, or at least encourage the use of and change the schemas and other code to use the better form as in the docstrings.
- Class method organization. Honestly, they're mostly organized logically, but there are some oddities like `Mobileclient._get_all_items(_incremental)` being almost the last methods defined when they're used in many of the other methods. I'd like to reorganize the methods in the class instances to something like:

```
__magic__ 
_private
@properties
@class/staticmethods
methods (arranged logically in the same way as the docs, which they already mostly are)
```

I've gotten on this kind of meta kick for my own stuff lately, so I figured I'd see what you think about it for gmusicapi. I'm pretty sure the docs stuff is no big deal; it's just basic language editing. But the code style stuff could be more controversial. As always, let me know what you think.

**Comment by simon-weber** [comment]
I'm fine with pretty much all of this.

The only part I disagree with: I'm neutral on opening-delimiter-alignment, so at least as of now I wouldn't agree with disallowing it. I'm curious to know Kenneth's reasoning behind disliking that alignment so much (maybe I'm just tasteless!).

**Comment by thebigmunch** [comment]
The small examples in the PEP tend to hide some of the issues.

I wouldn't push disallowing it, but I definitely take issue with its readability. It's often more difficult to find what opening delimiters a closing delimiter belongs to, especially for people less experienced in reading Python. And its ease of writing can be a problem, especially if your editor doesn't handle it intelligently. You also end up being between indentation levels a lot of times, which is one of the things editors can make interesting for you.

For example:
``` python
sj_image_color_styles = {
    'type': 'object',
    'additionalProperties': False,
    'properties': {
        'primary': {'type': 'object',
                    'additionalProperties': False,
                    'properties': {
                        'red': {'type': 'integer'},
                        'green': {'type': 'integer'},
                        'blue': {'type': 'integer'}
                    }},
        'scrim': {'type': 'object',
                  'additionalProperties': False,
                  'properties': {
                      'red': {'type': 'integer'},
                      'green': {'type': 'integer'},
                      'blue': {'type': 'integer'}
                  }},
        'accent': {'type': 'object',
                   'additionalProperties': False,
                   'properties': {
                       'red': {'type': 'integer'},
                       'green': {'type': 'integer'},
                       'blue': {'type': 'integer'}
                   }}
    }
}
```
vs
``` python
sj_image_color_styles = {
    'type': 'object',
    'additionalProperties': False,
    'properties': {
        'primary': {
            'type': 'object',
            'additionalProperties': False,
            'properties': {
                'red': {'type': 'integer'},
                'green': {'type': 'integer'},
                'blue': {'type': 'integer'}
            }
        },
        'scrim': {
            'type': 'object',
            'additionalProperties': False,
            'properties': {
                'red': {'type': 'integer'},
                'green': {'type': 'integer'},
                'blue': {'type': 'integer'}
            }
        },
        'accent': {
            'type': 'object',
            'additionalProperties': False,
            'properties': {
                'red': {'type': 'integer'},
                'green': {'type': 'integer'},
                'blue': {'type': 'integer'}
            }
        }
    }
}
```

Both are perfectly valid as far as PEP8 is concerned. But the 2nd is a bit easier to discern opening/closing partnerships. And, subjectively, the 2nd one looks less cluttered and is easier to read due to less horizontal size. And a side-benefit of the 2nd being slightly more vertical is that the line length is kept down due to fewer indentation levels.

Just pointing out again, that you used the 2nd form in docstrings to demonstrate returns. Whether conscious of it or not, I assume it was because it's easier to read/understand, especially for the less experienced/knowledgeable who might be reading those docstrings vs reading the code.

**Comment by simon-weber** [comment]
Got it; makes sense. I'm probably just more used to the first style than most people (and my editor makes indenting that way easy). I don't have strong feelings towards either one; it's good to know that some people do.

> you used the 2nd form in docstrings to demonstrate returns

haha, the reason for that is I was using a javascript beautifier to format the json-as-python dicts. It was an easy way to introduce newlines consistently (my editor usually only introduces leading whitespace when I autoindent). I guess I got lucky!
