### ISSUE TITLE
Unified song model

### ISSUE THREAD

**Issue by thebigmunch** [simon-weber/gmusicapi#443]
As brought up in the past (#237 and others), song metadata keys vary between the client APIs. I've been playing around with it for a long time. I've even had something cooked up for a bit that would facilitate the unification of them in a backward-compatible way in the form of a mapping subclass that stores values by original keys and arbitrarily transformed/normalized keys. Now that I've finally got time/energy/motivation to get a bunch of stuff done, it's probably time to get this going.

The main question is, what format do we want the keys to take? Despite me hating lowerCamelCase with the fury of a thousand suns, it'd probably be best to use it to match the other Mobileclient (and Webclient) call response keys. The other options would be to use lower_underscore (Musicmanager/Python) or lowercase (Mutagen). But, to keep consistency between all the call response keys, using one of those would probably require using that format for all response call keys.  I'm not sure having different formats for songs vs the rest would be a good idea, since that's the kinda inconsistency we're trying to solve here.

**Comment by simon-weber** [comment]
Yeah, I think my preference would be to map other clients onto the most commonly used client (probably mobileclient?). That way, new mobileclient keys will make sense in the time period before we add them to the mapping, and minimize the additional logic we're adding (at least by usage, not necessarily in terms of keys changed).
