### ISSUE TITLE
Language/tier URL parameters

### ISSUE THREAD

**Issue by thebigmunch** [simon-weber/gmusicapi#444]
As we've found out, the tier parameter doesn't seem to have any real effect. And, until I was poking at #377, I thought the language (hl) parameter was the same. But, it seems it's actually required to get situations.

We can obviously get the tier now. Should we be setting this in calls automatically?

The language is a result of what we send during authentication. On an actual Android device, the language/country would be available to send without user intervention, but that doesn't seem like an option for gmusicapi. Is this something we'd want to give users the option of setting while defaulting to en_us as is the case upstream? Or just default all the calls to en_us?

**Comment by simon-weber** [comment]
Have you noticed any differences in responses when setting the locale? I'd be fine with just sending en_us if we can't figure out a reason to send a different one.

**Comment by thebigmunch** [comment]
I'll have to look again at the situations returned to see if they're different, but, when I set language to es_es, the titles and descriptions were, at a glance, all in Spanish.

**Comment by simon-weber** [comment]
Ah, makes sense. Yeah, makes sense to expose it then if it's not too difficult (with defaulting to either en_us, or the user's locale if google gives it to us).

**Comment by thebigmunch** [comment]
@simon-weber: Can you think of a good, clean way to automatically apply these to every call? Nothing screamed at me while I was skimming and pondering it earlier.

**Comment by simon-weber** [comment]
The best thing I can think of is setting params on the underlying requests.Session. I'm pretty sure that will attach them to every request made.

**Comment by thebigmunch** [comment]
Yeah, that's what I had thought as well. Just making sure we were of the same mind before jumping in on it.

As an aside, I believe I know why the ``listennow/situations`` endpoint requires the locale. The situations themselves don't have their name/description localized. But the endpoint returns the entire situations block on the Listen Now page as a dict including the header/subheader (i.e. [this](https://waa.ai/kf5q)) which are localized. The other calls we've dealt with so far simply haven't had anything that is localized.

**Comment by simon-weber** [comment]
Ah, makes sense.
