### ISSUE TITLE
investigate "use your phone to sign in"

### ISSUE THREAD

**Issue by virtualdxs** [simon-weber/gmusicapi#449]
Google lets you log in by accepting a login on your phone. When this sends the request, the phone asks for approval but the function has already returned and failed. Note that this will require being able to show the user a few digits without breaking program flow.

**Comment by simon-weber** [comment]
Are you referring to http://techcrunch.com/2015/12/22/google-begins-testing-password-free-logins?

**Comment by virtualdxs** [comment]
Yeah, that's it.

**Comment by virtualdxs** [comment]
Looking into it a little, all you should need to do to check is grep for "Use your password instead", and if it exists,follow the link, otherwise you're on the standard password page.

**Comment by virtualdxs** [comment]
form_candidates = response.soup.select("form")
        if len(form_candidates) > 1:
            log.error("Google login form dom has changed; there are %s candidate forms:\n%s",
                      len(form_candidates), form_candidates)
            return False

        # Begin Pseudocode
       passwordLoginSubmit = grep('<input id="skipChallenge"')
       if not empty passwordLoginSubmit then submitFormSurrounding(passwordLoginSubmit)
       # End Pseudocode (we're now on a password page)

        form = form_candidates[0]
        form.select("#Passwd")[0]['value'] = password

The surrounding form looks something like this:

`<form method="POST" action="/signin/challenge/skip"><input name="challengeId" type="hidden" value="1"><input type="hidden" name="gxf" id="gxf" value="AFoagUUbTkVYqfpR1T3IOWwhc53j9VFirA:1459732283910"><input id="skipChallenge" type="submit" jsname="rwR6T" class="g1C42c" value="Use your password instead"></form>`

Note that the best solution would be to figure out how to integrate with it rather than just bypass it, but at least it'll work for users who have this enabled.

**Comment by virtualdxs** [comment]
That's in session.py btw
