### ISSUE TITLE
Code 500 - Internal error when deleting a large number of files

### ISSUE THREAD

**Issue by jorti** [simon-weber/gmusicapi#463]
I'm getting this error while executing delete_songs on +6000 songs. I'm running this script:
https://github.com/maxkirchoff/google-music-dupe-killer

```
(response was: u'{\n "error": {\n  "errors": [\n   {\n    "domain": "global",\n    "reason": "internalError",\n    "message": "Internal Error"\n   }\n  ],\n  "code": 500,\n  "message": "Internal Error"\n }\n}\n')
```

**Comment by simon-weber** [comment]
This one's probably on Google's end. Their backend often doesn't handle big changes well. Try making a few smaller requests, maybe chunks of 1k tracks.

**Comment by jorti** [comment]
A quick test iterating the songs one by one successfully deleted all of them.

Thank you.

**Comment by simon-weber** [comment]
Sure thing!
