### ISSUE TITLE
ImportError: cannot import name raise_from

### ISSUE THREAD

**Issue by URDaddyOh** [simon-weber/gmusicapi#464]
Getting an import error on the from gmusicapi line

Mac OS X 10.10.5

Fresh install of gmusicapi using latest version of pip

```
python --version
Python 2.7.10
```

The code
```
import sys
from gmusicapi import Mobileclient

api = Mobileclient()
logged_in = api.login('myaccount@gmail.com', 'mypassword')
```

The Traceback reported
```
Traceback (most recent call last):
  File "getMyMusic.py", line 3, in <module>
    from gmusicapi import Mobileclient
  File "/Library/Python/2.7/site-packages/gmusicapi/__init__.py", line 4, in <module>
    from gmusicapi.clients import Webclient, Musicmanager, Mobileclient
  File "/Library/Python/2.7/site-packages/gmusicapi/clients/__init__.py", line 2, in <module>
    from gmusicapi.clients.webclient import Webclient
  File "/Library/Python/2.7/site-packages/gmusicapi/clients/webclient.py", line 11, in <module>
    from gmusicapi.protocol import webclient
  File "/Library/Python/2.7/site-packages/gmusicapi/protocol/webclient.py", line 6, in <module>
    from six import raise_from
ImportError: cannot import name raise_from
```

Thanks

**Comment by URDaddyOh** [comment]
The import works in the develop branch.

**Comment by simon-weber** [comment]
Huh. Develop isn't ahead by any meaningful changes: https://github.com/simon-weber/gmusicapi/compare/6b08261...7c5b5db.

Was there anything different about the installations were run?

**Comment by URDaddyOh** [comment]
I used pip to install the one that failed. Used python setup.py install for the develop branch.  Got a version error on rasyn1 (I think that was the library) so I used pip to uninstall and pip install to get the later version and reinstalled develop.

That is what worked. For now I can use this branch. I will not be done developing program for a few weeks probably.

**Comment by simon-weber** [comment]
Ok; glad it's working. If you run into problems again, I'd recommend trying the install inside a virtualenv. That'll rule out anything odd about your system install.

**Comment by URDaddyOh** [comment]
My pyasn1 library was corrupt. In my IDE I have a virtualenv setup and the master build did not work till I uninstalled and reinstalled pyasn1 0.1.9. I am marking this closed. Thanks for the great work on this package.

**Comment by simon-weber** [comment]
Sure thing! Glad we got it figured out.
