### ISSUE TITLE
Webclient Login Failing

### ISSUE THREAD

**Issue by dantespe** [simon-weber/gmusicapi#466]
I can't seem to get login with webclient. I am 100% that my password and username are right. Is anyone else having the same issues?

**Comment by dantespe** [comment]
Also, if we have two-step verification turned on and app specific passwords are not supported then how would two-step users be able to login using Webclient?

**Comment by simon-weber** [comment]
2fa via app-specific passwords isn't supported for the webclient, but is for the mobileclient. I'd suggest the mobileclient interface regardless (there's a quick overview of why [here](http://unofficial-google-music-api.readthedocs.io/en/latest/reference/api.html)).

Let me know if switching to the mobileclient works for you.
