### ISSUE TITLE
Feature Request: Get what's currently playing on a given device

### ISSUE THREAD

**Issue by TimeHorse** [simon-weber/gmusicapi#469]
Is it possible in the Mobileclient.get_registered_devices() to add a reference to the song currently playing on the given device, if any?  I really want to make a tool that periodically queries Google Music to see which device was most recently accessed and if it's playing a song that it was not playing the last time it checked, then broadcast that track to a special Twitter account I have set up to log what I'm currently listening to.

**Comment by simon-weber** [comment]
Unfortunately, I don't think Googles exposes this data to us, since most of the client state is kept offline.

They do have some way to detect when a device is streaming (to power the "you can only stream from one device at a time" restriction), but I don't think we currently support retrieving even that.

**Comment by TimeHorse** [comment]
Thank you Simon!  I think then it may be best to consider a JS injection approach directly into the web at least when playback isn't via an App, which could cover some cases at least.

**Comment by simon-weber** [comment]
For that specific use case, you might be better off with a chrome extension that scrapes the dom and sends it to twitter clientside.

We used to have more scraping in gmusicapi, but it was such a pain to maintain that as it broke, we've tended to remove rather than replace it, haha.

**Comment by thebigmunch** [comment]
Through all the poking I've done over the years, there's an endpoint that I haven't looked further into: ``activity/recordrealtime``. This likely isn't useful here, but it's possible there are other endpoints under ``activity`` that may do different things. It seems to me that would be a place to start looking if you wanted to poke around. I haven't run into anything else yet that seems promising.

**Comment by TimeHorse** [comment]
Do you have a link to the activity/recordrealtime API?  I can't find it in the list of Activities.

**Comment by soshial** [comment]
Any update on this matter?

**Comment by simon-weber** [comment]
Sorry, no updates. I wouldn't get your hopes up: unless Google unexpectedly makes a change to support this - or we find a hidden api - it's not something that'll land in gmusicapi.

The chrome extension approach mentioned earlier could be an alternative for people who primarily use the web client.
