### ISSUE TITLE
update docs to clarify streaming call abilities (musicmanager/webclient 404)

### ISSUE THREAD

**Issue by mitchmindtree** [simon-weber/gmusicapi#472]
When attempting to call `music_manager.download_song(song_id)` I'm getting the following exception:

```
GetDownloadLink: 404 Client Error: Not Found for url: https://music.google.com/music/export?songid=20f89b83-8021-3f22-af05-02ce6d5f601a&version=2
(requests kwargs: {u'url': u'https://music.google.com/music/export', u'headers': {u'X-Device-ID': u'B8:F6:B1:13:7D:3E', u'Authorization': u'<omitted>'}, u'params': {u'songid': u'20f89b83-8021-3f22-af05-02ce6d5f601a', u'version': 2}, u'method': u'GET'})
(response was: u'<HTML>\n<HEAD>\n<TITLE>Not Found</TITLE>\n</HEAD>\n<BODY BGCOLOR="#FFFFFF" TEXT="#000000">\n<H1>Not Found</H1>\n<H2>Error 404</H2>\n</BODY>\n</HTML>\n')
```

I first did the `Musicmanager.perform_oauth` step which finished with "succeeded".

I then wrote a script to test the `download_song` method as follows:

```python
#!usr/bin/env python3

import time
import gmusicapi

def main():

    # Create the APIs.
    music_manager = gmusicapi.Musicmanager()
    mobile_client = gmusicapi.Mobileclient()

    # Log in.
    music_manager_logged_in = music_manager.login()
    if music_manager_logged_in:
        print("Musicmanager login succeeded")
    else:
        print("Musicmanager login failed")
        return
    mobile_client_logged_in = mobile_client.login(user, password, gmusicapi.Mobileclient.FROM_MAC_ADDRESS)
    if mobile_client_logged_in:
        print("Mobileclient login succeeded")
    else:
        print("Mobileclient login failed")
        return
    
    all_songs_generator = mobile_client.get_all_songs(incremental=True)
    for song_list in all_songs_generator:
        for song in song_list:
            song_id = song['id']

            # This is where the exception occurs.
            filename, audio = music_manager.download_song(song_id)

            time.sleep(1)

if __name__ == "__main__":
    main() 
```

If I ignore the exception and continue to loop, the same exception is raised each iteration, so it doesn't seem to be song-specific.

`pip` lists `gmusicapi` as version `10.0.1`

Perhaps the URL might have changed from `https://music.google.com/music/export` to something else?

Any ideas on what might be going on here would be appreciated 😸

**Comment by simon-weber** [comment]
Can you try with http://unofficial-google-music-api.readthedocs.io/en/latest/reference/musicmanager.html#gmusicapi.clients.Musicmanager.get_uploaded_songs instead of mobileclient.get_all_songs? I'm wondering if the musicmanager will 404 if given an All Access track that's been added to the library (rather than an uploaded track).

**Comment by mitchmindtree** [comment]
It seems you're right - when replacing `mobile_client.get_all_songs` with `music_manager.get_uploaded_songs` the `music_manager.download_song` method works without issues. Is this expected behaviour? Or perhaps the result of a recent change to the google music protocol?

**Comment by simon-weber** [comment]
I think this is expected, though I've never actually tried Google's music manager with my subscription test account. I think Google's music manager would download your uploaded and purchased tracks, but not anything from your subscription.

Seems like we should update the docs!

**Comment by mitchmindtree** [comment]
I seem to be getting the same behaviour when attempting to use `Webclient.get_stream_audio` or `Webclient.get_stream_urls` - both respond with 404.

**Comment by simon-weber** [comment]
Hm. What about the mobileclient? The webclient isn't as well tested, so it might just be broken in some unrelated way.

Also, can you give an example of the kind of id you're using?

**Comment by mitchmindtree** [comment]
I just tried `mobile_client.get_stream_url` and it seems to work fine with the ``id``s retrieved from the `get_all_songs` `song` dictionaries 👍

**Comment by mitchmindtree** [comment]
I'll leave this open for you to close in case you'd like to wait until the docs are adjusted.

**Comment by simon-weber** [comment]
Sounds good. Glad you got it working!
