### ISSUE TITLE
`Mobileclient`'s `get_stream_url` method raising a `CallFailure` - `403 Client Error: Forbidden url`

### ISSUE THREAD

**Issue by mitchmindtree** [simon-weber/gmusicapi#473]
```
GetStreamUrl: 403 Client Error: Forbidden for url: https://android.clients.google.com/music/mplay?opt=hi&songid=23386570-e3eb-35bd-bf49-de6c14c3ccef&pt=e&slt=1467761137913&sig=g8Yjyye5mf2VoCpPUIlO3FPc1cQ&hl=en_US&tier=aa&net=mob
(requests kwargs: {u'url': u'https://android.clients.google.com/music/mplay', u'headers': {u'X-Device-ID': u'B8F6B1137D3D', u'Authorization': u'<omitted>'}, u'allow_redirects': False, u'params': {u'opt': u'hi', u'songid': u'23386570-e3eb-35bd-bf49-de6c14c3ccef', u'pt': u'
e', u'slt': '1467761137913', u'sig': 'g8Yjyye5mf2VoCpPUIlO3FPc1cQ', u'hl': u'en_US', u'tier': u'aa', u'net': u'mob'}, u'method': u'GET'})
(response was: u'<HTML>\n<HEAD>\n<TITLE>Forbidden</TITLE>\n</HEAD>\n<BODY BGCOLOR="#FFFFFF" TEXT="#000000">\n<H1>Forbidden</H1>\n<H2>Error 403</H2>\n</BODY>\n</HTML>\n')
```

The song `id`s I'm using are yielded by the generators yielded by `mobile_client.get_all_songs(incremental=True)`.

Curiously, this only occurs for some songs and not others. For example, ~100 songs might consecutively fail with this exception, and then another 4 will work without issues. If I run the script again, the same songs always behave the same way.

This might not be noteworthy, but I also thought it was curious that these exception-prone songs are all deep into the `get_all_songs` list (i.e. ~6000 will work without issues, and then suddenly 95% of the remaining songs will raise this exception).

**Comment by mitchmindtree** [comment]
I just tested a different `android_id` to the `Mobileclient.login` arguments and the behaviour was the same as above.

**Comment by simon-weber** [comment]
Huh, not sure. Usually this is an all-or-nothing kind of error caused by bad credentials.

Do you have both working and non-working examples of both uploaded and AA tracks? Maybe that's the difference that's causing problems.

**Comment by tjstum** [comment]
I am going to leave a half useful comment in the helps it might debug.

I think I've seen something similar where I would get 403s for some calls to `get_stream_url` for IDs that I had retrieved from getting an entire playlist's worth. When I briefly looked, the metadata was also unavailable for the result, so it seemed to me at the time that they were songs that had been removed from All-Access or something, but they still appeared in the playlist.

I'm sorry I don't have any more information right now, but maybe that helps?

**Comment by PostsDesert** [comment]
I'm getting this same error when trying to play a song from a playlist. I'm able to play the song when I get it the search function.
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/gmusicapi/protocol/shared.py", line 218, in perform
    response.raise_for_status()
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 893, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://mclients.googleapis.com/music/mplay?slt=1482961447150&net=mob&tier=aa&songid=2t5wtfhm77s7trojjzdt3gujpy&pt=e&sig=MOlWF5dNGUexplZxRkAfqlRvE0g&hl=en_US&dv=0&opt=hi

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "song.py", line 165, in <module>
    playlists = api.get_stream_url('2t5wtfhm77s7trojjzdt3gujpy', quality=u'hi')
  File "<decorator-gen-102>", line 2, in get_stream_url
  File "/usr/local/lib/python3.5/dist-packages/gmusicapi/utils/utils.py", line 293, in wrapper
    return function(*args, **kw)
  File "/usr/local/lib/python3.5/dist-packages/gmusicapi/clients/mobileclient.py", line 372, in get_stream_url
    return self._make_call(mobileclient.GetStreamUrl, song_id, device_id, quality)
  File "/usr/local/lib/python3.5/dist-packages/gmusicapi/clients/shared.py", line 84, in _make_call
    return protocol.perform(self.session, self.validate, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/gmusicapi/protocol/shared.py", line 226, in perform
    raise CallFailure(err_msg, call_name)
gmusicapi.exceptions.CallFailure: GetStreamUrl: 404 Client Error: Not Found for url: https://mclients.googleapis.com/music/mplay?slt=1482961447150&net=mob&tier=aa&songid=2t5wtfhm77s7trojjzdt3gujpy&pt=e&sig=MOlWF5dNGUexplZxRkAfqlRvE0g&hl=en_US&dv=0&opt=hi
(requests kwargs: {'method': 'GET', 'allow_redirects': False, 'url': 'https://mclients.googleapis.com/music/mplay', 'headers': {'X-Device-ID': 'D4BED9E0376A', 'Authorization': '<omitted>'}, 'params': {'slt': '1482961447150', 'net': 'mob', 'tier': 'aa', 'songid': '2t5wtfhm77s7trojjzdt3gujpy', 'pt': 'e', 'sig': b'MOlWF5dNGUexplZxRkAfqlRvE0g', 'hl': 'en_US', 'dv': 0, 'opt': 'hi'}})
(response was: '<HTML>\n<HEAD>\n<TITLE>Not Found</TITLE>\n</HEAD>\n<BODY BGCOLOR="#FFFFFF" TEXT="#000000">\n<H1>Not Found</H1>\n<H2>Error 404</H2>\n</BODY>\n</HTML>\n')
```

**Comment by PostsDesert** [comment]
So on farther review this seems to be caused by using the `nid`. When I use the `storeId` instead it works perfectly fine. Does anyone know the difference between the two?

**Comment by simon-weber** [comment]
I only know that the nid stands for "nautilus id", where nautilus is the code name for their music database (which may contain songs outside the store). Google's ids have an odd history of changing unexpectedly (eg https://github.com/simon-weber/gmusicapi/issues/517 or tjstum's comment earlier), which sounds like what happened here.
