### ISSUE TITLE
Streaming Fails due to the one minute cap

### ISSUE THREAD

**Issue by SimonCadge** [simon-weber/gmusicapi#477]
I have made use of the api to create a locally hosted web app for my class. It's not very good I know, but it works.
That being said, while streaming the songs, the stream will fail after about 1:30 or 2:00. I understand that the stream url is only valid for one minute, so I wonder whether there is any way to play the whole song?

I am using the link as the source for a html5 audio element, but I've tried using XMLHttpRequests and then using the cached version, but I'm not allowed, with the error message saying:

"XMLHttpRequest cannot load https://r8---sn-8pgbpohxqp5-auos.c.doc-0-0-sj.sj.googleusercontent.com/vide…&amp;mn=sn-8pgbpohxqp5-auos&amp;ms=au&amp;mt=1470395199&amp;mv=m&amp;pl=24. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://192.168.1.75:5000' is therefore not allowed access. The response had HTTP status code 403."

I believe it must be possible, as people have used this api for similar things before. Any help would be greatly appreciated, as I'm so tantalysingly close to having it work. If this is the wrong place to ask, please could you point me to where is correct.

**Comment by simon-weber** [comment]
I think the usual approach is to have the backend cache the song before passing it off to the frontend. Then, the frontend can stream eg from disk or a data url without worrying about the timeout.

**Comment by SimonCadge** [comment]
This is what I'm attempting with the XMLHttpRequest, but apparently this doesn't work. I was just wondering whether you have an idea of how I might go about implementing that using javascript or flask or jinja2 or something simmilar.

**Comment by simon-weber** [comment]
I'm suggesting downloading the track in python, which isn't subject to same-origin restrictions like in-browser javascript is. Here's an example of how a django proxy does it: https://github.com/malept/gmusicprocurator/blob/e9f6d0d9d288f5b54e264f67a6658eda7c269a8e/gmusicprocurator/views/proxy.py#L183.

**Comment by ceberous** [comment]
so how does one save a Flask Response to file ? or forward the response to mPlayer?

**Comment by SimonCadge** [comment]
Thank you very much, I have successfully implemented this into my project. 
I honestly didn't think I would ever have it working, so your help is greatly appreciated.

**Comment by simon-weber** [comment]
Glad everyone got it working!
