### ISSUE TITLE
maximum value for max_results not documented

### ISSUE THREAD

**Issue by mjg59** [simon-weber/gmusicapi#479]
If I do a Mobileclient.search("test", max_results=20000) I only receive 10 entries in song_hits. Doing the same with the mobile app lists 5 hits plus a "98 more" marker.

**Comment by simon-weber** [comment]
I seem to remember something about a max value for max_results. Can you try with, say, 100 and see if you do get 100 results?

**Comment by mjg59** [comment]
Ah! Yes, using 100 gives me much better results. 200 goes back to 10. Ok, seems like a documentation issue at worst.

**Comment by simon-weber** [comment]
Ah, ok. Sorry for the confusion; I'll leave this open as a documentation problem.
