### ISSUE TITLE
error on get_all_stations

### ISSUE THREAD

**Issue by diraimondo** [simon-weber/gmusicapi#485]
Today in gmusicproxy I've found that the method get_all_stations of gmusicapi (9.0.0) raises an error:

```
  File "./GMusicProxy", line 251, in <lambda>
    stations = self._robust_retry(lambda:api.get_all_stations())
  File "/home/mario/.virtualenvs/gmusicproxy/local/lib/python2.7/site-packages/gmusicapi/clients/mobileclient.py", line 760, in get_all_stations
    updated_after=updated_after)
  File "/home/mario/.virtualenvs/gmusicproxy/local/lib/python2.7/site-packages/gmusicapi/clients/mobileclient.py", line 1069, in _get_all_items
    return [s for chunk in generator for s in chunk]
  File "/home/mario/.virtualenvs/gmusicproxy/local/lib/python2.7/site-packages/gmusicapi/clients/mobileclient.py", line 1082, in _get_all_items_incremental
    **kwargs)
  File "/home/mario/.virtualenvs/gmusicproxy/local/lib/python2.7/site-packages/gmusicapi/clients/shared.py", line 83, in _make_call
    return protocol.perform(self.session, self.validate, *args, **kwargs)
  File "/home/mario/.virtualenvs/gmusicproxy/local/lib/python2.7/site-packages/gmusicapi/protocol/shared.py", line 227, in perform
    raise CallFailure(err_msg, call_name)
CallFailure: ListStations: 500 Server Error: Internal Server Error
(requests kwargs: {u'url': u'https://mclients.googleapis.com/sj/v1.11/radio/station', u'headers': {u'Content-Type': u'application/json', u'Authorization': u'<omitted>'}, u'data': '{"max-results": "20000"}', u'method': u'POST', u'params': {u'alt': u'json', u'updated-min': 0, u'include-tracks': u'true'}})
(response was: '{\n "error": {\n  "errors": [\n   {\n    "domain": "global",\n    "reason": "internalError",\n    "message": "Internal Error"\n   }\n  ],\n  "code": 500,\n  "me
ssage": "Internal Error"\n }\n}\n')
```

**Comment by simon-weber** [comment]
These 500s are often temporary. Are you still seeing the problem now?

**Comment by diraimondo** [comment]
I can use the other gmusicproxy methods, like get_collection or even get_song, but get_all_stations regularly raises error. I guess it is working for you.

**Comment by simon-weber** [comment]
I haven't tried it manually, but there haven't been any test failures.

**Comment by thebigmunch** [comment]
I tried it on 2 accounts. Successful on both.

**Comment by diraimondo** [comment]
It looks that BubbleUPnP had a similar problem with stations few weeks ago: http://forum.xda-developers.com/showpost.php?p=68106096&postcount=11314
They recently released version 2.7.4 with this changelog: "fixed failure to load Google Music Stations folder".
The problem looks related to the state of the account. I got just few stations selected from the pool. I renamed them: maybe this is related.

**Comment by kirkaholic** [comment]
I'm having the same error in the same call (CallFailure: ListStations: 500 Server Error: Internal Server Error).

**Comment by kirkaholic** [comment]
Definitely an issue with something in my account. Switched account to one with only a handful of radios and it works.

**Comment by diraimondo** [comment]
@simon-weber , is there any way to report useful information to fix this issue. It is clearly related to the actual state of the account. I could remove all stations list and it could fix the problem but this would not improve the gmusicapi/gmusicproxy support for their users.

**Comment by rsteckler** [comment]
Same issue here.  I removed all of the radio stations from my account and it still 500s.  I then added just one and same 500 error. 

If there's anything I can do to help debug, I'm happy to do it.  

Some things that may be related:
I'm using a OTP for google.
I tried without a device id and by spoofing my phone's ID without a difference.

**Comment by simon-weber** [comment]
Are you noticing problems loading other items like playlists or playlist contents? I'm wondering if this is load-related (like https://github.com/simon-weber/Autoplaylists-for-Google-Music/issues/104) and would be improved by the change suggested in https://github.com/simon-weber/gmusicapi/issues/513.

**Comment by diraimondo** [comment]
I usually don't use playlists but I tried to subscribe a couple of playlists in my account. The method `get_all_playlists` correctly reports the name and urls of them. When I try to stream one of them, gmusicproxy reports 'playlist not found', the debug output (with some messages from gmusicapi) is:

```
request path: /get_playlist?id=14b8a041-1da5-4e95-8334-2b73ec54576d
192.168.200.201 - - [25/Nov/2016 21:06:31] "GET /get_playlist?id=14b8a041-1da5-4e95-8334-2b73ec54576d HTTP/1.1" 200 -
Getting tracks from playlist with id '14b8a041-1da5-4e95-8334-2b73ec54576d'
ListPlaylists(args=[], kwargs={'start_token': None, u'max_results': 20000})
{u'kind': u'sj#playlistList', u'data': {u'items': [u'<3 playlists>']}}
ListPlaylistEntries(args=[], kwargs={'start_token': None, u'max_results': 20000, 'updated_after': None})
{u'kind': u'sj#playlistEntryList', u'data': {u'items': [u'<0 plentries>']}}
[]
ListTracks(args=[], kwargs={'start_token': None, u'max_results': 20000})
{u'kind': u'sj#trackList', u'data': {u'items': [u'<128 tracks>']}}
generated playlist:
#EXTM3U
Playlist not found!
```
It doesn't work but it's not a 500 error.

**Comment by diraimondo** [comment]
I feel stupid: switching on a recent release of gmusicapi fixed the problem... 

Sorry for the noise.

**Comment by simon-weber** [comment]
No worries! Glad we got it figured out.
