### ISSUE TITLE
Option to cache login credentials and re-auth after auth expires

### ISSUE THREAD

**Issue by askvictor** [simon-weber/gmusicapi#486]
The application I'm using this library with stops working after a few days, this appears to be due to the authentication token expiring. While I could wrap every call to this API to check if an 'unauthorised' response was received, it would be cleaner for the API to handle this itself. I propose that if a call fails in this way, that a re-auth is attempted. It would, however, require saving the username and password in memory, so I'd say an option argument to the login method to allow credentials to be stored for this purpose. 

Thoughts?

**Comment by simon-weber** [comment]
Caching plaintext credentials makes me pretty nervous. Since the musicmanager and mobileclient both use OAuth, though, they've got refresh/master tokens which should be fine to cache either in or out of process.

**Comment by askvictor** [comment]
While I'm similarly nervous about the idea of storing the password, I think the reality of any service that uses this library will likely store the credentials somewhere (on disk or DB) anyway, so it's just a matter of buck-passing. Having it optional would allow the application developer to make that decision.

Using the refresh token would be somewhat more secure, but beyond my abilities to deal with.

**Comment by simon-weber** [comment]
Yeah, I hear ya. Auth in general is pretty frustrating with the current apis. https://github.com/simon-weber/gmusicapi/issues/290#issuecomment-149918614 is the only thing I'm aware of that could really change the landscape.

**Comment by simon-weber** [comment]
I'm working on proper OAuth support over in https://github.com/simon-weber/gmusicapi/issues/620#issuecomment-439731287, which will eventually become the only supported auth method for the mobileclient. It'll also fix this (since it mirrors the Musicmanager's two-step interface).

**Comment by simon-weber** [comment]
That's out now in 11.1.0: see [the docs](https://unofficial-google-music-api.readthedocs.io/en/latest/reference/mobileclient.html#gmusicapi.clients.Mobileclient.perform_oauth) for details.
