### ISSUE TITLE
mc.get_all_user_playlist_contents slow for large histories

### ISSUE THREAD

**Issue by JVMed** [simon-weber/gmusicapi#503]
I have a couple of playlists that update every day and I sync them by simply retrieving all my playlist contents, deleting all tracks in a playlist and adding the new track list to the playlist. However when I retrieve my playlist tracks with a custom `Mobileclient.get_all_user_playlist_contents()`, the number of "deleted" tracks it downloads increases with every playlist sync, as expected. 

This syncing method has been working fine for the last 6 months but now after my custom `Mobileclient.get_all_user_playlist_contents()` downloads about one hundred 1000-track batches, the next incremental batch results in following error:

```python
....
File ".../lib/gmusicapi/clients/shared.py", line 84, in _make_call
    return protocol.perform(self.session, self.validate, *args, **kwargs)
  File ".../lib/gmusicapi/protocol/shared.py", line 228, in perform
    raise CallFailure(err_msg, call_name)
CallFailure: ListPlaylistEntries: 500 Server Error: Internal Server Error
(requests kwargs: {u'url': u'https://mclients.googleapis.com/sj/v2.4/plentryfeed', u'headers': {u'Content-Type': u'application/json', u'Authorization': u'<omitted>'}, u'data': '{"max-results": "1000", "start-token": "xxx..."}', u'method': u'POST', u'params': {u'tier': u'fr', u'alt': u'json', u'updated-min': 0, u'hl': u'en_US', u'include-tracks': u'true'}})
(response was: u'{\n "error": {\n  "errors": [\n   {\n    "domain": "global",\n    "reason": "backendError",\n    "message": "Backend Error"\n   }\n  ],\n  "code": 500,\n  "message": "Backend Error"\n }\n}\n')
```

I think the cause is the number of "deleted" tracks GPM has stored has grown too much and is causing some error. Is there a way to permanently delete "deleted" tracks? The "Delete recommendation history" option on the web does not appear to do much and have not tried "Delete My Library".

**Comment by simon-weber** [comment]
Huh, I'm not sure. Probably there's a param for it that we just didn't notice.

**Comment by JVMed** [comment]
I'm curious if it is just my account. When I run this...

```python
from gmusicapi import Mobileclient
import logging

logging.info("logging in")

api = Mobileclient(debug_logging=True)
api.login('user@gmail.com', 'password', Mobileclient.FROM_MAC_ADDRESS)

logging.info("getting playlist tracks")

api.get_all_user_playlist_contents()

logging.info("done")
```

... I get an error

```python
DEBUG:gmusicapi.Mobileclient1:{u'nextPageToken': u'xxx...', u'kind': u'sj#playlistEntryList', u'data': {u'items': [u'<994 plentries>']}}
DEBUG:gmusicapi.Mobileclient1:ListPlaylistEntries(args=[], kwargs={'start_token': u'xxx...', u'max_results': 20000, 'updated_after': None})
DEBUG:gmusicapi.Mobileclient1:{u'nextPageToken': u'xxx...', u'kind': u'sj#playlistEntryList', u'data': {u'items': [u'<295 plentries>']}}
DEBUG:gmusicapi.Mobileclient1:ListPlaylistEntries(args=[], kwargs={'start_token': u'xxx...', u'max_results': 20000, 'updated_after': None})
DEBUG:gmusicapi.Mobileclient1:{u'nextPageToken': u'xxx...', u'kind': u'sj#playlistEntryList', u'data': {u'items': [u'<539 plentries>']}}
DEBUG:gmusicapi.Mobileclient1:ListPlaylistEntries(args=[], kwargs={'start_token': u'xxx...', u'max_results': 20000, 'updated_after': None})
DEBUG:gmusicapi.Mobileclient1:{u'nextPageToken': u'xxx...', u'kind': u'sj#playlistEntryList', u'data': {u'items': [u'<187 plentries>']}}
DEBUG:gmusicapi.Mobileclient1:ListPlaylistEntries(args=[], kwargs={'start_token': u'xxx...', u'max_results': 20000, 'updated_after': None})
Traceback (most recent call last):
  File "C:/PycharmProjects/test_get_all_playlist_contents/test.py", line 12, in <module>
    api.get_all_user_playlist_contents()
  File "C:\Python27\lib\site-packages\gmusicapi\clients\mobileclient.py", line 466, in get_all_user_playlist_contents
    updated_after=None)
  File "C:\Python27\lib\site-packages\gmusicapi\clients\mobileclient.py", line 1327, in _get_all_items
    return [s for chunk in generator for s in chunk]
  File "C:\Python27\lib\site-packages\gmusicapi\clients\mobileclient.py", line 1340, in _get_all_items_incremental
    **kwargs)
  File "C:\Python27\lib\site-packages\gmusicapi\clients\shared.py", line 84, in _make_call
    return protocol.perform(self.session, self.validate, *args, **kwargs)
  File "C:\Python27\lib\site-packages\gmusicapi\protocol\shared.py", line 228, in perform
    raise CallFailure(err_msg, call_name)
gmusicapi.exceptions.CallFailure: ListPlaylistEntries: 500 Server Error: Internal Server Error
(requests kwargs: {u'url': u'https://mclients.googleapis.com/sj/v2.4/plentryfeed', u'headers': {u'Content-Type': u'application/json', u'Authorization': u'<omitted>'}, u'data': '{"max-results": "20000", "start-token": "xxx..."}', u'method': u'POST', u'params': {u'hl': u'en_US', u'include-tracks': u'true', u'tier': u'aa', u'alt': u'json', u'updated-min': 0}})
(response was: u'{\n "error": {\n  "errors": [\n   {\n    "domain": "global",\n    "reason": "backendError",\n    "message": "Backend Error"\n   }\n  ],\n  "code": 500,\n  "message": "Backend Error"\n }\n}\n')

```

Would you be able to do a similar test? I don't think I reach the end of all the playlist contents as while `api.get_all_user_playlist_contents()` is running, the total accumulated incremental number of tracks from each batch for a playlist when the above error occurs is less than the total number of tracks that should be in that playlist.

**Comment by JVMed** [comment]
`Mobileclient.get_all_user_playlist_contents()` started working again by itself a few hours ago, perhaps it was a similar Google issue to #504.

**Comment by simon-weber** [comment]
Huh, interesting. Thanks for following up.

**Comment by simon-weber** [comment]
Interesting: I think this started happening to my test account. Builds are hanging on that call now.

**Comment by simon-weber** [comment]
A recent ios capture shows Google always restricting this call to 250 results. Even with that it hangs for me, though. Probably Google has a separate call for initializing a client that doesn't have to trawl through all the past mutations.

**Comment by simon-weber** [comment]
The build problem is due to Google switching from omitting the page token key to returning a null one. Since the token looks different, we'd end up looping back around the start of paging. b561fe5833c661705a3a83abe79d9eb3af86dc3f should fix it.

I'm not sure if it's the same problem as what you were having originally. I wonder if they pushed some kind of bug (that you saw) and then introduced this behavior as a hotfix (since it's a breaking change without a version increase).

**Comment by JVMed** [comment]
> This syncing method has been working fine for the last 6 months but now after my custom Mobileclient.get_all_user_playlist_contents() downloads about one hundred 1000-track batches, the next incremental batch results in following error:

I'm not sure when (#513) or what you changed (don't included deleted?) but I updated to the latest dev version today (from 10.0.0) and the number of batches (`lib_chunk`s) `Mobileclient.get_all_user_playlist_contents()` needs to download has decreased significantly from 150+ to about 6, which is a awesome time saving (about 30mins)!

**Comment by simon-weber** [comment]
Yup, that was #513! Glad to hear it sped you up as well.
