### ISSUE TITLE
Small default album art

### ISSUE THREAD

**Issue by tagniam** [simon-weber/gmusicapi#506]
By default, the URL that is included in `albumArtRef` is a link to a ~500x500 image of the cover art. This size is a bit small for some uses, so I think the API should either grab larger art by default or cover art grabbing should be consolidated into its own function to specify the size of the image. Thoughts?

I realize this issue (and how to specify the size of the image through URL parameters) was already addressed in #52, but it's been a while since then and I'm just wondering if there's been any progress.

**Comment by simon-weber** [comment]
Sorry, no progress since then. A separate function for handling resizing sounds good.

I'm going to merge this issue into the older one, since it's got more details.
