### ISSUE TITLE
search("g4m3", x)['song_hits'] returns a list of length 9, regardless of what X is

### ISSUE THREAD

**Issue by MightyAlex200** [simon-weber/gmusicapi#514]
Okay so when I try searching for "g4m3" using the Mobileclient.search method, I __ALWAYS__ get a song_hits list with a length of 9. Here is my code:

```
import gmusicapi
from gmusicapi import Mobileclient
import json

api = Mobileclient()
api.login(email, pass, "1234567890abcdef")
    
print(len(api.search("g4m3", 1)['song_hits']))
```

(the '1' in api.search can be anything)

Am I doing something wrong or is this a bug in either the api or Google Play Music?

**Comment by simon-weber** [comment]
Huh, odd. My bet is it's a bug on Google's side triggered by results that don't fill out an entire chunk, in which case they just return all the results. For example, trying `"the beatles", 1` does properly get only 1 result.

**Comment by MightyAlex200** [comment]
Is it also possible that this is affecting the official Google Play Music applications, as searching "g4m3" on [music.google.com](music.google.com) results in the same list of 9 songs?

**Comment by simon-weber** [comment]
Yup, exactly: if my theory is right, this is a serverside issue that affects all clients (including our unofficial one).

**Comment by simon-weber** [comment]
Going to close this since it seems like it was just something wonky on Google's end.
