### ISSUE TITLE
Working with a corporate proxy

### ISSUE THREAD

**Issue by piggyslasher** [simon-weber/gmusicapi#515]
Hello there. Would there be an easy way to get this to work behind the corporate proxy?

I.e. either take in a flag or use the `https_proxy` environment variable.

**Comment by simon-weber** [comment]
We use `requests` behind the scenes for all http interaction, so I'd expect that setting `HTTPS_PROXY` will work so long as you have a recent version. If you need socks, though, we'd need to add additional code to hook it up. See http://docs.python-requests.org/en/master/user/advanced/#proxies for more details.

**Comment by simon-weber** [comment]
Let me know if that didn't work out for you.

**Comment by piggyslasher** [comment]
Sadly, it didn't. I tried every this. http_proxy, HTTPS_PROXY, ALL_PROXY.
Is there a setting where we can enable `requests` to adhere to these env
variables?

**Comment by simon-weber** [comment]
Can you share exactly what you ran? This works fine for me with a local proxy:
```shell
export HTTPS_PROXY=127.0.0.1
python some_gmusicapi_script.py
```

**Comment by simon-weber** [comment]
Going to close this since it's gone stale.
