### ISSUE TITLE
get_stream_url not returning a path to mp3?

### ISSUE THREAD

**Issue by dhtilly** [simon-weber/gmusicapi#519]
When I call get_stream_url it returns a url similar to this one:

`https://r1---sn-vgqsrn7s.c.doc-0-0-sj.sj.googleusercontent.com/videoplayback?id=cc438977cd539ce7&itag=25&source=skyjam&begin=0&upn=3okKRGzBzc0&o=01621130358061853879&cmbypass=yes&ratebypass=yes&ip=68.39.114.139&ipbits=0&expire=1482048699&sparams=cmbypass,expire,id,ip,ipbits,itag,mm,mn,ms,mv,nh,o,pl,ratebypass,source,upn&signature=559C16D81B798379E6A1A857E65BDF16D5E787FE.6259E393D7D1D3B519CEA3A4B6897853E21FF2B8&key=cms1&mm=31&mn=sn-vgqsrn7s&ms=au&mt=1482048450&mv=m&nh=IgpwZjAxLm9yZDM1Kg42Ni4yMDguMjI4LjIwMQ&pl=15`

I'm trying to use mpg123, a music player for Ubuntu, to play the mp3 from the url, but it can't access the file. Is this because I'm not handling redirects, as mentioned on readthedocs? Trying to use chrome to open the url doesn't redirect, it just goes to a blank page. Is this how the url should look? I was expecting it to point directly to an mp3...

**Comment by simon-weber** [comment]
Yup, that's the expected format. If you're getting a blank page in chrome, the link may have already expired: they only last around 60 seconds.

Try giving the url to `curl -v` -- that should show you what the redirect chain looks like.

**Comment by dhtilly** [comment]
Thanks, posting into to chrome gets it to work now, although trying to use curl returns a Forbidden 403. I've tried using my phone's android_Id instead of the Mobileclient's MAC address, but that didn't change anything. Should I be trying to call curl from within python or is it alright to copy the url into a different terminal? Or is there something wrong with my credentials? is_subscribed and is_authenticated are both returning True. Thanks again!

**Comment by simon-weber** [comment]
Can you paste your exact steps and what output you get? curl works fine for me. You might be running into the 403 noted in the docs: "only one IP can be streaming music at once. This can result in an http 403 with X-Rejected-Reason: ANOTHER_STREAM_BEING_PLAYED."

**Comment by dhtilly** [comment]
Here's the python script:
```
import subprocess
import os
from gmusicapi import Mobileclient
api=Mobileclient()
api.login('dhtilly@gmail.com',appspassword,id)
print api.is_authenticated() 
print api.is_subscribed
sr=api.search('Pink Floyd Time')
#sr=api.search('christmas/ sarajevo 12/24 insrumental')
storeId = str(sr['song_hits'][0]['track']['storeId'])
url=api.get_stream_url(storeId)
print url
```
It outputs True, True, and then the URL. I realized I might not be input to ```curl -v``` correctly. Previously I was just pasting the url, with no quotes, which gave output similar to:
```
[10] 31906
[11] 31907
[12] 31908
[13] 31909
[14] 31910
[15] 31911
[16] 31912
[17] 31913
[18] 31914
[19] 31915
[20] 31916
[6]   Done                    o=01621130358061853879
david@DHT-X230:~/Documents$ *   Trying 74.125.159.135...
* Connected to r1---sn-vgqsrn7s.c.doc-0-0-sj.sj.googleusercontent.com (74.125.159.135) port 443 (#0)
* found 173 certificates in /etc/ssl/certs/ca-certificates.crt
* found 697 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
*        server certificate verification OK
*        server certificate status verification SKIPPED
*        common name: *.c.docs.google.com (matched)
*        server certificate expiration date OK
*        server certificate activation date OK
*        certificate public key: RSA
*        certificate version: #3
*        subject: C=US,ST=California,L=Mountain View,O=Google Inc,CN=*.c.docs.google.com
*        start date: Wed, 30 Nov 2016 15:42:00 GMT
*        expire date: Wed, 22 Feb 2017 15:42:00 GMT
*        issuer: C=US,O=Google Inc,CN=Google Internet Authority G2
*        compression: NULL
* ALPN, server did not agree to a protocol
> GET /videoplayback?id=cc438977cd539ce7 HTTP/1.1
> Host: r1---sn-vgqsrn7s.c.doc-0-0-sj.sj.googleusercontent.com
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 403 Forbidden
< Last-Modified: Wed, 02 May 2007 10:26:10 GMT
< Content-Type: text/plain
< Content-Length: 0
< Connection: close
< X-Content-Type-Options: nosniff
< Date: Wed, 21 Dec 2016 22:08:03 GMT
< Server: gvs 1.0
< 
* Closing connection 0
```
I'm entirely sure how to interpret this output, but I suspect curl was attempting to read multiple urls? Anyways I tried again, with the url enclosed in both single and double quotes (separate tests), but this only caused curl to print for a few seconds, and fill up the terminal window. This data seems worthless to me, just random unicode characters.
Thanks

**Comment by simon-weber** [comment]
The second quoted invocation sounds correct. The output you're seeing is your terminal trying to encode the mp3 data (the same as if you did, say, `cat some.mp3`). Try piping the output a file and then reading the file with your media player.

**Comment by dhtilly** [comment]
Oh wow, that was silly of me... Thanks for all the help, I can access the mp3's fine now.

**Comment by simon-weber** [comment]
No problem! Glad we got it figured out.
