### ISSUE TITLE
search results limited to 100

### ISSUE THREAD

**Issue by Bucklew** [simon-weber/gmusicapi#520]
Using the plugin with the Squeezeserver (originally Logitech) over a plugin.

Would love the get more than 100 albums for one artists, changed this maximum in the plugin, but then realized it is also capped by gmusicapi.

Any way to change this maximum?

PS: Loving your work! Great job!

**Comment by simon-weber** [comment]
Sorry, I think this is a limitation on Google's end. It's possible there's an unimplemented way to page through 100+ results; I haven't looked at this call in a while.

**Comment by Bucklew** [comment]
Too bad, but thank you for the answer.

Having some artists with 100+ albums. So no chance to get everything past 100 (except specific searches).

**Comment by simon-weber** [comment]
Well, it might be possible, but not with our current code. The easiest way to make progress is to find an example of one of Google's clients doing this: then we know it's possible and can look into replicating what it does.

**Comment by Bucklew** [comment]
Ok, thank you for your answer.

Too bad i miss the required python skills :)

**Comment by jscholes** [comment]
For what it's worth, I was also interested in retrieving more than 100 track results for a search query.  However the iOS app doesn't seem to have this functionality and the list stops scrolling at the 100 song mark as well.  Seems like an odd limitation for Google to impose on their own product.

**Comment by thebigmunch** [comment]
So, I was experimenting just now and came across an interesting find. The trick to getting more than 100 results per type is to not send the ``max-results`` param. Despite the fact that setting the max-results over 100 will result in getting only 10 results per type (except for stations and videos, it seems), not sending the ``max-results`` param or setting it as ``None`` will get you up to 999 results per type.

**Comment by thebigmunch** [comment]
PS You should be able to try this out by setting the ``max_results`` parameter to the ``search`` method to ``None``.

**Comment by Bucklew** [comment]
Great workaround, Thank you!

**Comment by simon-weber** [comment]
Nice find. Thoughts on switching the default to None?

**Comment by thebigmunch** [comment]
That's what I think should be done. Just leave the documentation about ``max_results`` > 100 oddity, and it should be fine.
