### ISSUE TITLE
Play one specific song

### ISSUE THREAD

**Issue by diegodeodati** [simon-weber/gmusicapi#526]
Hi it's possibile to play specific song, and if it's possible how...

Thanks this is a very good project

**Comment by simon-weber** [comment]
It sounds like http://unofficial-google-music-api.readthedocs.io/en/latest/reference/mobileclient.html#gmusicapi.clients.Mobileclient.get_stream_url is what you want? You just need to provide the song id.

**Comment by diegodeodati** [comment]
Simon,
which is the code to play a song?
This?
Mobileclient.get_stream_url(song_id, device_id=None, quality=u'hi')

into song_id what i have to put... the name ? which is the id ?

Can you post an example here different from the example into the docs?

**Comment by christopher-dG** [comment]
Hey @diegodeodati, in case you have not already figured this out, the `song_id` that you're looking for is called `storeId`. You can find it in the results from `search(song_name)`: check out the 'song_hits' key in [the docs](http://unofficial-google-music-api.readthedocs.io/en/latest/reference/mobileclient.html#gmusicapi.clients.Mobileclient.search). So what you might do if you wanted to play a song would be:
```python
import subprocess
song_name ="Song I want to play"
results = Mobileclient.search(song_name)
top_song_result = results['song_hits'][0]['track']
stream_url = Mobileclient.get_stream_url(top_song_result['storeId'])  # The url to stream.
subprocess.call('mpv', stream_url)  # Play the song.
```

**Comment by domdomegg** [comment]
Can this issue be closed now?

**Comment by simon-weber** [comment]
Yup, sounds good to me.
