### ISSUE TITLE
Error Login

### ISSUE THREAD

**Issue by diegodeodati** [simon-weber/gmusicapi#527]
Hi i have one error,
i try to connect to my google music accont but the script give me this error:

gmusicapi.exceptions.NotLoggedIn

this is my very simple code:

from gmusicapi import Mobileclient

api = Mobileclient()
api.login('#############@gmail.com', '#########', Mobileclient.FROM_MAC_ADDRESS)
# => True

library = api.get_all_songs()

print(library)

any idea?

**Comment by simon-weber** [comment]
Did api.login actually return true? Or was that copied and pasted? If it's not returning true, there's something wrong with email/password you've provided.

**Comment by diegodeodati** [comment]
Hi Simon,
i have active two step confirmation and this is the problem.

**Comment by simon-weber** [comment]
Ah, ok. You'll need to set up an app password to use with gmusicapi: https://support.google.com/accounts/answer/185833?hl=en.

**Comment by diegodeodati** [comment]
Simon,
i do what you suggest... but 

UserWarning: implicit cast to 'char *' from a different pointer type: will be forbidden in the future 

Here is the code:

from gmusicapi import Mobileclient

api = Mobileclient()
logged_in = api.login('#####@gmail.com', '#### #### #### ####', 'android')

any suggestion?

**Comment by simon-weber** [comment]
That warning can be ignored. It's a problem with a dependency that can be fixed by upgrading it: https://github.com/pyca/cryptography/issues/3156#issuecomment-248623017.
