### ISSUE TITLE
Some Warnings...

### ISSUE THREAD

**Issue by diegodeodati** [simon-weber/gmusicapi#528]
Simon,
another problem...

UserWarning: implicit cast to 'char *' from a different pointer type: will be forbidden in the future

Here is the code:

from gmusicapi import Mobileclient

api = Mobileclient()
logged_in = api.login('#####@gmail.com', '#### #### #### ####', 'android')

any suggestion?
How i can disable warnings? i have

**Comment by simon-weber** [comment]
I'm closing this as a duplicate of https://github.com/simon-weber/gmusicapi/issues/527.
