### ISSUE TITLE
Tracks not adding to playlist (nids not beginning with "T"?)

### ISSUE THREAD

**Issue by JVMed** [simon-weber/gmusicapi#530]
The last few days I've experienced new problems with not all my nids being added to a playlist, for example out of a list of 115 nids only 14 would appear in GPM (if it matters all the tracks were released fairly recently). Looking through the `nid `list only 16 tracks had nids that began with capital `T`. However if I add each track's `storeid ` instead they all appear successfully in the playlist in GPM. Here is one track found with `mobileclient.search()` that did not add to a playlist with its `nid `but did with its `storeid`

`{u'track': {
        u'albumArtRef': [{
            u'url': u'http://lh3.googleusercontent.com/aeFT0-EChHFb3rH1JHTGixVaAKzgAIHHfKh6BZRG9rmISVehhRcsXICaLtiTK2qJNKWTTFHMSg'
                ,
            u'kind': u'sj#imageRef',
            u'aspectRatio': u'1',
            u'autogen': False,
            }],
        u'artistId': [u'sp4jilxe26d26cpptgi4ai6cfy'],
        u'composer': u'',
        u'year': 2017,
        u'trackAvailableForSubscription': True,
        u'trackType': u'7',
        u'album': u'Never Start',
        u'title': u'Never Start',
        u'albumArtist': u'Middle Kids',
        u'trackNumber': 1,
        u'discNumber': 1,
        u'albumAvailableForPurchase': True,
        u'explicitType': u'2',
        u'trackAvailableForPurchase': True,
        u'storeId': u'Tvi2dqrf4c6gh7zdfch3bdlo2au',
        u'nid': u'vi2dqrf4c6gh7zdfch3bdlo2au',
        u'estimatedSize': u'7889006',
        u'albumId': u'rtgsjtvlo24y7jnczxaabqsjxm',
        u'genre': u'Alternative/Indie',
        u'playCount': 4,
        u'kind': u'sj#track',
        u'artist': u'Middle Kids',
        u'lastModifiedTimestamp': u'1486175786462384',
        u'durationMillis': u'197000',
        }, u'type': u'1'}`

Is it common for a tracks nid not begin with `T`? From my logs the earliest occurrence of a nid not beginning with `T` was Jan 2017.

**Comment by simon-weber** [comment]
I haven't noticed a change myself, but I've long since avoided using nids. They seem to change randomly. The storeid or track id are usually the way to go.
