### ISSUE TITLE
oauth2 with Mobileclient

### ISSUE THREAD

**Issue by iondulgheru** [simon-weber/gmusicapi#534]
Hi
I am using two step authentication for my google account.
Using the documentation I successfully configured Musicmanager.
I am trying to also setup Mobileclient with oauth2, but I am lost in the process of creating my credentials.
Is there any way to create the oauth token for Mobileclient the same way I created it for Musicmanager?

Thank you

**Comment by simon-weber** [comment]
Unfortunately, the mobileclient does not support oauth right now. https://github.com/simon-weber/gmusicapi/issues/426 is the ticket to watch for that. Instead, you'll need to set up an application password and use that.

**Comment by iondulgheru** [comment]
Thank you @simon-weber 
Meanwhile I managed to create an application password and it works.
