### ISSUE TITLE
updatePlaylistOrder

### ISSUE THREAD

**Issue by limeblack** [simon-weber/gmusicapi#542]
So I'm in the process of creating an interface that allows you to simply reorder songs in a playlist.

Instead of calling reordering functions it would be very convenient if you could simple call 2 functions.

ListPlaylistEntries(I think) and updatePlaylistOrder.

How feasible would it be to implement such a function/would you consider adding such a function?

**Comment by simon-weber** [comment]
What's the interface you're picturing?

**Comment by limeblack** [comment]
@simon-weber  you pass in an array of songs with songids(or whatever is used to track them)

**Comment by simon-weber** [comment]
Got it. https://github.com/simon-weber/gmusicapi/issues/185 is an old issue that tracks this. Let's reuse it and move discussion over there.
