### ISSUE TITLE
MAX_PER_MACHINE_USERS_EXCEEDED

### ISSUE THREAD

**Issue by aug-riedinger** [simon-weber/gmusicapi#543]
I get the following error:

```
CallFailure: AuthenticateUploader: AuthenticateUploader: Upload auth error code 12: MAX_PER_MACHINE_USERS_EXCEEDED. See http://goo.gl/O6xe7 for more information. 
```

with the following code:

```
import gmusicapi.clients
gmusicapi.clients.Musicmanager.perform_oauth(storage_filepath='./play-music.key')
music_manager.login(oauth_credentials='./play-music.key')
result = music_manager.upload("./static/music.mp3")
```

Does this sound any familiar?

I'm aware I might have done ooauth several times during my setup, but still:
- How can I know how many USERS are concerned?
- How can I remove former access (remove clients)?
- Or do I simply have to wait for sessions to expire?

Thanks

**Comment by simon-weber** [comment]
Huh, I haven't seen this one before. You can check what's registered under settings > my devices in the webapp and deauth old ones, but there are some limits to how often you can do that.

What I'd recommend is picking one of the existing device ids from http://unofficial-google-music-api.readthedocs.io/en/latest/reference/mobileclient.html#gmusicapi.clients.Mobileclient.get_registered_devices and reusing that in your login call (even across multiple real devices, if you have them). What might be happening now is that you're creating new devices without knowing it and filling up your limit.

**Comment by aug-riedinger** [comment]
Got it!

I was using gmusicapi through a docker which may not send an actual MAC address in its request hence was failing.

Fixed it by adding a second argument to the login:
```
  music_manager.login(oauth_credentials='./play-music.key', uploader_id='00:00:00:00:00:00')
```

used my actual current MAC address though I'm not sur this was mandatory.

Thanks for getting in touch and your suggestions!
