### ISSUE TITLE
Playlist Reordering

### ISSUE THREAD

**Issue by meep366** [simon-weber/gmusicapi#546]
Currently the Mobileclient.reorder_playlist_entry() method operates on one entry at a time and passes back a ClientID to the Google API. Unfortunately, it appears that calling the method on single entries leads to random behavior, possibly the Google API expects them to be done in batches so the ClientIDs are out of date after the first call. I tested it by creating a simple loop to sort a playlist one by one and even with 10 songs, sometimes the reorder would fail to work.

**Comment by simon-weber** [comment]
Oh, I had forgotten there was a super old issue for this: https://github.com/simon-weber/gmusicapi/issues/185. I've already got the relevant links to Autoplaylists over there, so I'm going to merge this ticket into it.
