### ISSUE TITLE
Please add support to query a playlist ID and all tracks inside that ID?

### ISSUE THREAD

**Issue by lohriialo** [simon-weber/gmusicapi#553]
Is there a way to find out a particular playlist ID and all tracks inside that ID?

Then returning the tracks and it's information in a json data would be awesome and would make this library so useful

**Comment by simon-weber** [comment]
[Mobileclient.get_all_user_playlist_contents](http://unofficial-google-music-api.readthedocs.io/en/latest/reference/mobileclient.html#gmusicapi.clients.Mobileclient.get_all_user_playlist_contents) supports this if I'm understanding you correctly.

It retrieves all a user's playlists. At least last I checked, Google didn't have an interface for retrieving only a single playlist (and given how their clients work, they're unlikely to add one).

Hope that helps!
