### ISSUE TITLE
Download whole library

### ISSUE THREAD

**Issue by ggrelet** [simon-weber/gmusicapi#554]
Hi! First of all, thanks for your work.
I've been using Google Music a lot (10.000+ songs uploaded) and I'd like to download the whole library.

But the thing is that's the whole package is above 100GB... I couldn't figure it before the download so I proceeded with the official Music Manager to an external drive with only 80GB of free space. I now have 900+ songs that can't be downloaded but I'd like to complete my discography, si here's the question, is there a way to download the whole library but check the existing files and set the download directory as a complete other from the current location of the previously downloaded songs?

**Comment by thebigmunch** [comment]
You probably want to look at my https://github.com/thebigmunch/gmusicapi-scripts. Specifically, the ``gmsync`` command.

**Comment by ggrelet** [comment]
Ok this seems great, still need a bit of help.

Thanks to this:
`gmsync down -m "/path/to/my/current/downloaded/music" -d`
I've been able to retrieve all the missing song.

Now, is there a way to download them to another folder? Like this, for exemple:
`gmsync down -m "/path/to/my/current/downloaded/music" "/path/to/another/folder" -d`

Or should I parse the resulting songs through `pipe |` and make a complete another command with `gmdownload?

**Comment by simon-weber** [comment]
I'm going to close this since it's gone stale.

**Comment by ggrelet** [comment]
Thanks for you help
