### ISSUE TITLE
Unable to login/auth to googleapps/gapps accounts

### ISSUE THREAD

**Issue by cacheuk** [simon-weber/gmusicapi#558]
I'm currently unable to api.login() (fails) when the google account is a google apps account!

any known workaround ?

**Comment by simon-weber** [comment]
Hm, I haven't heard of other folks having problems. Here's some usual (non-gapps specific) debugging ideas:
* try disabling 2fa if it's enabled
* try enabling [less secure app access](https://support.google.com/accounts/answer/6010255)
* log into the account and check for any security alerts
* check that you can log into other accounts from the same IP

**Comment by cacheuk** [comment]
Thanks @simon-weber I had checked those prior to opening an issue :) after a little print() debugging it appears that I was getting {u'Error': u'DeviceManagementRequiredOrSyncDisabled'} in Mobileclient.login/res = gpsoauth.perform_oauth(). having gone through the Domain settings in the the Google Admin console for the domain in question it appears that turning the following setting to off fixes the above error and I can login() again:


the setting is in Google Admin console > Device management > Setup
![screenshot from 2017-06-18 10-20-29](https://user-images.githubusercontent.com/1109092/27259741-e5294828-5411-11e7-986d-4235fe9145d2.png)

**Comment by simon-weber** [comment]
Ah, interesting; I hadn't heard of that one before.

Nice work figuring it out and thanks for posting back! Sounds like https://github.com/simon-weber/gmusicapi/issues/532 would have helped here.
