### ISSUE TITLE
Help with AddToPlaylist method

### ISSUE THREAD

**Issue by iKethavel** [simon-weber/gmusicapi#562]
Hi, I'm trying to understand how AddToPlaylist method work. And I have some problems with params which I'll send. Can you help me explain that?
Why don't I use this plugin? Because my app works over Node JS and [this](https://github.com/jamon/playmusic) doesn't work :)

**Comment by simon-weber** [comment]
Sure. Post your code, responses and whatnot and I'll try to help.

**Comment by iKethavel** [comment]
I've broken my Google account, and, maybe, I'll need to begin from login function))
Where can I find work example of this API?

**Comment by simon-weber** [comment]
The docs are your best bet unless there's something more specific I can help with: http://unofficial-google-music-api.readthedocs.io/en/latest/usage.html#usage.

**Comment by simon-weber** [comment]
I'm going to close this since it's gone stale.
