### ISSUE TITLE
Upload session fails after a few uploads

### ISSUE THREAD

**Issue by Forceflow** [simon-weber/gmusicapi#570]
Using the latest gmusicapi release, I'm using a script (gmusicapi-scripts by @thebigmunch) to sync my library. After syncing a few tracks (uploading new ones that have been added to my local library recently), I always get this error:

> Traceback (most recent call last):
  File "./gmsync.py", line 219, in <module>
    main()
  File "./gmsync.py", line 202, in main
    mmw.upload(songs_to_upload, enable_matching=cli['match'], delete_on_success=cli['delete-on-success'])
  File "/usr/local/lib/python3.5/dist-packages/gmusicapi_wrapper/decorators.py", line 22, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/gmusicapi_wrapper/musicmanager.py", line 303, in upload
    for result in self._upload(filepaths, enable_matching=enable_matching, transcode_quality=transcode_quality):
  File "/usr/local/lib/python3.5/dist-packages/gmusicapi_wrapper/musicmanager.py", line 256, in _upload
    filepath, enable_matching=enable_matching, transcode_quality=transcode_quality
  File "<decorator-gen-74>", line 2, in upload
  File "/usr/local/lib/python3.5/dist-packages/gmusicapi/utils/utils.py", line 616, in wrapper
    return function(*args, **kw)
  File "<decorator-gen-73>", line 2, in upload
  File "/usr/local/lib/python3.5/dist-packages/gmusicapi/utils/utils.py", line 593, in wrapper
    return function(*args, **kw)
  File "/usr/local/lib/python3.5/dist-packages/gmusicapi/clients/musicmanager.py", line 578, in upload
    musicmanager.GetUploadSession.process_session(session)
  File "/usr/local/lib/python3.5/dist-packages/gmusicapi/protocol/musicmanager.py", line 463, in process_session
    ['completionInfo']['customerSpecificInfo']['ResponseCode'])
KeyError: 'customerSpecificInfo'

Things I already tried:

- Re-auth gmusicapi
- Reboot system
- Manually updating files to gmusic using the browser (works)

Any idea what might be the cause of this? Keep in mind that every time I run the sync script, a few tracks get uploaded succesfully (and play fine in gmusic), but after the fifth or sixth track, gmusicapi throws this error.

**Comment by Forceflow** [comment]
I figured out that the error that is returned is missing the customerSpecificInfo key. In order to find out what's in the error message anyway, I'm going to add a print statement right in front of that call in musicmanager.py.

**Comment by Forceflow** [comment]
This is in the actual response:

{'errorMessage': {'reason': 'REQUEST_REJECTED', 'upload_id': 'AEnB2UqVGJmql2N_K8EM3cMyz7zbcjF9EV3
9bIvk7wwtlcg-dcrrYRMW9CZpGaCMu3jBC8r2DPkhec_8Q5D8MOWPqO6LPavqQ', 'additionalInfo': {'uploader_ser
ice.GoogleRupioAdditionalInfo': {'completionInfo': {'status': 'REJECTED', 'customerSpecificInfo':
{'ResponseCode': 503}}, 'requestRejectedInfo': {'reasonDescription': 'agent_rejected'}}}}}

**Comment by mcat-ee** [comment]
I'm also getting this error - it fails on the first upload attempt :( 

I've tried uploading with modified uploader name and id

**Comment by Forceflow** [comment]
Tonight, **all** my uploads are failing with this session response. Yesterday I still could upload some songs after retrying.

> Info': {'status': 'REJECTED'}, 'requestRejectedInfo': {'reasonDescription': 'agent_rejected'}}}, 'reason': 'REQUEST_REJECTED'}}
> {'errorMessage': {'upload_id': 'AEnB2UqNzQFzEr-IbvZWqu_aT7PF1U8KmVtNhvCfqySQpzi4OBETUWJrRQFNir7ljOqOWzDeMOh_sxPm64r3qYdqhEGcdxquuw', 'additionalInfo': {'uploader_service.GoogleRupioAdditionalInfo': {'completionInfo': {'status': 'REJECTED'}, 'requestRejectedInfo': {'reasonDescription': 'agent_rejected'}}}, 'reason': 'REQUEST_REJECTED'}}

**Comment by simon-weber** [comment]
Hm, I haven't seen that one before.

For what it's worth, I just manually restarted a build and it passed: https://travis-ci.org/simon-weber/gmusicapi/builds/272970476. I can't think of anything that might be different about the test accounts, unless Google is rolling out a change and it hasn't reached them yet.

**Comment by simon-weber** [comment]
Huh, it actually just failed after merging #571: https://travis-ci.org/simon-weber/gmusicapi/builds/273145876. I'll be interested to see if it fails tomorrow.

**Comment by mcat-ee** [comment]
@Forceflow You can pass the options to the **MusicManager.login(...)** method, but it didn't work :( 

I can't try it right now but perhaps Google is whitelisting the acceptable user-agents?

**Comment by Forceflow** [comment]
@simon-weber I'm not ruling out it's a problem with Google Music service itself.

I have a fairly huge library (18k) and some files had wrong tags. Since the gmusicapi-method was broken, I thought I'd use the shoddy Chrome plugin to upload them again. Removed them, (even from the gmusic trash), tried to upload them again and half the files would not upload. Reason: "failed to upload file".

https://imgur.com/a/Mj4DN

**Comment by ibaaj** [comment]
same problem here.

**Comment by ibaaj** [comment]
MusicManager is having issues also : 
![http://i.imgur.com/2Bd8Nks.png](http://i.imgur.com/2Bd8Nks.png)

**Comment by jacopomarcovaldi** [comment]
Hi, today i have this exception too, Reading your post seems that google music is having some problem, infact ibaaj can't upload even if he uses music manager, i am right?

**Comment by billhudson73** [comment]
Same api uploading issue here too.

**Comment by ibaaj** [comment]
@jacopomarcovaldi yes, both MusicManager and gmusicapi are having issues to upload content

we need to wait google team...

**Comment by jacopomarcovaldi** [comment]
@ibaaj thank you :) :+1:

**Comment by Forceflow** [comment]
I have contacted Google Music support using Google chat (not sure if I talked to a bot or a real person), but the issue would be "forwarded to an expert". I referred to this thread, so I hope they read it.

**Comment by kcgthb** [comment]
Similar problem reported by Music Manager users: https://productforums.google.com/forum/#!topic/play/pIGUj7D74m8

**Comment by Forceflow** [comment]
Got a reply from Google Play team: 

Hi Jeroen, 

This is Rochelle from YouTube and Play Music team.

I am writing you back regarding your upload issue on Google Play Music. We've received some reports of similar issues from other users and our engineers are working on a fix as I am sending this email. Just try it again within 24 to 48 hours and this should be working fine.

**Comment by Forceflow** [comment]
I just tried uploading again using the latest gmusicapi code, and it worked. Anyone else having success again? If so - this issue can be closed.

**Comment by jacopomarcovaldi** [comment]
@Forceflow Yes confirmed, this morning my script uploaded 2 files :+1:

**Comment by mcat-ee** [comment]
Can also confirm - @simon-weber, close this issue?

**Comment by simon-weber** [comment]
Glad it wasn't on our end! Thanks for keeping tabs on it, everyone.
