### ISSUE TITLE
Multiple Account

### ISSUE THREAD

**Issue by ibaaj** [simon-weber/gmusicapi#572]
Hello,

Sorry if this question has been already answered or I didn't read enough of the documentation..
I'm currently working with the ```gmupload.py``` script from @thebigmunch to upload content to Google Music.

But now, I want to use 2 google music accounts separately. 

Even if I tried to use a virtualenv and read the code from gmusic-scripts and gmusicwrapper, I'm always connected with my first account, I never get disconnected or be able to use my new account...

I'm sure there is a way but for the moment I didn't find any.
Can you help me ?

best regards,
ibaaj

**Comment by thebigmunch** [comment]
As shown in the [usage docs](https://thebigmunch.github.io/gmusicapi-scripts/usage/) for my scripts, the MusicManager-based scripts (upload, download, sync) have an argument for setting the name of the credential file to use: ``-c, --cred``. Use that to set different credential files for different accounts.

**Comment by ibaaj** [comment]
thanks a lot
