### ISSUE TITLE
Missing / inconsistent tags

### ISSUE THREAD

**Issue by jason-a69** [simon-weber/gmusicapi#579]
I am in the process of uploading my music collection, whilst this is ongoing I have been messing around trying to extract parts of my library that are already uploaded. I have encountered a couple of issues.

Issue 1
I have tried to download all song by a certain artist, on this occasion "Abba" (OK OK I am showing my age). The code is very simple
`library = api.get_all_songs()
for track in library:
    if track['artist'] == 'Abba':
       print track['artistId']
`
This will run to a certain point and then fall over because artistId is not found in one of the tracks
....
`[u'Apybyeokraflfy6xw2ci5ob77oi']
[u'Apybyeokraflfy6xw2ci5ob77oi']
[u'Apybyeokraflfy6xw2ci5ob77oi']
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    print track['artistId']
KeyError: 'artistId'
`
Is this normal behaviour?

Issue 2
I have been doing some other testing and I am having problems displaying my library, yet again it is something to do with the tags. I am getting a different artistID tags for the same artist (yeah OK, it's Abba again). Again - is this normal behaviour?

I was thinking of trying to clear the cache on the Google Play Music side in the hope that things will fix themselves....or just leave it for a few days.

Any advice is appreciated

Thanks

Jason

**Comment by simon-weber** [comment]
Yeah, these are expected. Google's database changes unexpectedly, so avoid relying too much on fields they control. You can also see exactly which fields are optional in https://github.com/simon-weber/gmusicapi/blob/develop/gmusicapi/protocol/mobileclient.py under sj_track.

**Comment by jason-a69** [comment]
Hi Simon,

Thanks very much for this, I'll code around the artist / album IDs

Jason

**Comment by simon-weber** [comment]
No problem!
