### ISSUE TITLE
Play an Activity Radio

### ISSUE THREAD

**Issue by litobro** [simon-weber/gmusicapi#587]
Maybe I'm just daft but I cannot find this feature anywhere in the docs. Is it possible to get the tracks for an Activity Radio?

I'm thinking the pre-defined ones google has made like "hanging out" or "sleeping".

**Comment by thebigmunch** [comment]
Those are called [situations](https://unofficial-google-music-api.readthedocs.io/en/latest/reference/mobileclient.html#gmusicapi.clients.Mobileclient.get_listen_now_situations).
