### ISSUE TITLE
CallFailure: ListStations: 500 Server Error: Internal Server Error for url

### ISSUE THREAD

**Issue by ceberous** [simon-weber/gmusicapi#588]
it seems that the radio stations are no longer being returned from:
mopidy.playlists.getPlaylists()

http://showterm.io/cba2e5d57c3aed961f55d#fast

https://github.com/simon-weber/gmusicapi/blob/850e29a5dd51a66a50973ee1e6d825db3938d6f1/gmusicapi/protocol/shared.py#L101

https://github.com/simon-weber/gmusicapi/blob/94622f277333930ac15b6771e3cdbc99f22f9854/gmusicapi/protocol/mobileclient.py#L628

https://github.com/simon-weber/gmusicapi/blob/94622f277333930ac15b6771e3cdbc99f22f9854/gmusicapi/protocol/mobileclient.py#L1426

https://github.com/simon-weber/gmusicapi/blob/850e29a5dd51a66a50973ee1e6d825db3938d6f1/gmusicapi/clients/mobileclient.py#L1591

https://github.com/simon-weber/gmusicapi/blob/850e29a5dd51a66a50973ee1e6d825db3938d6f1/gmusicapi/clients/mobileclient.py#L1977

https://github.com/simon-weber/gmusicapi/blob/850e29a5dd51a66a50973ee1e6d825db3938d6f1/gmusicapi/clients/shared.py#L77

**Comment by simon-weber** [comment]
Hm, I just reran the tests and it seemed to work. An unrelated call did 500, though, so maybe Google is having some temporary issues on their end? Here's the build: https://travis-ci.org/simon-weber/gmusicapi/jobs/309140390.

Give it a shot after waiting a little bit and let me know if it's still broken.

**Comment by ceberous** [comment]
I waited a while. But nothing changed. I got it to work by opening up a browser and logging out and back in to https://myaccount.google.com/

**Comment by simon-weber** [comment]
Glad you got it working! No need to delete the history: it's helpful in case other people run into the same problem.

For posterity's sake: the problem was unexpected 500s on ListStations, and logging out and back in fixed it.
