### ISSUE TITLE
Mobileclient login function returning false

### ISSUE THREAD

**Issue by squibsy** [simon-weber/gmusicapi#589]
I'm using
`loggedIn = self.api.login(email, password, device_id)`
where email is my full gmail email address, password is my Google account password and device_id is from
`Mobileclient.FROM_MAC_ADDRESS`
but I always get false returned by the login function. I'm not using 2fa and I'm uncertain how to troubleshoot. Device is a raspberry pi, and my Christmas present is now in jeopardy :-)

**Comment by simon-weber** [comment]
Can you try enabling 2fa with an app password as per https://github.com/simon-weber/gmusicapi/issues/584 and see if that fixes it?

**Comment by cmrace** [comment]
I had this problem as well. I got around it (by accident) without 2fa by replacing 'Mobileclient.FROM_MAC_ADDRESS' with my actual device id. To find that, use self.api.login(email, password, '1234567890abcdef'). It should return an error message saying that id is invalid (duh). It then lists valid device ids - choose the 16 digit one.

Be careful, only '1234567890abcdef' will work! Other bogus ids just return False.

**Comment by exp0nge** [comment]
@cmrace What's odd is that you have to make a call that fails to get device id's and then parse them to find the Android device id.

**Comment by squibsy** [comment]
@exp0nge The device id call appears to raise a not logged in exception

@cmrace The login call appears to return a boolean value only. The documentation supports this.

Creating an app password worked - I slotted it into
loggedIn = self.api.login(email, password, device_id)
and all is well.

Thanks all for the input.

**Comment by exp0nge** [comment]
@squibsy you have to catch the exception when you login to get the valid id's

**Comment by simon-weber** [comment]
Huh, this is the first I've heard of auth problems caused by client ids (except in the case where people had too many).

I'm gonna merge this into https://github.com/simon-weber/gmusicapi/issues/584. It would be pretty easy to allow people to get their existing ids upfront if needed.
