### ISSUE TITLE
Semantic Versioning for rc releases

### ISSUE THREAD

**Issue by davewongillies** [simon-weber/gmusicapi#592]
In `HISTORY.rst` in this repo, its noted that from `1.0` semantic versioning is used. A small request, can you please make your `rc` releases versions SemVer compliant as well?

As per https://semver.org/#spec-item-9:
> A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version. Identifiers MUST comprise only ASCII alphanumerics and hyphen [0-9A-Za-z-]. Identifiers MUST NOT be empty. Numeric identifiers MUST NOT include leading zeroes. Pre-release versions have a lower precedence than the associated normal version. A pre-release version indicates that the version is unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version. Examples: 1.0.0-alpha, 1.0.0-alpha.1, 1.0.0-0.3.7, 1.0.0-x.7.z.92.

So instead of `11.0.1rc1` the version would be `11.0.1-rc.1`. The reason I ask is that I'm attempting to do version checking for https://github.com/squeezebox-googlemusic/squeezebox-googlemusic and since the rc releases aren't semver compliant, I can't do version comparisons correctly.

**Comment by simon-weber** [comment]
Whoops! Sure, I'll switch to the proper formatting going forward.
