### ISSUE TITLE
gmusicapi.Mobileclient1 (shared:281) [ERROR]: the response format for Search was not recognized.

### ISSUE THREAD

**Issue by chinbhat** [simon-weber/gmusicapi#596]
When you ask to start a station for A R Rahman, the following error occurred. The audio plays fine. But there is an error in debug, asking you to raise an issue.

[error.log](https://github.com/simon-weber/gmusicapi/files/1624688/error.log)
Raising an issue as per the log instruction. 

First, try the develop branch. If you can recreate this error with the most recent code please [create an issue](http://goo.gl/qbAW8) that includes the above ValidationException and the following request/response:

* Added Error.log

**Comment by simon-weber** [comment]
I think this should be fixed on the develop branch by 7428776650898cc316628ad49fa0b30579b43f3a. You can install the most recent code with something like:
```
pip uninstall gmusicapi
pip install git+https://github.com/simon-weber/gmusicapi.git@develop#egg=gmusicapi
```

Feel free to reopen if if you're still getting this error with the most recent code.
