### ISSUE TITLE
Unable to play my station. Command accepted, but music doesnt come through.

### ISSUE THREAD

**Issue by chinbhat** [simon-weber/gmusicapi#597]
I asked Geemusic to play my station. Alexa responded that she will play my personalized station, but the music isnt coming through.

Attaching the debug trace and amazon service request & response. 

-- Using Google music paid Subscription.
[Amazon_service_response.txt](https://github.com/simon-weber/gmusicapi/files/1628854/Amazon_service_response.txt)
[Amazon_service_request.txt](https://github.com/simon-weber/gmusicapi/files/1628855/Amazon_service_request.txt)
[error.log](https://github.com/simon-weber/gmusicapi/files/1628856/error.log)

**Comment by simon-weber** [comment]
This looks like a bug on geemusic's end: looking at the gmusicapi log it's generating a stream request with a songid of `None`.

Best to open an issue over at https://github.com/stevenleeg/geemusic/issues instead.
