### ISSUE TITLE
get_all_stations returns all recent stations instead of stations in my library

### ISSUE THREAD

**Issue by bretrouse** [simon-weber/gmusicapi#604]
Hello,

Is it possible to add a flag to the get_all_stations call that will only return stations in my library? Currently the call is returning every station I've ever listened to rather than ones I've saved.

Thanks,
Bret

**Comment by simon-weber** [comment]
Huh, I actually didn't know that was the default behavior, haha. If this is something the apps do then it's possible, but we'd have to figure out how to form the call.

For now, does setting updated_after help? That would at least get you just recent stations.

**Comment by bretrouse** [comment]
Hmm, updated_after may be helpful in the interim but it's entirely dependent upon what stations were recently played.

If I go to the app and look at Stations under the Library section it shows 4 most recent stations, then it shows My Stations which is the set I've saved to my Library, so the app does have a way of supporting this.

I was adding adding Stations support to the Alexa skill [GeeMusic ](https://github.com/stevenleeg/geemusic) when I encountered this.

**Comment by thebigmunch** [comment]
Stations in your library will have the key ``inLibrary`` set to True. I don't believe I've ever seen anything in the calls themselves to do this, so I believe it's done client-side.

**Comment by bretrouse** [comment]
Ah, thanks! I'll check this out tonight. Client-side filtering should be fine.

**Comment by thebigmunch** [comment]
Just for future knowledge and more novice users, it is indeed a True/False value. I just do this in my code: ``[station for station in station_list if station.get('inLibrary')]``.

**Comment by simon-weber** [comment]
Ah, awesome. We should add that to the example station dict. I suppose we could add a flag to do the filtering, too, but if it's that simple maybe we just call it out in the docs.

**Comment by bretrouse** [comment]
Adding filtering to the API itself could help enforce best practices but definitely isn't a requirement. Having the example in the docs should be enough.
