### ISSUE TITLE
Unable to edit playlists created with create_playlist

### ISSUE THREAD

**Issue by taschaal** [simon-weber/gmusicapi#605]
Using the create_playlist(name) method of the mobileclient will successfully create an empty playlist, but if I try to edit it I get "Couldn't open the playlist. Please try again."   Also trying to use add_songs_to_playlist(plid,songids)  fails with:

gmusicapi.exceptions.CallFailure: BatchMutatePlaylistEntries: 500 Server Error: Internal Server Error for url: https://mclients.googleapis.com/sj/v2.5/plentriesbatch?dv=0&tier=fr&alt=json&hl=en_US
(requests kwargs: {u'url': u'https://mclients.googleapis.com/sj/v2.5/plentriesbatch', u'headers': {u'Content-Type': u'application/json', u'Authorization': u'<omitted>'}, u'data': '{"mutations": [{"create": {"followingEntryId": "fc690150-40d2-11e8-8a83-44032cfab7ce", "deleted": false, "trackId": "55ebe4e7-f76e-3d2e-8fa3-c34aa6bb38ae", "lastModifiedTimestamp": "0", "playlistId": "7ed97737-a7f0-493d-9445-0827841b54e0", "clientId": "fc69014f-40d2-11e8-9f5f-44032cfab7ce", "source": 1, "creationTimestamp": "-1"}}, {"create": {"followingEntryId": "fc690151-40d2-11e8-a79f-44032cfab7ce", "deleted": false, "trackId": "5a32f196-02aa-30c8-a0d5-41ce43d27bc4", "lastModifiedTimestamp": "0", "playlistId": "7ed97737-a7f0-493d-9445-0827841b54e0", "clientId": "fc690150-40d2-11e8-8a83-44032cfab7ce", "source": 1, "precedingEntryId": "fc69014f-40d2-11e8-9f5f-44032cfab7ce", "creationTimestamp": "-1"}}, {"create": {"followingEntryId": "fc692861-40d2-11e8-b406-44032cfab7ce", "deleted": false, "trackId": "de7afb78-96c3-3c7c-baa6-e095b9f2c817", "lastModifiedTimestamp": "0", "playlistId": "7ed97737-a7f0-493d-9445-0827841b54e0", "clientId": "fc690151-40d2-11e8-a79f-44032cfab7ce", "source": 1, "precedingEntryId": "fc690150-40d2-11e8-8a83-44032cfab7ce", "creationTimestamp": "-1"}}, {"create": {"followingEntryId": "fc692862-40d2-11e8-bf28-44032cfab7ce", "deleted": false, "trackId": "8ccc5a22-8345-35d1-a32c-66569f978416", "lastModifiedTimestamp": "0", "playlistId": "7ed97737-a7f0-493d-9445-0827841b54e0", "clientId": "fc692861-40d2-11e8-b406-44032cfab7ce", "source": 1, "precedingEntryId": "fc690151-40d2-11e8-a79f-44032cfab7ce", "creationTimestamp": "-1"}}, {"create": {"followingEntryId": "fc692863-40d2-11e8-b489-44032cfab7ce", "deleted": false, "trackId": "5b264e40-fb2d-3a7c-bdad-efbf3f6daaee", "lastModifiedTimestamp": "0", "playlistId": "7ed97737-a7f0-493d-9445-0827841b54e0", "clientId": "fc692862-40d2-11e8-bf28-44032cfab7ce", "source": 1, "precedingEntryId": "fc692861-40d2-11e8-b406-44032cfab7ce", "creationTimestamp": "-1"}}, {"create": {"followingEntryId": "fc692864-40d2-11e8-888d-44032cfab7ce", "deleted": false, "trackId": "8dbf4f83-a0ef-3209-ac38-b0d1cb4885a0", "lastModifiedTimestamp": "0", "playlistId": "7ed97737-a7f0-493d-9445-0827841b54e0", "clientId": "fc692863-40d2-11e8-b489-44032cfab7ce", "source": 1, "precedingEntryId": "fc692862-40d2-11e8-bf28-44032cfab7ce", "creationTimestamp": "-1"}}, {"create": {"followingEntryId": "fc692865-40d2-11e8-9107-44032cfab7ce", "deleted": false, "trackId": "a9fa1f50-ca65-33b6-84d6-2fda788e5db2", "lastModifiedTimestamp": "0", "playlistId": "7ed97737-a7f0-493d-9445-0827841b54e0", "clientId": "fc692864-40d2-11e8-888d-44032cfab7ce", "source": 1, "precedingEntryId": "fc692863-40d2-11e8-b489-44032cfab7ce", "creationTimestamp": "-1"}}, {"create": {"followingEntryId": "fc692866-40d2-11e8-94b6-44032cfab7ce", "deleted": false, "trackId": "fca19082-8f96-3b31-ba4d-8ac065921770", "lastModifiedTimestamp": "0", "playlistId": "7ed97737-a7f0-493d-9445-0827841b54e0", "clientId": "fc692865-40d2-11e8-9107-44032cfab7ce", "source": 1, "precedingEntryId": "fc692864-40d2-11e8-888d-44032cfab7ce", "creationTimestamp": "-1"}}, {"create": {"followingEntryId": "fc692867-40d2-11e8-b225-44032cfab7ce", "deleted": false, "trackId": "2cd6ee90-8924-3dc9-9f8c-83ef3644a18b", "lastModifiedTimestamp": "0", "playlistId": "7ed97737-a7f0-493d-9445-0827841b54e0", "clientId": "fc692866-40d2-11e8-94b6-44032cfab7ce", "source": 1, "precedingEntryId": "fc692865-40d2-11e8-9107-44032cfab7ce", "creationTimestamp": "-1"}}, {"create": {"deleted": false, "trackId": "526bfa58-e2ee-3a5f-82cc-cdd7bd88f855", "lastModifiedTimestamp": "0", "playlistId": "7ed97737-a7f0-493d-9445-0827841b54e0", "clientId": "fc692867-40d2-11e8-b225-44032cfab7ce", "source": 1, "precedingEntryId": "fc692866-40d2-11e8-94b6-44032cfab7ce", "creationTimestamp": "-1"}}]}', u'method': u'POST', u'params': {u'dv': 0, u'tier': u'fr', u'alt': u'json', u'hl': 'en_US'}})
(response was: u'{"error":{"errors":[{"domain":"global","reason":"backendError","message":"Backend Error"}],"code":500,"message":"Backend Error"}}')

This worked about a week ago.

**Comment by simon-weber** [comment]
Have you done a lot of editing of playlists recently? I've seen this in the context of https://autoplaylists.simon.codes, where Google seems to get overloaded and start responding with 500s. If that's what's going on here, it'll usually fix itself after stopping the edits and waiting for a while (up to a day or so).

**Comment by taschaal** [comment]
I Actually run it nightly to generate a set of random playlists, so maybe that is my issue. I'll hold off for a few days and see if it resolves itself. Thanks for the prompt response. 


Sent via the Samsung Galaxy S7, an AT&T 4G LTE smartphone
-------- Original message --------From: Simon Weber <notifications@github.com> Date: 4/15/18  11:41 AM  (GMT-08:00) To: simon-weber/gmusicapi <gmusicapi@noreply.github.com> Cc: taschaal <taschaal@gmail.com>, Author <author@noreply.github.com> Subject: Re: [simon-weber/gmusicapi] Unable to edit playlists created with
  create_playlist (#605) 
Have you done a lot of editing of playlists recently? I've seen this in the context of https://autoplaylists.simon.codes, where Google seems to get overloaded and start responding with 500s. If that's what's going on here, it'll usually fix itself after stopping the edits and waiting for a while (up to a day or so).

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/simon-weber/gmusicapi","title":"simon-weber/gmusicapi","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/simon-weber/gmusicapi"}},"updates":{"snippets":[{"icon":"PERSON","message":"@simon-weber in #605: Have you done a lot of editing of playlists recently? I've seen this in the context of https://autoplaylists.simon.codes, where Google seems to get overloaded and start responding with 500s. If that's what's going on here, it'll usually fix itself after stopping the edits and waiting for a while (up to a day or so)."}],"action":{"name":"View Issue","url":"https://github.com/simon-weber/gmusicapi/issues/605#issuecomment-381428297"}}}

**Comment by taschaal** [comment]
It started working again.  Thanks for your assistance.

**Comment by simon-weber** [comment]
Sure thing!
