### ISSUE TITLE
Getting top tracks for artist

### ISSUE THREAD

**Issue by adnidor** [simon-weber/gmusicapi#607]
It would be nice to have the ability to get the top tracks for a specific artist, was requested in mopidy/mopidy-gmusic#184

**Comment by adnidor** [comment]
As it turns out I just can't read documentation.

https://unofficial-google-music-api.readthedocs.io/en/latest/reference/mobileclient.html#gmusicapi.clients.Mobileclient.get_artist_info seems to be the moethod used for this

**Comment by simon-weber** [comment]
Haha, no worries. Glad you found it.
