### ISSUE TITLE
Thumbs up songs not found by get_all_songs() if they aren't in music library

### ISSUE THREAD

**Issue by aduriseti** [simon-weber/gmusicapi#611]
I looked at the methods for getting thumbs up playlist songs suggested in #200 and #99 but both rely on finding songs with get_all_songs - which only finds songs in the music library.

Obviously the mobile client can compute which songs have a thumbs up somehow - even if the songs aren't in the music library - is there a way to replicate this functionality with the api?

**Comment by simon-weber** [comment]
Yup, that's correct.

**Comment by aduriseti** [comment]
oh well - guess it can't be helped then

**Comment by blha303** [comment]
If it's generated in the client, you can get it on a one-off basis with this javascript:

    t=document.getElementsByClassName("song-row");o=[];for(i=0;i<t.length;i++){o.push(t[i].attributes["data-id"].value)};prompt("Copy from below",o.join("\n"))

With the caveat that, apparently, gmusic doesn't actually load any rows that aren't in your viewport. I got around this by zooming the page to 25% before running it, but you may have to take multiple samples after scrolling depending on the length of your autoplaylist.

**Comment by aduriseti** [comment]
hey - this thread is for the mobile client 

also this is a python api - how would I execute javascript?

I'm pretty curious - being able to get the autoplaylist would simplify things 

Also - are you having any authentication problems w/ this api?

**Comment by blha303** [comment]
I'm also using gmusicapi.Mobileclient, but there's no way to get autoplaylists through the API.

As I said, on a one-off basis you could open the client (the web client at play.google.com/music) and use that javascript to get the track IDs, that you could then individually download.

I'm having no authentication problems.

**Comment by aduriseti** [comment]
ahh - I see  - sorry I didn't understand 

I thought you were using the web client to access the page via javascript somehow

How are you authenticating?  Are you using the MAC # or are you using a device id?  What's your device type?  Over what time scale have you been using the api? (I'm asking b/c I haven't used this api in a few months so maybe there was a change to this api or google's auth system in the meantime)

**Comment by blha303** [comment]
I'm using the mac address of an old phone, retrieved from the web client via more javascript for simplicity. I've been using gmusicapi for years, it's incredibly useful.

**Comment by aduriseti** [comment]
Nice - are you able to get audio streams?  Do you have 2fa w/ and app password for your account?  What's your account type - premium I'm guessing?

**Comment by blha303** [comment]
I don't think this is relevant to the issue, but ok. gmusicapi works as well as it always has. No I don't have 2fa or app passwords because it needs my real login for the mobileclient class. Yes I have premium. Yes I can get audio streams, see https://gist.github.com/blha303/3ffedf1f3e2be13cb372240aeacfabdf

**Comment by aduriseti** [comment]
Thanks - this is quite helpful for working through my authentication issues
