### ISSUE TITLE
Playlist/situation hits not returned from search method with max_results set to None (default)

### ISSUE THREAD

**Issue by thebigmunch** [simon-weber/gmusicapi#617]
As described in #614 , starting at https://github.com/simon-weber/gmusicapi/issues/614#issuecomment-426261579.  Creating a separate issue just in case.

Possible decisions are changing the default right away, documenting the new behavior for those that want to get more than 100 results of certain types and don't care about playlist/situation hits, or wait to see if the behavior reverts.

Let me know and I'll submit a PR.

**Comment by simon-weber** [comment]
Cool, I'll reopen the old issue.
