### ISSUE TITLE
'suggestedQuery' not defined by 'properties' or 'patternProperties'

### ISSUE THREAD

**Issue by vinyldarkscratch** [simon-weber/gmusicapi#628]
It looks like this is an issue that happened way back with #305 and was supposedly fixed by #307.  However, it looks like it's an issue yet again.  Google thinks that a search for "Attiliate Headbangers" (my record label's very first release) is a typo, and includes a `suggestedQuery` for "affiliate headbangers" in its place, which is causing the validator to panic.

A search for `suggestedQuery` in `protocol/mobileclient.py` comes up empty.  Whatever fix #307 included seems to be gone now.

**Comment by simon-weber** [comment]
I pulled in your fix. Thanks!
