### ISSUE TITLE
Finding genre of song given song name and its artist or only song name 

### ISSUE THREAD

**Issue by Priyansh2** [simon-weber/gmusicapi#631]
Can anyone tell me how i can find the genre of a song given song name or song name and its artist(s).

**Comment by simon-weber** [comment]
For subscription accounts and tracks in the Play Store, try [Mobileclient.search](https://unofficial-google-music-api.readthedocs.io/en/latest/reference/mobileclient.html#gmusicapi.clients.Mobileclient.search).

For non-subscription accounts or tracks in your library, you'll need to search over the results of [Mobileclient.get_all_songs](https://unofficial-google-music-api.readthedocs.io/en/latest/reference/mobileclient.html#gmusicapi.clients.Mobileclient.get_all_songs).

**Comment by Priyansh2** [comment]
@simon-weber What if there were no songs/tracks in my library. I want a solution where i can give any random song provided it is in the database of apple music and can get its genre. The method `get_all_songs` returns all the songs in my library if i'm not wrong and what if i want to find the genre of song which is not present in my library.

**Comment by simon-weber** [comment]
You'd have to have a subscription account and use the first approach. The apis Google Music expose to us don't allow for querying the Play Store db otherwise.
