### ISSUE TITLE
Update on the "thumbs up" playlist

### ISSUE THREAD

**Issue by justin-gerhardt** [simon-weber/gmusicapi#633]
As has been noted in previous issues I have noticed that MobileClient::get_all_playlists does not return the auto-generated playlists. The current workaround seems to be to look for thumbed up tracks in library but this omits songs that are rated but not added.

I did a bit of digging in the play music web application and found a request to `https://play.google.com/music/services/getephemthumbsup`. I played with the parameters a bit and found you can get a json response describing all thumbs up'ed tracks (added to the library or not) by sending a post request with no query parameters or body and an `Authorization: Bearer` header set to the oauth access token from the MobileClient.

**Comment by simon-weber** [comment]
That's interesting. I'm pretty sure I tested cross-api auth in the past and only got 403s.

I wonder if Google's mobile clients use that endpoint, or whether it's a more general thing that auth works for other endpoints now.

**Comment by thebigmunch** [comment]
> I wonder if Google's mobile clients use that endpoint, or whether it's a more general thing that auth works for other endpoints now.

It doesn't. #560 and my experience say that the ``ephemeral/top`` mobile endpoint returns the same as ``https://play.google.com/music/services/getephemthumbsup`` for the mobile clients.

I'm definitely going to test out using web calls with mobile auth, though, as I've been chasing down [reliability](https://github.com/thebigmunch/google-music/issues/3) in moving or adding multiple songs (to anywhere but the end) in playlists and the ``plentriesbatch`` endpoint is [flaky](https://github.com/thebigmunch/google-music/issues/1#issuecomment-436257515) on Google's end. For example, a simple test Google's client fails is if you move 2 songs from the end of a playlist to the beginning, one song will end up at the end again once the client syncs. I believe this happens for any mutations that rely on each other in the same batch call. I have yet to try with the ``plentries`` endpoint which exists, but, last time I was playing with playlists in Google's web client, it seemed reliable.

If you don't test it before I do, I'll report back on cross-API auth.

**Comment by thebigmunch** [comment]
Ah, right. I remember better after my morning warmup. ``ephemeral/top`` returns store thumbs up songs (may have done something different at one point, but I haven't seen anything but thumbs up songs in years). ``https://play.google.com/music/services/getephemthumbsup`` returns the actual playlist. And I think I remember seeing calls for the last added and free & purchased playlists, too, if cross-API auth works out.

**Comment by justin-gerhardt** [comment]
"Recently Added" and "Free & Purchased" appears to be generated from `https://play.google.com/music/services/streamingloadalltracks?format=jsarray`. Get or post requests work and mobile oauth tokens are accepted. Unfortunately, the output format is an undocumented js array embedded in html. Requesting json just 400's

**Comment by thebigmunch** [comment]
gmusicapi already has support for Google's jsarray in utils because of its previous Webclient functionality.

**Comment by thebigmunch** [comment]
So, you can definitely get a 200 response. But all I got when poking at it quick is an empty track list.

@justin-gerhardt You can set the ``format`` param to ``json`` to get back regular JSON.

**Comment by thebigmunch** [comment]
So, I was getting an empty track list because ``https://play.google.com/music/services/getephemthumbsup`` only returns non-library thumbs up songs (just like ``ephemeral/top``), not the playlist itself. Seems it works the same way as mobile for library thumbs up songs.

@justin-gerhardt Can you confirm this with using ``format=json``?

TL/DR This specific call doesn't add anything for the mobile client. But the fact that you can seem to call the web API with a Mobile token (only tested with Bearer) seems useful.

**Comment by justin-gerhardt** [comment]
I can confirm that `https://play.google.com/music/services/getephemthumbsup` is producing a json response (with no format parameter) that lists all of the "store" songs that I've thumbed up. It omits songs that have been uploaded. This is the same behavior as you have described for the mobile `ephemeral/top` url. I was mainly interested in it as it permits getting thumbed up store songs that have not been added to the library (the primary way I use play music). I didn't realize this seems to be already implemented under the name "promoted songs". In particular the description for `MobileClient::get_promoted_songs` makes it sound more like the algorithmic "I'm feeling lucky" rather than the thumbed up playlist.

The `https://play.google.com/music/services/streamingloadalltracks` url with a format parameter set to json produces a 400 error. It appears to only function with format set to jsarray. That said it's only notable for completeness, the information it produces seems to be no greater than the existing `MobileClient::get_all_songs` method.

Overall, your conclusion seems to be correct, these url's add nothing to the current implementation but they are interesting for auth reasons.

**Comment by thebigmunch** [comment]
> The `https://play.google.com/music/services/streamingloadalltracks` url with a format parameter set to json produces a 400 error. It appears to only function with format set to jsarray. That said it's only notable for completeness, the information it produces seems to be no greater than the existing

I'm not sure how you were doing it, but it certainly returned properly for me with the ``format`` param set to ``json``. Using requests, I simply set ``params={'format': 'json'}`` in ``requests.post``. Using the Composer in Fiddler, it was just a matter of changing it in the URL.

> I didn't realize this seems to be already implemented under the name "promoted songs".

Nobody is quite sure. Like Simon, I seem to recall it doing something other than just returning store thumbs up songs at some point in the past. Given its name vs the naming in the Web API, that's probably correct. I haven't seen it do anything but return thumbs up songs with my own accounts for years now. That doesn't necessarily mean it doesn't still. But, knowing Google, they probably changed what they were doing with it and didn't bother to use a better endpoint like ``ephemeral/thumbsup`` (which doesn't seem to exist and definitely isn't used).

> Overall, your conclusion seems to be correct, these url's add nothing to the current implementation but they are interesting for auth reasons.

Probably the most useful web API call for the Mobileclient would be for editing song metadata; Google removed that capability from the Mobile API years ago.

**Comment by thebigmunch** [comment]
We were talking about the streamingloadalltracks call...

I haven't looked that call to see if there is a format param for it or not. Not at my computer to test with curl and the thumbs up call, but that works just fine as I said with requests and Fiddler.

Also, the metadata changing is already figured out and implemented for the Webclient in gmusicapi. All that would have to be done is making it calls let with the Mobileclient.

**Comment by justin-gerhardt** [comment]
Excellent, already implemented features are the best features.

**Comment by thebigmunch** [comment]
Double fun fact, you can also use a bearer token from the Music Manager side of things to access the web calls.

**Comment by justin-gerhardt** [comment]
Can a mobile token access the Music Manager api?

**Comment by thebigmunch** [comment]
> Can a mobile token access the Music Manager api?

Nope. No holy grail there it seems. Each scope appears to be limited to specific Google client IDs, so no cross-calling there.

**Comment by justin-gerhardt** [comment]
Do you mean the api errors or the scope can't be requested? I just tried using the mobile client creds to request both https://www.googleapis.com/auth/musicmanager and https://www.googleapis.com/auth/skyjam scopes and that worked. I haven't tested calling the api yet though.

**Comment by thebigmunch** [comment]
You can get a token. But cross-API calls will fail with a 403.
