### ISSUE TITLE
Gmusicapi.clients.OAUTH_FILEPATH is deprecated

### ISSUE THREAD

**Issue by Forceflow** [simon-weber/gmusicapi#634]
```
/usr/local/lib/python3.6/dist-packages/gmusicapi/__init__.py:4: GmusicapiWarning: gmusicapi.clients.OAUTH_FILEPATH is deprecated and will be removed; use Musicmanager.OAUTH_FILEPATH
```
This started popping up - latest version.

**Comment by Forceflow** [comment]
I'm using gmusicapi through the (now deprecated, but they are still the only scripts that work reliably for me - no offense to thebigmunch ) ) gmusicapi-scripts, so I cannot really pin down where this error originates from. From the import itself?

**Comment by simon-weber** [comment]
That's correct. I don't know of an easy way to show that warning only if the property is accessed (since it's on a module), so it shows for everybody. I'll remove it at some point, probably soon.

You don't need to do anything unless you're making use of the old property.

**Comment by simon-weber** [comment]
12.0.0 removes the warning and the deprecated property.
