### ISSUE TITLE
Mobileclient.remove_entries_from_playlist doesn't accept playlist_id parameter

### ISSUE THREAD

**Issue by markguindi1** [simon-weber/gmusicapi#640]
It would seem that the `Mobileclient.remove_entries_from_playlist` method would remove songs from a specific playlist (and that's also what the [docs](https://unofficial-google-music-api.readthedocs.io/en/latest/reference/mobileclient.html#gmusicapi.clients.Mobileclient.remove_entries_from_playlist) seem to imply when it says "Removes specific entries from a playlist"). But to do so, wouldn't it need to accept a `playlist_id` parameter to know which playlist to delete from? The docs don't specify anything of that sort, and even in the source code for the mobileclient (found [here,](https://github.com/simon-weber/gmusicapi/blob/99c64dda0215956886aa0de23befbce5d539ead8/gmusicapi/clients/mobileclient.py) line 706) it seems like the method only accepts an `entry_ids` parameter. 

Would anybody be able to clarify if this method somehow really does accept the `playlist_id` parameter (even if it's not evident in the code/docs), or, if it doesn't accept the `playlist_id` parameter, possibly fix it to include it?

And, by the way, I'm curious about what the current behavior of `Mobileclient.remove_entries_from_playlist` is if it doesn't accept the `playlist_id` parameter (I would try it out myself, but I don't want to mess up my music playlists).

**Comment by thebigmunch** [comment]
Playlists and playlist entries are separated in Google Music for technical reasons. Showing playlist entries for a playlist is actually a client-side operation because of this; the ID of the playlist a playlist entry belongs to is stored in the playlist entry. There's no need to specify the playlist to remove a playlist entry from that playlist, because it's not part of that operation at all. What you're actually doing is deleting the playlist entry from your playlist entries list.

**Comment by simon-weber** [comment]
Yup, that's right. Playlist entries are already unique (at least per account, but probably globally too), so there's no need to provide a playlist id.

**Comment by markguindi1** [comment]
I think I understand now. Looking at the docs again, I see that each playlist entry dict has both an `id` key and a `trackId` key. The `id` is used for this particular "instance" of the song in the playlist, while the `trackId` is used for the song in general. For example, if I have a certain song in 2 playlists, then their `id`s will be different, and their `trackId`s will be the same. 

So when I want to make a call to `Mobileclient.remove_entries_from_playlist`, I pass in the `id`s of the songs I want to remove, as that `id` uniquely identifies the occurrence of that song in this particular playlist, and it will remove it from that playlist.

I was getting confused because I knew that songs had a `trackId`, which I've already used in my existing code to add songs to a playlist, and I thought you were supposed to pass _that_ to `Mobileclient.remove_entries_from_playlist`. That's why I thought it wouldn't know which playlist to delete it from. 

Thank you for the clarification @thebigmunch @simon-weber !
