### ISSUE TITLE
Mobileclient.get_all_songs does not include beatsPerMinute property

### ISSUE THREAD

**Issue by pankajPizone** [simon-weber/gmusicapi#642]
Mobileclient.get_all_songs() function doesn't  include **beatsPerMinute** property in response of songs but 
 gmusicapi document example have beatsPerMinute property in json.

**Comment by simon-weber** [comment]
That field is optional. Refer to [the protocol code](https://github.com/simon-weber/gmusicapi/blob/99c64dda0215956886aa0de23befbce5d539ead8/gmusicapi/protocol/mobileclient.py#L139) for the exact schema.

**Comment by pankajPizone** [comment]
@simon-weber How can i get beatsPerMinute?

**Comment by simon-weber** [comment]
If it's not present in the dictionary, then Google isn't making it available for that song; there's nothing else we can do on our end.
