### ISSUE TITLE
Not able to get recent songs which is recently played by user using GMusicApi?

### ISSUE THREAD

**Issue by pankajPizone** [simon-weber/gmusicapi#643]

**Comment by simon-weber** [comment]
I don't think Google provides that metadata over non-webclient apis, so it's not really possible with gmusicapi. [Autoplaylists](https://github.com/simon-weber/Autoplaylists-for-Google-Music) can do this, though.

**Comment by pankajPizone** [comment]
@simon-weber We can only get songs which is added in library there is any feature of Gmusicapi to get all songs which is played?

**Comment by simon-weber** [comment]
We don't currently know of a way to do that for non-library tracks. https://github.com/simon-weber/gmusicapi/issues/182 is an old issue that tracks that.
