### ISSUE TITLE
Failed to authenticate

### ISSUE THREAD

**Issue by pankajPizone** [simon-weber/gmusicapi#645]
I'm login with email, passwd and deviceid for android.

I have login my account on Google Music Play and register device for this account and account have subscription but still i cant login, why?

**Comment by simon-weber** [comment]
I don't really have enough details from this to help you, but if you're using the deprecated SSO auth flow, please switch to the OAuth flow. There is an example here: https://unofficial-google-music-api.readthedocs.io/en/latest/usage.html#quickstart.

**Comment by pankajPizone** [comment]
Is there is any way to authenticate user when i'm using 2 factor authentication?
