### ISSUE TITLE
get_all_songs returning songs not visible on web UI in playlist

### ISSUE THREAD

**Issue by joshtrobins** [simon-weber/gmusicapi#646]
This seems like a bug on the google side to me...

I have a playlist with 900+ songs. I use get_all_songs to pull down the full list of songs I have added to every playlist. It appears that songs I at one point added to the large playlist have since disappeared from the playlist. This is normal Google behavior so I am not surprised and that is why I wrote a tool to detect this using gmusicapi.

However, what I did not expect is that gmusicapi get_all_songs is actually returning the missing songs, they just can't be found in the actual web view. I am using 12.1.0.

**Comment by simon-weber** [comment]
Yeah, I don't think there's much to do on our end. My guess would be you'd see the same discrepancy in their mobile app.

You could try loading the site incognito in case it has to do with their local bookkeeping.

**Comment by joshtrobins** [comment]
I recreated the playlist by deleting it and adding everything back and all the songs are visible now... weird. /shrug

**Comment by simon-weber** [comment]
¯\_(ツ)_/¯
