### ISSUE TITLE
Connection Aborted when searching for a song

### ISSUE THREAD

**Issue by wootiown** [simon-weber/gmusicapi#647]
After searching for a song, it looks like the connection was somehow terminated. This was during a livestream on twitch and there were no noticeable connection issues whatsoever on my end.

This was after the script ran and searched for songs for around an hour, it randomly dies after about an hour.

![](https://cdn.discordapp.com/attachments/538866706140102676/544337534122196992/2.png)

**Comment by simon-weber** [comment]
Hm. My guess would be it's some kind of rate limiting on their end, or maybe just a periodic hiccup.

Either way, I'm not sure there's much we can do at the library level about it. If it's a script you maintain, some retry logic might do the trick.

**Comment by wootiown** [comment]
Thanks for the quick response, that's what I figured but I just wanted to make sure it wasn't something that anyone else was experiencing. I'll try out the retry logic, cheers.
