### ISSUE TITLE
Gmusicapi install error

### ISSUE THREAD

**Issue by codingnoob233** [simon-weber/gmusicapi#651]
Hi I'm helping a friend to install this but everytime he gets to running setup.py install for pycrypto gets an error. Followed buy wall of red text. Saying does not support clang
Everything else goes smoothly except for here.

**Comment by simon-weber** [comment]
Can you paste the error and share the OS, please? They probably need to install some supporting libraries, but I don't have enough information yet to point you in the right direction.

**Comment by codingnoob233** [comment]
Running setup.py install for lxml ... error ERROR: Complete output from command /data/data/com.termux/files/usr/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/data/data/com.termux/files/usr/tmp/pip-install-46lci3bp/lxml/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /data/data/com.termux/files/usr/tmp/pip-record-oro9v2bt/install-record.txt --single-version-externally-managed --compile:
ERROR: Building lxml version 4.3.4. Building without Cython.
Using build configuration of libxslt 1.1.33
Building against libxml2/libxslt in the following directory: /data/data/com.termux/files/usr/lib
running install
running build
running build_py creating build
creating build/lib.linux-aarch64-3.7 creating build/lib.linux-aarch64-3.7/lxml
copying src/lxml/sax.py -> build/lib.linux-aarch64-3.7/lxml
copying src/lxml/_elementpath.py -> build/lib.linux-aarch64-3.7/lxml
copying src/lxml/builder.py -> build/lib.linux-aarch64-3.7/lxml
copying src/lxml/ElementInclude.py -> build/lib.linux-aarch64-3.7/lxml
copying src/lxml/__init__.py -> build/lib.linux-aarch64-3.7/lxml
copying src/lxml/usedoctest.py -> build/lib.linux-aarch64-3.7/lxml
copying src/lxml/cssselect.py -> build/lib.linux-aarch64-3.7/lxml
copying src/lxml/pyclasslookup.py -> build/lib.linux-aarch64-3.7/lxml
copying src/lxml/doctestcompare.py -> build/lib.linux-aarch64-3.7/lxml
creating build/lib.linux-aarch64-3.7/lxml/includes
copying src/lxml/includes/__init__.py -> build/lib.linux-aarch64-3.7/lxml/includes
creating build/lib.linux-aarch64-3.7/lxml/html copying src/lxml/html/diff.py -> build/lib.linux-aarch64-3.7/lxml/html copying src/lxml/html/ElementSoup.py -> build/lib.linux-aarch64-3.7/lxml/html copying src/lxml/html/html5parser.py -> build/lib.linux-aarch64-3.7/lxml/html copying src/lxml/html/builder.py -> build/lib.linux-aarch64-3.7/lxml/html copying src/lxml/html/__init__.py -> build/lib.linux-aarch64-3.7/lxml/html
.linux-aarch64-3.7/lxml/html copying src/lxml/html/usedoctest.py -> build/lib.linux-aarch64-3.7/lxml/html copying src/lxml/html/_setmixin.py -> build/lib.linux-aarch64-3.7/lxml/html copying src/lxml/html/clean.py -> build/lib.linux-aarch64-3.7/lxml/html copying src/lxml/html/soupparser.py -> build/lib.linux-aarch64-3.7/lxml/html copying src/lxml/html/_html5builder.py -> build/lib.linux-aarch64-3.7/lxml/html copying src/lxml/html/_diffcommand.py -> build/lib.linux-aarch64-3.7/lxml/html copying src/lxml/html/formfill.py -> build/lib.linux-aarch64-3.7/lxml/html copying src/lxml/html/defs.py -> build/lib.linux-aarch64-3.7/lxml/html creating build/lib.linux-aarch64-3.7/lxml/isoschematron copying src/lxml/isoschematron/__init__.py -> build/lib.linux-aarch64-3.7/lxml/isoschematron copying src/lxml/etree.h -> build/lib.linux-aarch64-3.7/lxml copying src/lxml/etree_api.h -> build/lib.linux-aarch64-3.7/lxml
copying src/lxml/lxml.etree.h -> build/lib.linux-aarch64-3.7/lxml copying src/lxml/lxml.etree_api.h -> build/lib.linux-aarch64-3.7/lxml copying src/lxml/includes/etreepublic.pxd -> build/lib.linux-aarch64-3.7/lxml/includes copying src/lxml/includes/xinclude.pxd -> build/lib.linux-aarch64-3.7/lxml/includes copying src/lxml/includes/xmlerror.pxd -> build/lib.linux-aarch64-3.7/lxml/includes copying src/lxml/includes/htmlparser.pxd -> build/lib.linux-aarch64-3.7/lxml/includes copying src/lxml/includes/config.pxd -> build/lib.linux-aarch64-3.7/lxml/includescopying src/lxml/includes/__init__.pxd -> build/lib.linux-aarch64-3.7/lxml/includes
copying src/lxml/includes/xmlschema.pxd -> build/lib.linux-aarch64-3.7/lxml/includes
copying src/lxml/includes/uri.pxd -> build/lib.linux-aarch64-3.7/lxml/includes copying src/lxml/includes/xslt.pxd -> build/lib.linux-aarch64-3.7/lxml/includes copying src/lxml/includes/tree.pxd -> build/lib.linux-aarch64-3.7/lxml/includes
copying src/lxml/includes/xmlparser.pxd -> build/lib.linux-aarch64-3.7/lxml/includes
copying src/lxml/includes/dtdvalid.pxd -> build/lib.linux-aarch64-3.7/lxml/includes copying src/lxml/includes/xpath.pxd -> build/lib.linux-aarch64-3.7/lxml/includes
copying src/lxml/includes/relaxng.pxd -> build/lib.linux-aarch64-3.7/lxml/includes copying src/lxml/includes/c14n.pxd -> build/lib.linux-aarch64-3.7/lxml/includes
copying src/lxml/includes/schematron.pxd -> build/lib.linux-aarch64-3.7/lxml/includes copying src/lxml/includes/etree_defs.h -> build/lib.linux-aarch64-3.7/lxml/includes
copying src/lxml/includes/lxml-version.h -> build/lib.linux-aarch64-3.7/lxml/includes creating build/lib.linux-aarch64-3.7/lxml/isoschematron/resources
creating build/lib.linux-aarch64-3.7/lxml/isoschematron/resources/rng copying src/lxml/isoschematron/resources/rng/iso-schematron.rng -> build/lib.linux-aarch64-3.7/lxml/isoschematron/resources/rng creating build/lib.linux-aarch64-3.7/lxml/isoschematron/resources/xsl copying src/lxml/isoschematron/resources/xsl/RNG2Schtrn.xsl -> build/lib.linux-aarch64-3.7/lxml/isoschematron/resources/xslcopying src/lxml/isoschematron/resources/xsl/XSD2Schtrn.xsl -> build/lib.linux-aarch64-3.7/lxml/isoschematron/resources/xsl
creating build/lib.linux-aarch64-3.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1 copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_dsdl_include.xsl -> build/lib.linux-aarch64-3.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1 copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_abstract_expand.xsl -> build/lib.linux-aarch64-3.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_skeleton_for_xslt1.xsl -> build/lib.linux-aarch64-3.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_message.xsl -> build/lib.linux-aarch64-3.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_svrl_for_xslt1.xsl -> build/lib.linux-aarch64-3.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/readme.txt -> build/lib.linux-aarch64-3.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
running build_ext
building 'lxml.etree' extension
creating build/temp.linux-aarch64-3.7 creating build/temp.linux-aarch64-3.7/src
creating build/temp.linux-aarch64-3.7/src/lxml
aarch64-linux-android-clang -Wno-unused-result -Wsign-compare -Wunreachable-code
DNDEBUG -g -fwrapv -O3 -Wall -Oz -Oz -fPIC -DCYTHON_CLINE_IN_TRACEBACK=0 -I/data/data/com.termux/files/usr/include -I/data/data/com.termux/files/usr/include/libxml2 -Isrc -Isrc/lxml/includes -I/data/data/com.termux/files/usr/include/python3.7m -c src/lxml/etree.c -o build/temp.linux-aarch64-3.7/src/lxml/etree.o -w In file included from src/lxml/etree.c:692:
In file included from src/lxml/includes/etree_defs.h:186:
In file included from /data/data/com.termux/files/usr/include/libxml2/libxml/tree.h:1307:
In file included from /data/data/com.termux/files/usr/include/libxml2/libxml/xmlmemory.h:218:
In file included from /data/data/com.termux/files/usr/include/libxml2/libxml/threads.h:35:
In file included from /data/data/com.termux/files/usr/include/libxml2/libxml/globals.h:18: In file included from /data/data/com.termux/files/usr/include/libxml2/libxml/parser.h:810:
/data/data/com.termux/files/usr/include/libxml2/libxml/encoding.h:28:10: fatal error: 'iconv.h' file not found #include <iconv.h>
^~~~~~~~~ 1 error generated.
Compile failed: command 'aarch64-linux-android-clang' failed with exit status 1
creating data creating data/data
creating data/data/com.termux
creating data/data/com.termux/files creating data/data/com.termux/files/usr creating data/data/com.termux/files/usr/tmp cc -I/data/data/com.termux/files/usr/include -I/data/data/com.termux/files/usr/include/libxml2 -I/usr/include/libxml2 -c /data/data/com.termux/files/usr/tmp/xmlXPathInit5xnmnqtl.c -o data/data/com.termux/files/usr/tmp/xmlXPathInit5xnmnqtl.o In file included from /data/data/com.termux/files/usr/tmp/xmlXPathInit5xnmnqtl.c:1: In file included from /data/data/com.termux/files/usr/include/libxml2/libxml/xpath.h:26:
In file included from /data/data/com.termux/files/usr/include/libxml2/libxml/xmlerror.h:10:
In file included from /data/data/com.termux/files/usr/include/libxml2/libxml/parser.h:810:
/data/data/com.termux/files/usr/include/libxml2/libxml/encoding.h:28:10: fatal error: 'iconv.h' file not found
#include <iconv.h>
^~~~~~~~~
1 error generated.
********************************************************************************* Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed? *********************************************************************************
error: command 'aarch64-linux-android-clang' failed with exit status 1
----------------------------------------
ERROR: Command "/data/data/com.termux/files/usr/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/data/data/com.termux/files/usr/tmp/pip-install-46lci3bp/lxml/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /data/data/com.termux/files/usr/tmp/pip-record-oro9v2bt/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /data/data/com.termux/files/usr/tmp/pip-install-46lci3bp/

**Comment by simon-weber** [comment]
This looks to be the relevant error: `Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?`.

More details at https://lxml.de/installation.html#requirements.

**Comment by codingnoob233** [comment]
Can I get back to you later on this topic.

**Comment by codingnoob233** [comment]
Ok here's what it is now 
Running setup.py install for pycryptodomex ... error                                  ERROR: Complete output from command /data/data/com.termux/files/usr/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/data/data/com.termux/files/usr/tmp/pip-install-__6ykt5r/pycryptodomex/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /data/data/com.termux/files/usr/tmp/pip-record-f5izvb4a/install-record.txt --single-version-externally-managed --compile:                                  ERROR: Testing support for clang          Target does not support clang             Testing support for gcc

**Comment by codingnoob233** [comment]
--compile:                                  ERROR: Testing support for clang          Target does not support clang             Testing support for gcc                   Target does not support gcc               Testing support for stdint.h header       Target does not support stdint.h header                                             Testing support for 128-bit integer       Target does not support 128-bit integer                                             Testing support for intrin.h header       Target does not support intrin.h header                                             Testing support for cpuid.h header        Target does not support

**Comment by simon-weber** [comment]
That doesn't look like the complete output. There's nothing immediately obvious in that to me.

Almost certainly it's a similar issue to before, though. Look through the output completely: like before, there should be something in there suggesting what you need to install.

**Comment by codingnoob233** [comment]
Ok told him to do pip install lxml because that's what's missing did it now gets error 
Is libxml2 installed?.Which he did install so idk

**Comment by codingnoob233** [comment]
Hey he installed everything on the link you gave me still won't get pass installing lxml.

**Comment by simon-weber** [comment]
It's probably best to see if the lxml folks can help in that case.
