### ISSUE TITLE
get filesize of audiofile

### ISSUE THREAD

**Issue by silelmot** [simon-weber/gmusicapi#654]
Hello,
is it possible to get the estimated filesize of an audiofile?

i want to create an time for a music-downloader in python.
for now i solve this by the number of titles getting downloaded, but it would be way more accurate if i could work with the filesize of the titles.

**Comment by simon-weber** [comment]
There should be an estimatedSize key in mobileclient [song dicts](https://unofficial-google-music-api.readthedocs.io/en/latest/reference/mobileclient.html#gmusicapi.clients.Mobileclient.get_all_songs) you can use.
