### ISSUE TITLE
Mobileclient.get_all_songs() not returning all tracks

### ISSUE THREAD

**Issue by frankhalligan** [simon-weber/gmusicapi#661]
I have 10,466 tracks in my library. These are all uploaded, no purchased tracks. On music.google.com, if I go to "Music Library => Songs", it shows 10,466 songs available.

Up until recently, get_all_songs() would return all 10,466. However, starting within the last few days, it's missing a lot of tracks (currently returns 10,367). There doesn't seem to be any pattern to the songs that are excluded, it's all single tracks from many different albums, no different to the surrounding tracks.

Oddly, if I play a track that's missing through the browser, it is then returned by get_all_songs() in subsequent calls. Is this just a Google Play Music issue, or has anyone come across anything similar?

**Comment by simon-weber** [comment]
Huh, weird. My gut is that it's a temporary Google issue - it sounds a bit like what I've seen with [Autoplaylists](https://github.com/simon-weber/Autoplaylists-for-Google-Music/) where playlist changes go missing unexpectedly - but I haven't heard of this specific problem before myself.

**Comment by frankhalligan** [comment]
Typical, as soon as I get around to making an issue, it solves itself! 10,466 being returned again, obviously a temporary glitch with GPM
