### ISSUE TITLE
No Donation Button

### ISSUE THREAD

**Issue by arcsector** [simon-weber/gmusicapi#662]
Music is everything for me as a developer, so this really saved my day when i found out i didn't have to write this myself. Please put something in the `README` and let me buy you guys a beer.

**Comment by arcsector** [comment]
You can close this if you want, I just really am thankful for this

**Comment by simon-weber** [comment]
Hah, I'm flattered! I set up a [sponsors profile](https://github.com/sponsors/simon-weber) recently -- you could be the first!
