### ISSUE TITLE
Invalid Device id with id's returned from returned valid id's

### ISSUE THREAD

**Issue by Lttlwing16** [simon-weber/gmusicapi#663]
Stuck in a loop on mc.oauth_login which returns a list of valid id's, but doesn't accept any of the id's listed when entered in the format `mc.oauth_login('<#my16bitidhere>')`

Caveat is I'm running this on raspberry pi 3B+ with Moode audio, which uses upmpdcli, which also fails to login, from what appears to be using the deprecated `Mobileclient.login` within it's api. I've cleared the credentials from the login within the gui to no avail.

**Comment by Lttlwing16** [comment]
Fixed. Was issuing the command wrong. Needed to omit <> from the device id. `mc.oauth_login(device_id='my16bitidhere')` fixed it. Can now confirm am able to access GPM from Bubbleupnp via moode.

**Comment by simon-weber** [comment]
Ah, ok. I haven't looked at that code in a while -- was the error printing the original/incorrect format?

**Comment by Lttlwing16** [comment]
Thanks Simon, the error did return the incorrect format, but it escaped me until I had an 'aha' moment. 

Just have to figure how to integrate with upmpdcli now!

**Comment by simon-weber** [comment]
Do you have an example of the error message? Running it myself just now seems to show copy-pastable values, so I wonder if there was something platform-specific going on.

Here's how mine look (I changed the actual values):
```
>>> mc.oauth_login("foo")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/simon/gmusicapi/gmusicapi/clients/mobileclient.py", line 184, in oauth_login
    return self._login(session_login, device_id, locale)
  File "/home/simon/gmusicapi/gmusicapi/clients/mobileclient.py", line 138, in _login
    self.android_id = self._validate_device_id(device_id, is_mac=is_mac)
  File "/home/simon/gmusicapi/gmusicapi/clients/mobileclient.py", line 75, in _validate_device_id
    raise InvalidDeviceId('Invalid device_id %s.' % device_id, device_ids)
gmusicapi.exceptions.InvalidDeviceId: Invalid device_id foo.Your valid device IDs are:
* E123456ABCDE
* ios:12345678-1234-ABCD-1234-1234567890AB
```

**Comment by Lttlwing16** [comment]
Mine looked identical but because I was issuing 'mc.oauth_login('<16bitidhere>') it included the <16bithexjere> in the error, so it didn't register at first.

**Comment by simon-weber** [comment]
Gotcha. Glad you got it figured out!

**Comment by Lttlwing16** [comment]
You'd be up to helping me implement within upmpdcli-gmusic? I'd like to get this running for Moode audio.

**Comment by simon-weber** [comment]
I don't really want to commit to anything, but I can try to answer questions as they come up.

**Comment by Lttlwing16** [comment]
Totally understand! I'll follow the usage guide and see if I can get it working. Just mainly need to move from using deprecated .login to .oauth_login

**Comment by Lttlwing16** [comment]
If you don't mind to have a look, but I think this modification should pull it in. I'm not at home (editing remotely) so I can't test it out until later. deviceid is pulled from user input on the moode login page. This is from Session.py of the plugin. 

Thanks in advance. 

`def login(self, deviceid):
        self.api = Mobileclient(debug_logging=False)

#        if deviceid is None:
#            logged_in = self.api.login(username, password,
#                                       Mobileclient.FROM_MAC_ADDRESS)
#            if logged_in:
#                # Try to re-login with a valid deviceid
#                data = self.api.get_registered_devices()
#                #self.dmpdata("registered devices", data)
#                deviceid = self.find_device_id(data)
#                if deviceid:
#                    logged_in = self.login(username, password, deviceid)
        else:
            logged_in = self.api.oauth_login('deviceid')
`

**Comment by simon-weber** [comment]
minor errors aside something like that ought to be fine. be sure to actually run the oauth exchange before calling oauth_login, though ([eg](https://unofficial-google-music-api.readthedocs.io/en/latest/usage.html#quickstart)).

**Comment by Lttlwing16** [comment]
It's probably pretty obvious I'm not a programmer. Just a determined, interested user. Oh well, learning Python is interesting and this is good starting place. So honestly, thanks for taking the time to look.

That aside, I've put in a request with the dev of upmpdcli to have him update the code to use perform_oauth and oauth_login. That said I'm currently just interested in getting it running on my machine, while I wait *if* he'll update the code. 

I've ran perform_oauth manually and have a token configured on the machine. I can now enter the oauth_login and return True straight away. Just for my personal uses, would I need to program the perform_oauth in the Session.py if it is already configured?

**Comment by simon-weber** [comment]
> I've ran perform_oauth manually and have a token configured on the machine. I can now enter the oauth_login and return True straight away. Just for my personal uses, would I need to program the perform_oauth in the Session.py if it is already configured?

You should be all set on that machine now.

**Comment by Lttlwing16** [comment]
So then a user could manually configure perform_oauth via python shell, then the rest of the login process could occur through the Session.py/GUI

**Comment by Lttlwing16** [comment]
Simon do you know how I can purge previous oauth tokens? The developer for upmpdcli is trying to implement the new oauth_login method and I have a previous token which I generated manually from the command line. I'd like to remove it as to make sure it isn't interfering with his oauth call. 

*I was able to properly use his method to generate a new token, and output it to file, but in trying to trouble shoot, I wanted to purge the old tokens I had previously created directly through the python shell.

Thanks!

**Comment by simon-weber** [comment]
I don't have links handy, but it's a standard google oauth flow so you should be able to find it in either Google's docs or the oauth2client docs.

**Comment by Lttlwing16** [comment]
Thanks Simon, we got it worked out and upmpdcli has the new oauth login method implemented and functional. Thanks for your help👍

**Comment by simon-weber** [comment]
Great!
