### ISSUE TITLE
Could not retrieve credentials from ... Simon Weber\\gmusicapi\\mobileclient.cred

### ISSUE THREAD

**Issue by mrgou** [simon-weber/gmusicapi#665]
This looks quite unexpected:

```python
from gmusicapi import Mobileclient
api = Mobileclient()

mydevice_id = 'abc123'

api.oauth_login(mydevice_id)
```
    C:\Users\username\miniconda3\envs\py38\lib\site-packages\oauth2client\_helpers.py:255: UserWarning: Cannot access C:\Users\username\AppData\Local\Simon Weber\gmusicapi\mobileclient.cred: No such file or directory
      warnings.warn(_MISSING_FILE_MESSAGE.format(filename))
    2020-04-28 21:50:18,911 - gmusicapi.Mobileclient1 (shared:176) [WARNING]: could not retrieve oauth credentials from ''C:\\Users\\username\\AppData\\Local\\Simon Weber\\gmusicapi\\mobileclient.cred''
    
    False

Looks like some filepath remained in the code. I'm using version `13.0.0`.

**Comment by simon-weber** [comment]
Huh. I wonder if you got a distribution that has packaged bytecode instead of source or something.

Did you install with pip or with conda?

**Comment by simon-weber** [comment]
Ah, nope, I just forgot that's how appdirs works: it namespaces by the author and package name.

You probably just want [to run perform_oauth](https://unofficial-google-music-api.readthedocs.io/en/latest/usage.html#quickstart) first so that the credential file is created.

**Comment by mrgou** [comment]
Yes, indeed, I managed to make it work. I just thought that an error message that indicates a filepath on the developer's computer it quite unexpected!

**Comment by simon-weber** [comment]
Yup, it threw me off at first too. To be clear, though, it's just the output of `appdirs.user_data_dir(appname="gmusicapi", appauthor="Simon Weber")`.
