### ISSUE TITLE
Error while performing local test

### ISSUE THREAD

**Issue by himanshujaidka** [simon-weber/gmusicapi#672]
On performing local test it shows the function error

**Comment by himanshujaidka** [comment]
![functest](https://user-images.githubusercontent.com/58654018/88520188-da5fff80-d010-11ea-8ef2-bb219ddbd4db.png)

**Comment by simon-weber** [comment]
This is mentioned in the [installation docs](https://unofficial-google-music-api.readthedocs.io/en/latest/usage.html#installation):
> If you’re going to be uploading music, you’ll likely need avconv or ffmpeg installed...

**Comment by himanshujaidka** [comment]
I have installed it but it is not working I virtual environment
